// Binary routing-matrix walks every fixture under
// `conformance/fixtures/` (excluding the leading-underscore
// quarantine directories) and emits a Markdown table of `Shape |
// Route | Strict` rows. The output is a non-blocking CI artifact
// surfaced by `task conformance:routing-matrix` (plan 16,
// `docs/ENGINE_POLICY.md`) and used by
// reviewers to spot when a fixture family's actual route does not
// match its directory's aspirational label.
//
// The walker reads YAML only -- it does NOT talk to a live
// emulator. The fixture's `expected.route` is the source of
// truth for the matrix column; the runner enforces that the
// engine actually emits that route at execution time.
//
// Determinism: rows are sorted by fixture path so two consecutive
// invocations produce byte-identical output (pinned by
// `routing_matrix_test.go::TestRoutingMatrixIsReproducible`).
package main

import (
	"flag"
	"fmt"
	"io"
	"os"
	"path/filepath"
	"slices"
	"sort"
	"strings"

	"github.com/vantaboard/bigquery-emulator/conformance/runner"
)

func main() {
	code, err := run(os.Args[1:], os.Stdout, os.Stderr)
	if err != nil {
		fmt.Fprintln(os.Stderr, "routing-matrix:", err)
	}
	os.Exit(code)
}

func run(args []string, stdout, stderr io.Writer) (int, error) {
	fs := flag.NewFlagSet("routing-matrix", flag.ContinueOnError)
	fs.SetOutput(stderr)
	fixturesDir := fs.String("fixtures", "conformance/fixtures",
		"path to the fixtures directory (or single fixture file)")
	outputFile := fs.String("output-file", "",
		"if set, write the Markdown table to this path (truncate). "+
			"Stdout still receives the same bytes for piping.")
	if err := fs.Parse(args); err != nil {
		return 2, err
	}
	table, err := buildMatrix(*fixturesDir)
	if err != nil {
		return 1, err
	}
	if _, err := io.WriteString(stdout, table); err != nil {
		return 1, err
	}
	if *outputFile != "" {
		// 0o600 keeps gosec G306 quiet -- the matrix is a
		// reproducible function of the public fixture YAMLs and
		// has no secret content, but the linter wants a strict
		// mode and the CI artifact uploader (or local
		// inspection) does not rely on group-readable
		// permissions on the on-disk copy.
		if err := os.WriteFile(*outputFile, []byte(table), 0o600); err != nil {
			return 1, fmt.Errorf("write %s: %w", *outputFile, err)
		}
	}
	return 0, nil
}

// matrixRow is the rendered shape of a single fixture in the
// matrix output. Kept private to the rendering helpers below.
type matrixRow struct {
	shape  string
	route  string
	strict bool
}

// buildMatrix loads every fixture under `dir` (LoadDir already
// skips the `_*/` quarantine directories) and renders a Markdown
// table sorted by fixture path. The third column flags
// `route_strict: false` rows so a reviewer can spot the
// documentation-only entries (typically error-path fixtures whose
// engine response never carries a trailer).
func buildMatrix(dir string) (string, error) {
	fixtures, err := runner.LoadDir(dir)
	if err != nil {
		return "", err
	}
	rows := collectMatrixRows(fixtures, dir)
	return renderMatrix(rows), nil
}

// collectMatrixRows converts loaded fixtures into the sorted-by-
// shape row set the renderer expects. Path normalization
// (forward-slash, suffix-stripped) lives here so the rendering
// helper stays pure-string.
func collectMatrixRows(fixtures []*runner.Fixture, dir string) []matrixRow {
	rows := make([]matrixRow, 0, len(fixtures))
	for _, f := range fixtures {
		rel, err := filepath.Rel(dir, f.Path)
		if err != nil {
			rel = f.Path
		}
		shape := filepath.ToSlash(
			strings.TrimSuffix(rel, filepath.Ext(rel)),
		)
		route := f.Expected.Route
		if route == "" && len(f.Expected.RouteAllowlist) > 0 {
			route = "[" + strings.Join(f.Expected.RouteAllowlist, ", ") + "]"
		}
		if route == "" {
			route = "(unassigned)"
		}
		rows = append(rows, matrixRow{
			shape:  shape,
			route:  route,
			strict: f.Expected.RouteStrictDefault(),
		})
	}
	sort.SliceStable(rows, func(i, j int) bool { return rows[i].shape < rows[j].shape })
	return rows
}

// renderMatrix produces the Markdown body. Pulled out of
// buildMatrix to keep the statement count below the funlen cap
// and to make the renderer trivially diffable in tests.
func renderMatrix(rows []matrixRow) string {
	counts := map[string]int{}
	for _, r := range rows {
		counts[r.route]++
	}
	var b strings.Builder
	b.WriteString(matrixHeader)
	writeSummary(&b, counts, len(rows))
	writePerFixture(&b, rows)
	return b.String()
}

const matrixHeader = `# Conformance routing matrix

Generated by ` + "`task conformance:routing-matrix`" + `. Each row pins the route the coordinator's ` +
	"`RouteClassifier`" + ` chooses for the fixture's ` + "`query:`" + ` step (the ` + "`setup:`" +
	` steps run on their own routes).

Strict=` + "`false`" + ` flags documentation-only rows: the engine returns before ` +
	"`EmitTrailers`" + ` fires (typically error-path fixtures), so the runner skips the assertion at execution time. The route value stays in the matrix as planning-time documentation.

`

func writeSummary(b *strings.Builder, counts map[string]int, total int) {
	b.WriteString("## Per-route totals\n\n| Route | Count |\n|---|---|\n")
	for _, name := range runner.KnownRouteNames() {
		if n := counts[name]; n > 0 {
			fmt.Fprintf(b, "| `%s` | %d |\n", name, n)
		}
	}
	// Print any non-canonical buckets (allowlist-rendered rows,
	// `(unassigned)`) AFTER the canonical block so a stray label
	// is visible to a reviewer.
	for k := range counts {
		if !isCanonicalRoute(k) {
			fmt.Fprintf(b, "| `%s` | %d |\n", k, counts[k])
		}
	}
	fmt.Fprintf(b, "| **total** | %d |\n", total)
}

func writePerFixture(b *strings.Builder, rows []matrixRow) {
	b.WriteString("\n## Per-fixture\n\n| Shape | Route | Strict |\n|---|---|---|\n")
	for _, r := range rows {
		strict := "true"
		if !r.strict {
			strict = "false"
		}
		fmt.Fprintf(b, "| `%s` | `%s` | %s |\n", r.shape, r.route, strict)
	}
}

func isCanonicalRoute(s string) bool {
	return slices.Contains(runner.KnownRouteNames(), s)
}
