#include "backend/engine/engine.h"

// This file ships only the abstract engine interfaces; the
// reference-impl and DuckDB engines live in their own translation
// units. This translation unit exists so the engine library has at
// least one source file for the build system to compile, and so the
// v-tables for the abstract classes have a single definition site
// (otherwise -Wweak-vtables can fire on the concrete impls).

namespace bigquery_emulator {
namespace backend {
namespace engine {

// Out-of-line key functions anchor the v-tables for the abstract
// interfaces. The destructors are still trivially generated by the
// compiler from the `= default` declarations in the header, but
// putting their out-of-line definitions here gives the linker a
// single .o to attach the v-table to.
AnalyzedQuery::~AnalyzedQuery() = default;
RowSource::~RowSource() = default;
Engine::~Engine() = default;

}  // namespace engine
}  // namespace backend
}  // namespace bigquery_emulator
