#include "backend/sqltools/sql_completion_data.h"

namespace bigquery_emulator {
namespace backend {
namespace sqltools {
namespace {

const std::vector<ClauseWordEntry>& BuildClauseWords() {
  static const std::vector<ClauseWordEntry>* kEntries =
      new std::vector<ClauseWordEntry>{
          {"SELECT", "select"},
          {"FROM", "from"},
          {"INNER JOIN", "join"},
          {"CROSS JOIN", "join"},
          {"FULL OUTER JOIN", "join"},
          {"FULL JOIN", "join"},
          {"LEFT OUTER JOIN", "join"},
          {"LEFT JOIN", "join"},
          {"RIGHT OUTER JOIN", "join"},
          {"RIGHT JOIN", "join"},
          {"JOIN", "join"},
          {"ON", "on"},
          {"USING", "using"},
          {"WHERE", "where"},
          {"GROUP BY", "group"},
          {"GROUPING SETS", "group"},
          {"HAVING", "having"},
          {"ORDER BY", "order"},
          {"NULLS FIRST", "order"},
          {"NULLS LAST", "order"},
          {"UNION ALL", "union"},
          {"UNION DISTINCT", "union"},
          {"INTERSECT DISTINCT", "intersect"},
          {"EXCEPT DISTINCT", "intersect"},
          {"LIMIT", "limit"},
          {"OFFSET", "offset"},
          {"WITH", "with"},
          {"WITH DATA", "with"},
          {"WITH PARTITION COLUMNS", "partition"},
          {"PARTITION BY", "partition"},
          {"WINDOW", "window"},
          {"CREATE TEMPORARY FUNCTION", "udf"},
          {"CREATE TEMP FUNCTION", "udf"},
          {"CREATE FUNCTION IF NOT EXISTS", "udf"},
          {"CREATE OR REPLACE FUNCTION", "udf"},
          {"CREATE FUNCTION", "udf"},
          {"CREATE TEMPORARY AGGREGATE FUNCTION", "udaf"},
          {"CREATE TEMP AGGREGATE FUNCTION", "udaf"},
          {"CREATE AGGREGATE FUNCTION IF NOT EXISTS", "udaf"},
          {"CREATE OR REPLACE AGGREGATE FUNCTION", "udaf"},
          {"CREATE AGGREGATE FUNCTION", "udf"},
          {"CREATE PROCEDURE", "procedure"},
          {"CREATE OR REPLACE PROCEDURE", "procedure"},
          {"CREATE PROCEDURE IF NOT EXISTS", "procedure"},
          {"DELETE", "delete"},
          {"INSERT INTO", "insert"},
          {"INSERT", "insert"},
          {"UPDATE", "update"},
          {"MERGE INTO", "merge"},
          {"MERGE", "merge"},
          {"WHEN MATCHED", "match"},
          {"WHEN NOT MATCHED BY TARGET", "match"},
          {"WHEN NOT MATCHED BY SOURCE", "match"},
          {"WHEN NOT MATCHED", "match"},
          {"SET", "set"},
          {"VALUES", "values"},
          {"CREATE TABLE IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE TABLE", "create"},
          {"CREATE TABLE", "create"},
          {"CREATE EXTERNAL TABLE IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE EXTERNAL TABLE", "create"},
          {"CREATE EXTERNAL TABLE", "create"},
          {"CREATE MATERIALIZED VIEW IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE MATERIALIZED VIEW", "create"},
          {"CREATE MATERIALIZED VIEW", "create"},
          {"CREATE VIEW IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE VIEW", "create"},
          {"CREATE VIEW", "create"},
          {"CREATE MODEL IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE MODEL", "create"},
          {"CREATE MODEL", "create"},
          {"CREATE ROW ACCESS POLICY IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE ROW ACCESS POLICY", "create"},
          {"CREATE ROW ACCESS POLICY", "create"},
          {"CREATE RESERVATION", "create"},
          {"CREATE RESERVATION IF NOT EXISTS", "create"},
          {"CREATE CAPACITY", "create"},
          {"CREATE ASSIGNMENT", "create"},
          {"CREATE SCHEMA", "create"},
          {"CREATE SCHEMA IF NOT EXISTS", "create"},
          {"CREATE SNAPSHOT TABLE IF NOT EXISTS", "create"},
          {"CREATE SNAPSHOT TABLE", "create"},
          {"CREATE SEARCH INDEX", "create"},
          {"CREATE SEARCH INDEX IF NOT EXISTS", "create"},
          {"CREATE VECTOR INDEX", "create"},
          {"CREATE VECTOR INDEX IF NOT EXISTS", "create"},
          {"DROP TABLE IF EXISTS", "drop"},
          {"DROP TABLE", "drop"},
          {"DROP EXTERNAL TABLE IF EXISTS", "drop"},
          {"DROP EXTERNAL TABLE", "drop"},
          {"DROP MATERIALIZED VIEW IF EXISTS", "drop"},
          {"DROP MATERIALIZED VIEW", "drop"},
          {"DROP VIEW IF EXISTS", "drop"},
          {"DROP VIEW", "drop"},
          {"DROP FUNCTION IF EXISTS", "drop"},
          {"DROP FUNCTION", "drop"},
          {"DROP PROCEDURE", "drop"},
          {"DROP PROCEDURE IF EXISTS", "drop"},
          {"DROP ROW ACCESS POLICY", "drop"},
          {"DROP ROW ACCESS POLICY IF EXISTS", "drop"},
          {"DROP ALL ROW ACCESS POLICIES", "drop"},
          {"TRUNCATE TABLE", "drop"},
          {"DROP RESERVATION IF EXISTS", "drop"},
          {"DROP RESERVATION", "drop"},
          {"DROP CAPACITY IF EXISTS", "drop"},
          {"DROP CAPACITY", "drop"},
          {"DROP ASSIGNMENT IF EXISTS", "drop"},
          {"DROP ASSIGNMENT", "drop"},
          {"DROP SCHEMA IF EXISTS", "drop"},
          {"DROP SCHEMA", "drop"},
          {"DROP SNAPSHOT TABLE IF EXISTS", "drop"},
          {"DROP SNAPSHOT TABLE", "drop"},
          {"DROP SEARCH INDEX", "drop"},
          {"DROP SEARCH INDEX IF EXISTS", "drop"},
          {"DROP VECTOR INDEX", "drop"},
          {"DROP VECTOR INDEX IF EXISTS", "drop"},
          {"DROP", "drop"},
          {"CLUSTER BY", "cluster"},
          {"ALTER TABLE IF EXISTS", "alter"},
          {"ALTER TABLE", "alter"},
          {"ALTER MATERIALIZED VIEW IF EXISTS", "alter"},
          {"ALTER MATERIALIZED VIEW", "alter"},
          {"ALTER VIEW IF EXISTS", "alter"},
          {"ALTER VIEW", "alter"},
          {"ALTER SCHEMA IF EXISTS", "alter"},
          {"ALTER SCHEMA", "alter"},
          {"ALTER BI_CAPACITY", "alter"},
          {"ALTER CAPACITY", "alter"},
          {"ALTER ORGANIZATION", "alter"},
          {"ALTER PROJECT", "alter"},
          {"ALTER RESERVATION", "alter"},
          {"DECLARE", "declare"},
          {"SET", "set"},
          {"IF", "if"},
          {"EXECUTE IMMEDIATE", "execute immediate"},
          {"LOOP", "loop"},
          {"WHILE", "loop"},
          {"BEGIN", "begin"},
          {"BEGIN TRANSACTION", "begin"},
          {"COMMIT", "end"},
          {"COMMIT TRANSACTION", "end"},
          {"ROLLBACK", "end"},
          {"ROLLBACK TRANSACTION", "end"},
          {"END", "end"},
          {"END IF", "end"},
          {"END WHILE", "end"},
          {"END LOOP", "end"},
          {"CONTINUE", "continue"},
          {"ITERATE", "continue"},
          {"BREAK", "break"},
          {"LEAVE", "break"},
          {"CALL", "call"},
          {"ASSERT", "assert"},
          {"EXPORT DATA", "export"},
          {"EXPORT DATA WITH CONNECTION", "export"},
          {"EXPORT TABLE METADATA", "export"},
          {"LOAD DATA INTO", "load"},
          {"LOAD DATA OVERWRITE", "load"},
          {"PARTITIONS", "load"},
          {"OVERWRITE PARTITIONS", "load"},
          {"FROM FILES", "load"},
          {"ADD CONSTRAINT", "alter"},
          {"ADD FOREIGN KEY", "alter"},
          {"ADD PRIMARY KEY", "alter"},
          {"DROP CONSTRAINT", "alter"},
          {"DROP PRIMARY KEY", "alter"},
          {"AS REPLICA OF", "create"},
          {"CONSTRAINT", "create"},
          {"ENFORCED", "create"},
          {"FOREIGN KEY", "create"},
          {"NOT ENFORCED", "create"},
          {"PRIMARY KEY", "create"},
          {"REFERENCES", "create"},
          {"UNDROP SCHEMA", "undrop"},
          {"UNDROP SCHEMA IF NOT EXISTS", "undrop"},
          {"QUALIFY", "qualify"},
          {"EXTEND", "pipe"},
          {"AGGREGATE", "pipe"},
          {"TABLESAMPLE", "pipe"},
          {"PIVOT", "pipe"},
          {"UNPIVOT", "pipe"},
          {"RENAME", "pipe"},
          {"MATCH_RECOGNIZE", "match_recognize"},
          {"MEASURES", "match_recognize"},
          {"PATTERN", "match_recognize"},
          {"DEFINE", "match_recognize"},
          {"AFTER MATCH SKIP TO NEXT ROW", "match_recognize"},
          {"AFTER MATCH SKIP PAST LAST ROW", "match_recognize"},
      };
  return *kEntries;
}

const std::vector<std::string>& BuildExpressionKeywords() {
  static const std::vector<std::string>* kEntries =
      new std::vector<std::string>{
          "ACCESS",
          "ADD",
          "AFTER",
          "AGGREGATE",
          "ALL",
          "ALTER",
          "AND",
          "ANY",
          "ARRAY",
          "AS",
          "ASC",
          "ASSERT_ROWS_MODIFIED",
          "ASSIGNMENT",
          "AT",
          "BEGIN",
          "BETWEEN",
          "BI_CAPACITY",
          "BY",
          "CAPACITY",
          "CASCADE",
          "CASE",
          "CAST",
          "CLONE",
          "CLUSTER",
          "COLLATE",
          "COLUMN",
          "COLUMNS",
          "COMMIT",
          "CONNECTION",
          "CONSTRAINT",
          "CREATE",
          "CROSS",
          "CUBE",
          "CURRENT",
          "DATA",
          "DEFAULT",
          "DEFINE",
          "DESC",
          "DETERMINISTIC",
          "DISTINCT",
          "DO",
          "DROP",
          "ELSE",
          "ELSEIF",
          "END",
          "ENFORCED",
          "ENUM",
          "ESCAPE",
          "EXCEPT",
          "EXCLUDE",
          "EXECUTE",
          "EXISTS",
          "EXPORT",
          "EXTEND",
          "EXTERNAL",
          "EXTRACT",
          "FALSE",
          "FETCH",
          "FILES",
          "FILTER",
          "FIRST",
          "FOLLOWING",
          "FOR",
          "FOREIGN",
          "FULL",
          "FUNCTION",
          "GENERATED",
          "GRANT",
          "GROUP",
          "GROUPING",
          "GROUPS",
          "HASH",
          "IDENTITY",
          "IF",
          "IGNORE",
          "IMMEDIATE",
          "IN",
          "INCREMENT",
          "INDEX",
          "INNER",
          "INOUT",
          "INTERSECT",
          "INTERVAL",
          "INTO",
          "IS",
          "KEY",
          "LANGUAGE",
          "LAST",
          "LATERAL",
          "LEFT",
          "LIKE",
          "LOAD",
          "LOOKUP",
          "MATCH",
          "MATCHED",
          "MATCH_RECOGNIZE",
          "MATERIALIZED",
          "MEASURES",
          "MERGE",
          "METADATA",
          "MODEL",
          "NATURAL",
          "NEW",
          "NEXT",
          "NO",
          "NOT",
          "NULL",
          "NULLS",
          "OF",
          "OPTIONS",
          "OR",
          "ORDER",
          "ORGANIZATION",
          "OUT",
          "OUTER",
          "OVER",
          "OVERWRITE",
          "PARTITION",
          "PARTITIONS",
          "PAST",
          "PATTERN",
          "PIVOT",
          "POLICIES",
          "POLICY",
          "PRECEDING",
          "PREV",
          "PRIMARY",
          "PROCEDURE",
          "PROJECT",
          "PROTO",
          "QUALIFY",
          "RANGE",
          "RECURSIVE",
          "REFERENCES",
          "RENAME",
          "REPEAT",
          "REPLICA",
          "RESERVATION",
          "RESPECT",
          "RESTRICT",
          "RETURNS",
          "RIGHT",
          "ROLLBACK",
          "ROLLUP",
          "ROW",
          "ROWS",
          "SCHEMA",
          "SEARCH",
          "SET",
          "SETS",
          "SKIP",
          "SNAPSHOT",
          "SOME",
          "SOURCE",
          "START",
          "STRUCT",
          "TABLE",
          "TABLESAMPLE",
          "TARGET",
          "TEMP",
          "TEMPORARY",
          "THEN",
          "TO",
          "TRANSACTION",
          "TREAT",
          "TRUE",
          "TRUNCATE",
          "UNBOUNDED",
          "UNDROP",
          "UNION",
          "UNNEST",
          "UNPIVOT",
          "UNTIL",
          "USING",
          "VIEW",
          "WHEN",
          "WITH",
          "WITHIN",
      };
  return *kEntries;
}

const std::vector<FunctionInfoEntry>& BuildFunctionInfo() {
  static const std::vector<FunctionInfoEntry>* kEntries =
      new std::vector<FunctionInfoEntry>{
          {"ABS", "numeric_expr", "Computes absolute value. Returns an error if theargument isan integer and the output value cannot be represented as the same type; this happens only for the largest negative input value, which has no positive representation. Returns +inf for a +/-inf argument.", ""},
          {"ACOS", "numeric_expr", "Computes the principal value of the arc cosine of <numeric_expr>. The return value is in the range [0,]. Generates an error if <numeric_expr> is a finite value outside of range [-1, 1].", ""},
          {"ACOSH", "numeric_expr", "Computes the inverse hyperbolic cosine of <numeric_expr>. Generates an error if <numeric_expr> is a finite value less than 1.", ""},
          {"ANY_VALUE", "expr", "Returns any value from the input or NULL if there are zero input rows. The value returned is non-deterministic, which means you might receive a different result each time you use this function.", ""},
          {"APPROX_COUNT_DISTINCT", "expr", "Returns the approximate result for COUNT(DISTINCT <expr>). The value returned is a statistical estimate\\u2014not necessarily the actual value.\\n\\nThis function is less accurate than COUNT(DISTINCT <expr>), but performs better on huge input.", ""},
          {"APPROX_QUANTILES", "expr, number", "Returns the approximate boundaries for a group of <expr> values, where <number> represents the number of quantiles to create. This function returns an array of <number> + 1 elements, where the first element is the approximate minimum and the last element is the approximate maximum.", ""},
          {"APPROX_TOP_COUNT", "expr, number", "Returns the approximate top elements of <expr>. The <number> parameter specifies the number of elements returned.", ""},
          {"ARRAY_AGG", "expr", "Returns an ARRAY of <expr> values.", ""},
          {"ARRAY_CONCAT", "array_expr1 [, array_expr_n]", "Concatenates one or more arrays with the same element type into a single array.", ""},
          {"ARRAY_CONCAT_AGG", "expr", "Concatenates elements from <expr> of type ARRAY, returning a single ARRAY as a result. This function ignores NULL input arrays, but respects the NULL elements in non-NULL input arrays (an error is raised, however, if an array in the final query result contains a NULL element).", ""},
          {"ARRAY_LENGTH", "array_expr", "Returns the size of the array. Returns 0 for an empty array. Returns NULL if the <array_expr> is NULL.", ""},
          {"ARRAY_TO_STRING", "array_expr, delimiter [, null_text]", "Returns a concatenation of the elements in <array_expr> as a STRING. The value for <array_expr> can either be an array of STRING or BYTES data types.", ""},
          {"ASCII", "value", "Returns the ASCII code for the first character of the input (STRING type), or for the first byte of the input (BYTES type). Function returns 0 if the string is empty, or the first character/byte's ASCII code is 0.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#ascii"},
          {"ASIN", "numeric_expr", "Computes the principal value of the arc sine of <numeric_expr>. The return value is in the range [-\\u03c0/2,\\u03c0/2]. Generates an error if X is a finite value outside of range [-1, 1].", ""},
          {"ASINH", "numeric_expr", "Computes the inverse hyperbolic sine of <numeric_expr>. Does not fail.", ""},
          {"ATAN", "numeric_expr", "Computes the principal value of the arc tangent of <numeric_expr>. The return value is in the range [-\\u03c0/2,\\u03c0/2]. Does not fail.", ""},
          {"ATANH", "numeric_expr", "Computes the inverse hyperbolic tangent of <numeric_expr>. Generates an error if the absolute value of <numeric_expr> is greater or equal 1.", ""},
          {"ATAN2", "numeric_expr, numeric_expr", "Calculates the principal value of the arc tangent of Y/X using the signs of the two arguments to determine the quadrant. The return value is in the range [-\\u03c0,\\u03c0]. ", ""},
          {"AVG", "expr", "Returns the average of non-NULL input values, or NaN if the input contains a NaN.", ""},
          {"BIT_AND", "expr", "Performs a bitwise AND operation on expression and returns the result.", ""},
          {"BIT_OR", "expr", "Performs a bitwise OR operation on expression and returns the result.", ""},
          {"BIT_XOR", "expr", "Performs a bitwise XOR operation on <expr> and returns the result.", ""},
          {"BYTE_LENGTH", "value", "Returns the length of the <value> in bytes, regardless of whether the type of the value is STRING or BYTES.", ""},
          {"CAST", "expr AS typename", "Converts <expr> into a variable of type <typename>.", ""},
          {"CEIL", "numeric_expr", "Returns the smallest integral value (with FLOAT64 type) that is not less than <numeric_expr>.", ""},
          {"CEILING", "numeric_expr", "Synonym of CEIL.", ""},
          {"CHAR_LENGTH", "value", "Returns the length of the STRING in characters.", ""},
          {"CHARACTER_LENGTH", "value", "Synonym for CHAR_LENGTH.", ""},
          {"CHR", "value", "Returns the character that matches the input Unicode code point. Each valid code point should fall within the range of [0, 0xD7FF] and [0xE000, 0x10FFFF]. If an invalid Unicode code point is specified, an error is returned.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#chr"},
          {"CONCAT", "value1 [, ...]", "Concatenates one or more values into a single result.", ""},
          {"COS", "numeric_expr", "Computes cosine of <numeric_expr>. Never fails.", ""},
          {"COSH", "numeric_expr", "Computes the hyperbolic cosine of <numeric_expr>. Generates an error if an overflow occurs.", ""},
          {"COUNT", "expr", "Returns the total number of values (NULL and non-NULL for <*>, non-NULL for <field>) in the scope of the function. With DISTINCT returns the number of distinct values for the specified field.", ""},
          {"COUNTIF", "expr", "Returns the count of TRUE values for <expr>. Returns 0 if there are zero input rows or <expr> evaluates to FALSE for all rows.", ""},
          {"CUME_DIST", "", "Return the relative rank of a row defined as NP/NR. NP is defined to be the number of rows that either precede or are peers with the current row. NR is the number of rows in the partition.", ""},
          {"CURRENT_DATE", "[time_zone]", "Returns the current date as of the specified or default timezone.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#current_date"},
          {"CURRENT_TIMESTAMP", "", "Parentheses are optional. This function handles leap seconds by smearing them across a window of 20 hours around the inserted leap second. CURRENT_TIMESTAMP() produces a TIMESTAMP value that is continuous, non-ambiguous, has exactly 60 seconds per minute and does not repeat values over the leap second.", ""},
          {"DATE", "timestamp_expr [, time_zone]", "Converts a <timestamp_expr> to a DATE data type. It supports an optional parameter to specify a timezone. If no timezone is specified, the default timezone, UTC, is used.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date"},
          {"DATE_ADD", "date_expr, INTERVAL int64_expr date_part", "Adds a specified time interval to a DATE.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date_add"},
          {"DATE_DIFF", "date_expr, date_expr, date_part", "Returns the number of <date_part> boundaries between the two <date_expr>s. If the first date occurs before the second date, then the result is non-positive.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date_diff"},
          {"DATE_FROM_UNIX_DATE", "INT64_expr", "Interprets <INT64_expr> as the number of days since 1970-01-01.", ""},
          {"DATE_SUB", "date_expr, INTERVAL int64_expr date_part", "Subtracts a specified time interval from a DATE.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date_sub"},
          {"DATE_TRUNC", "date_expr, date_part", "Truncates the date to the specified granularity.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date_trunc"},
          {"DENSE_RANK", "", "Returns the ordinal (1-based) rank of each row within the window partition. All peer rows receive the same rank value, and the subsequent rank value is incremented by one.", ""},
          {"DIV", "numeric_expr, numeric_expr", "Returns the result of integer division of X by Y. Division by zero returns an error. Division by -1 may overflow. See the table below for possible result types.", ""},
          {"ENDS_WITH", "value1, value2", "Takes two values. Returns TRUE if <value2> is a suffix of <value1>.", ""},
          {"EXP", "numeric_expr", "Computes e to the power of <numeric_expr>, also called the natural exponential function. If the result underflows, this function returns a zero. Generates an error if the result overflows. If <numeric_expr> is +/-inf, then this function returns +inf or 0.", ""},
          {"EXTRACT", "datetime_part FROM timestamp_expr [AT TIME ZONE tz_spec]", "Returns the value corresponding to the specified date part.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#extract"},
          {"FIRST_VALUE", "value_expr", "Returns the value of the <value_expr> for the first row in the current window frame.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#first_value"},
          {"FLOOR", "numeric_expr", "Returns the largest integral value (with FLOAT64 type) that is not greater than <numeric_expr>.", ""},
          {"FORMAT", "format_string, format_specifier1 [, ...]", "BigQuery supports a FORMAT() function for formatting strings. This function is similar to the C printf function. It produces a STRING from a format string that contains zero or more format specifiers, along with a variable length list of additional arguments that matches the format specifiers.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#format"},
          {"FORMAT_DATE", "format_string, date", "Formats the date_expr according to the specified <format_string>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#format_date"},
          {"FORMAT_TIMESTAMP", "format_string, timestamp [, <time_zone>]", "Formats a timestamp according to the specified <format_string>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#format_timestamp"},
          {"GENERATE_ARRAY", "start_expression, end_expression [, step_expression]", "Returns an array of values. The <start_expression> and <end_expression> parameters determine the inclusive start and end of the array.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#generate_array"},
          {"GENERATE_DATE_ARRAY", "start_date, end_date[, INTERVAL step_expression DAY|WEEK|MONTH|QUARTER|YEAR]", "Returns an array of dates. The <start_date> and <end_date> parameters determine the inclusive start and end of the array.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#generate_date_array"},
          {"GREATEST", "numeric_expr1, numeric_expr2, ...", "Returns NULL if any of the inputs is NULL. Otherwise, returns NaN if any of the inputs is NaN. Otherwise, returns the largest value among <numeric_expr1>, <numeric_expr2>... according to the < comparison.", ""},
          {"GROUPING", "group_by_expression", "Returns 0 or 1. Returns 1 if the group_by_expression argument is being aggregated, or 0 if it is not.", ""},
          {"IEEE_DIVIDE", "numeric_expr1, numeric_expr2", "Divides <numeric_expr1> by <numeric_expr2>; this function never fails. Returns FLOAT64. Unlike the division operator (/), this function does not generate errors for division by zero or overflow.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#ieee_divide"},
          {"IFNULL", "expr, null_result", "If expr is NULL, return null_result. Otherwise, return expr. If expr is not NULL, null_result is not evaluated. expr and null_result can be any type and must be implicitly coercible to a common supertype. Synonym for COALESCE(expr, null_result).", ""},
          {"INITCAP", "input[, delimiters]", "Transform the <input> string with the first character in each word in uppercase, and all other characters in lowercase. Non-alphabetic characters will remain the same . Mapping between lowercase and uppercase is done according to the Unicode Character Database without taking into account language-specific mappings.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#initcap"},
          {"INSTR", "source_value, search_value [, position[, occurrence ]]", "Searches the occurrences of <search_value> in the <source_value>, starting from <position>, returns the start position of the search hit.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#instr"},
          {"IS_INF", "numeric_expr", "Returns TRUE if the value is positive or negative infinity. Returns NULL for NULL inputs.", ""},
          {"IS_NAN", "numeric_expr", "Returns TRUE if the value is a NaN value. Returns NULL for NULL inputs.", ""},
          {"JSON_ARRAY", "[value][, ...]", "Creates a JSON array from zero or more SQL values.", ""},
          {"JSON_REMOVE", "json_expr, json_path[, ...]", "Removes JSON data.", ""},
          {"JSON_SET", "json_expr, json_path, value[, json_path, value][...]", "Inserts or replaces existing JSON data.", ""},
          {"KLL_QUANTILES.EXTRACT_INT64", "sketch, num_quantiles", "Gets a selected number of quantiles from an INT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesextract_int64"},
          {"KLL_QUANTILES.EXTRACT_FLOAT64", "sketch, num_quantiles", "Gets a selected number of quantiles from a FLOAT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesextract_double"},
          {"KLL_QUANTILES.EXTRACT_POINT_INT64", "sketch, phi", "Gets a specific quantile from an INT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesextract_point_int64"},
          {"KLL_QUANTILES.EXTRACT_POINT_FLOAT64", "sketch, phi", "Gets a specific quantile from a FLOAT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesextract_point_double"},
          {"KLL_QUANTILES.INIT_INT64", "input[, precision [, weight => input_weight ]", "Aggregates values into an INT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesinit_int64"},
          {"KLL_QUANTILES.INIT_FLOAT64", "input[, precision [, weight => input_weight ]", "Aggregates values into a FLOAT64-initialized KLL sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesinit_double"},
          {"KLL_QUANTILES.MERGE_INT64", "sketch, num_quantiles", "Merges INT64-initialized KLL sketches into a new sketch, and then gets the quantiles from the new sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesmerge_int64"},
          {"KLL_QUANTILES.MERGE_FLOAT64", "sketch, num_quantiles", "Merges FLOAT64-initialized KLL sketches into a new sketch, and then gets the quantiles from the new sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesmerge_double"},
          {"KLL_QUANTILES.MERGE_PARTIAL", "sketch", "Merges KLL sketches of the same underlying type into a new sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesmerge_partial"},
          {"KLL_QUANTILES.MERGE_POINT_INT64", "sketch, phi", "Merges INT64-initialized KLL sketches into a new sketch, and then gets a specific quantile from the new sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesmerge_point_int64"},
          {"KLL_QUANTILES.MERGE_POINT_FLOAT64", "sketch, phi", "Merges FLOAT64-initialized KLL sketches into a new sketch, and then gets a specific quantile from the new sketch.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/kll_functions#kll_quantilesmerge_point_double"},
          {"LAG", "value_expr [, offset [, default_expr] ]", "Returns the value of the <value_expr> on a preceding row. Changing the <offset> value changes which preceding row is returned; the default value is 1, indicating the previous row in the window frame. An error occurs if <offset> is NULL or a negative value.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#lag"},
          {"LAST_DAY", "datetime_expression [, date_part]", "Returns the last day from the <datetime_expression> that contains the date. This is commonly used to return the last day of the month. You can optionally specify the <date_part> for which the last day is returned. If this parameter is not used, the default value is MONTH.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/datetime_functions#last_day"},
          {"LAST_VALUE", "value_expr", "Returns the value of the <value_expr> for the last row in the current window frame.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#last_value"},
          {"LAX_BOOL", "json_expr", "Attempts to convert a JSON value to a SQL BOOL value.", ""},
          {"LAX_FLOAT64", "json_expr", "Attempts to convert a JSON expression to a SQL FLOAT64 value.", ""},
          {"LAX_INT64", "json_expr", "Attempts to convert a JSON expression to a SQL INT64 value.", ""},
          {"LAX_STRING", "json_expr", "Attempts to convert a JSON expression to a SQL STRING value.", ""},
          {"LEAD", "value_expr [, offset [, default_expr] ]", "Returns the value of the <value_expr> on a subsequent row. Changing the <offset> value changes which subsequent row is returned; the default value is 1, indicating the next row in the window frame. An error occurs if <offset> is NULL or a negative value.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#lead"},
          {"LEAST", "numeric_expr1, numeric_expr2, ...", "Returns NULL if any of the inputs is NULL. Returns NaN if any of the inputs is NaN. Otherwise, returns the smallest value among <numeric_expr1>, <numeric_expr2>, ... according to the > comparison.", ""},
          {"LEFT", "value, length", "Returns the specified number of leftmost characters from the input STRING, or the specified number of leftmost bytes from the input BYTES.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#left"},
          {"LENGTH", "value", "Returns the length of the value. The returned value is in characters for STRING arguments and in bytes for the BYTES argument.", ""},
          {"LN", "numeric_expr", "Computes the natural logarithm of <numeric_expr>. Generates an error if <numeric_expr> is less than or equal to zero. If <numeric_expr> is +inf, then this function returns +inf.", ""},
          {"LOG", "numeric_expr [, base]", "If only <numeric_expr> is present, LOG is a synonym of LN. If <base> is also present, LOG computes the logarithm of <numeric_expr> to <base>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#log"},
          {"LOG10", "numeric_expr", "Similar to LOG, but computes logarithm to base 10.", ""},
          {"LOGICAL_AND", "expr", "Returns the logical AND of all non-NULL expressions. Returns NULL if there are zero input rows or <expr> evaluates to NULL for all rows.", ""},
          {"LOGICAL_OR", "expr", "Returns the logical OR of all non-NULL expressions. Returns NULL if there are zero input rows or <expr> evaluates to NULL for all rows.", ""},
          {"LOWER", "value", "For STRING arguments, returns the original string with all alphabetic characters in lowercase. Mapping between lowercase and uppercase is done according to the Unicode Character Database without taking into account language-specific mappings.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#lower"},
          {"LTRIM", "value1 [, value2]", "Identical to TRIM, but only removes leading characters.", ""},
          {"MAX", "expr", "Returns the maximum value of non-NULL expressions. Returns NULL if there are zero input rows or <expr> evaluates to NULL for all rows. Returns NaN if the input contains a NaN.", ""},
          {"MAX_BY", "expr1, expr2", "Returns the value of expr1 for which the value of expr2 is maximized. Returns an arbitrary value of expr1 if multiple rows match the maximized expr2. Returns NULL if expr1 evaluates to NULL for all matched rows or expr2 contains a NaN.", ""},
          {"MIN", "expr", "Returns the minimum value of non-NULL expressions. Returns NULL if there are zero input rows or <expr> evaluates to NULL for all rows. Returns NaN if the input contains a NaN.", ""},
          {"MIN_BY", "expr1, expr2", "Returns the value of expr1 for which the value of expr2 is minimized. Returns an arbitrary value of expr1 if multiple rows match the minimized expr2. Returns NULL if expr1 evaluates to NULL for all matched rows or expr2 contains a NaN.", ""},
          {"MOD", "numeric_expr1, numeric_expr2", "Modulo function: returns the remainder of the division of <numeric_expr1> by <numeric_expr2>. Returned value has the same sign as <numeric_expr1>. An error is generated if <numeric_expr2> is 0. See the table below for possible result types.", ""},
          {"NTH_VALUE", "value_expr, constant_integer_expr", "Returns the value of <value_expr> at the Nth row of the current window frame, where Nth is defined by <constant_integer_expr>. Returns NULL if there is no such row.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#nth_value"},
          {"NTILE", "constant_integer_expr", "This function divides the rows into <constant_integer_expr> buckets based on row ordering and returns the 1-based bucket number that is assigned to each row. The number of rows in the buckets can differ by at most 1. The remainder values (the remainder of number of rows divided by buckets) are distributed one for each bucket, starting with bucket 1. If <constant_integer_expr> evaluates to NULL, 0 or negative, an error is provided.", ""},
          {"OCTET_LENGTH", "input", "An alias of BYTE_LENGTH. Returns the length of the <value> in bytes, regardless of whether the type of the <value> is STRING or BYTES.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#octet_length"},
          {"OFFSET", "zero_based_offset", "Accesses an ARRAY element by position and returns the element. OFFSET means that the numbering starts at zero, ORDINAL means that the numbering starts at one.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#offset-and-ordinal"},
          {"ORDINAL", "one_based_offset", "Accesses an ARRAY element by position and returns the element. OFFSET means that the numbering starts at zero, ORDINAL means that the numbering starts at one.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#offset-and-ordinal"},
          {"PARSE_TIMESTAMP", "format_string, string [, time_zone]", "Uses a <format_string> and a string representation of a timestamp to return a TIMESTAMP object.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#parse_timestamp"},
          {"PERCENT_RANK", "", "Return the percentile rank of a row defined as (RK-1)/(NR-1), where RK is the RANK of the row and NR is the number of rows in the partition. Returns 0 if NR=1.", ""},
          {"POW", "numeric_expr1, numeric_expr2", "Returns the value of <numeric_expr1> raised to the power of <numeric_expr1>. If the result underflows and is not representable, then the function returns a value of zero.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#pow"},
          {"POWER", "numeric_expr, numeric_expr", "Synonym of POW().", ""},
          {"RANK", "", "Returns the ordinal (1-based) rank of each row within the ordered partition. All peer rows receive the same rank value. The next row or set of peer rows receives a rank value which increments by the number of peers with the previous rank value, instead of DENSE_RANK, which always increments by 1.", ""},
          {"REGEXP_CONTAINS", "value, regex", "Returns TRUE if <value> is a partial match for the regular expression, <regex>. You can search for a full match by using ^ (beginning of text) and $ (end of text).", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_contains"},
          {"REGEXP_EXTRACT", "value, regex [, position[, occurrence]]", "Returns the first substring in <value> that matches the regular expression, <regex>. Returns NULL if there is no match. If <position> is specified, the search starts at this position in value, otherwise it starts at the beginning of value. If <occurrence> is specified, the search returns a specific occurrence of the regexp in value, otherwise returns the first match.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_extract"},
          {"REGEXP_EXTRACT_ALL", "value, regex", "Returns an array of all substrings of <value> that match the regular expression, <regex>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_extract_all"},
          {"REGEXP_INSTR", "value, regex [, position[, occurrence, [return_pos_after_match]]]", "Returns the position of the specified <occurrence> of the <regex> pattern in <value>. <return_pos_after_match> can be 0 (default, returns the beginning position of the match) or 1 (returns the first position following the end of the match)", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_instr"},
          {"REGEXP_REPLACE", "value, regex, replacement", "Returns a STRING where all substrings of <value> that match regular expression <regex> are replaced with replacement.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#regexp_replace"},
          {"REGEXP_SUBSTR", "value, regexp [,position[, occurrence]]", "Extracts a substring from <value> that matches a regular expression specified by <regexp>. Optionally, search starts at <position> and looks for the specified <occurrence>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#regexp_substr"},
          {"REPLACE", "original_value, from_value, to_value", "Replaces all occurrences of <from_value> with <to_value> in <original_value>. If <from_value> is empty, no replacement is made.", ""},
          {"RIGHT", "value, length", "Returns the specified number of rightmost characters from the input STRING, or the specified number of rightmost bytes from the input BYTES.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#right"},
          {"ROUND", "numeric_expr [, decimal_places]", "If only <numeric_expr> is present, ROUND rounds <numeric_expr> to the nearest integer. If <decimal_places> is present, ROUND rounds <numeric_expr> to <decimal_places> decimal places after the decimal point. If <decimal_places> is negative, ROUND will round off digits to the left of the decimal point. Rounds halfway cases away from zero. Generates an error if overflow occurs.", ""},
          {"ROW_NUMBER", "", "Does not require the ORDER BY clause. Returns the sequential row ordinal (1-based) of each row for each ordered partition. If the ORDER BY clause is unspecified then the result is non-deterministic.", ""},
          {"RTRIM", "value1 [, value2]", "Identical to TRIM, but only removes trailing characters.", ""},
          {"SAFE_CAST", "expr AS typename", "SAFE_CAST is identical to CAST, except it returns NULL instead of raising an error.", ""},
          {"SAFE_CONVERT_BYTES_TO_STRING", "value", "Converts a sequence of bytes to a string. Any invalid UTF-8 characters are replaced with the Unicode replacement character, U+FFFD.", ""},
          {"SIGN", "numeric_expr", "Returns -1, 0, or +1 for negative, zero and positive arguments respectively. For floating point arguments, this function does not distinguish between positive and negative zero. Returns NaN for a NaN argument.", ""},
          {"SIN", "numeric_expr", "Computes the sine of <numeric_expr>. Never fails.", ""},
          {"SINH", "numeric_expr", "Computes the hyperbolic sine of <numeric_expr>. Generates an error if an overflow occurs.", ""},
          {"SOUNDEX", "input", "Returns a string that represents the Soundex code for the <input>. Soundex is a phonetic algorithm for indexing names by sound, as pronounced in English.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#soundex"},
          {"SPLIT", "value [, delimiter]", "Splits <value> using the <delimiter> argument.", ""},
          {"SQRT", "numeric_expr", "Computes the square root of <numeric_expr>. Generates an error if <numeric_expr> is less than 0. Returns +inf if <numeric_expr> is +inf.", ""},
          {"STARTS_WITH", "value1, value2", "Returns TRUE if <value2> is a prefix of <value1>.", ""},
          {"STRING", "timestamp_expr [, time_zone]", "Converts a <timestamp_expr> to a STRING data type. Supports an optional parameter to specify a timezone. ", ""},
          {"STRING_AGG", "expr, [, delimiter]", "Returns a value (either STRING or BYTES) obtained by concatenating non-null values.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#string_agg"},
          {"STRPOS", "value1, value2", "Returns the 1-based index of the first occurrence of <value2> inside <value1>. Returns 0 if <value2> is not found.", ""},
          {"ST_DISTANCE", "geography_1, geography_2[, use_spheroid]", "Returns the shortest distance in meters between two non-empty GEOGRAPHYs.  If either of the input GEOGRAPHYs is empty, ST_DISTANCE returns NULL. The optional use_spheroid parameter determines how this function measures distance. If use_spheroid is FALSE, the function measures distance on the surface of a perfect sphere.  The use_spheroid parameter currently only supportsthe value FALSE. The default value of use_spheroid is FALSE.", ""},
          {"SUBSTR", "value, position [, length]", "Returns a substring of the supplied value. The <position> argument is an integer specifying the starting position of the substring, with position = 1 indicating the first character or byte. The <length> argument is the maximum number of characters for STRING arguments, or bytes for BYTES arguments.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#substr"},
          {"SUBSTRING", "value, position [, length]", "An alias of substr. Returns a substring of the supplied <value> (STRING or BYTES). The <position> argument is an integer specifying the starting position of the substring, with position = 1 indicating the first character or byte. The <length> argument is the maximum number of characters for STRING arguments, or bytes for BYTES arguments.", ""},
          {"SUM", "expr", "Returns the sum of non-null values.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#sum"},
          {"TAN", "numeric_expr", "Computes tangent of <numeric_expr>. Generates an error if an overflow occurs.", ""},
          {"TANH", "numeric_expr", "Computes hyperbolic tangent of <numeric_expr>. Does not fail.", ""},
          {"TIMESTAMP", "timestamp_expr [, time_zone]", "Converts a STRING expression to a TIMESTAMP data type.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp"},
          {"TIMESTAMP_ADD", "timestamp_expr, INTERVAL int64_expr date_part", "Adds <int64_expr> units of <date_part> to the timestamp, independent of any time zone.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_add"},
          {"TIMESTAMP_DIFF", "timestamp_expr, timestamp_expr, date_part", "Returns the number of whole specified <date_part> intervals between two timestamps. The first <timestamp_expr> represents the later date; if the first <timestamp_expr> is earlier than the second <timestamp_expr>, the output is negative. Throws an error if the computation overflows the result type, such as if the difference in microseconds between the two timestamps would overflow an INT64 value.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_diff"},
          {"TIMESTAMP_MICROS", "INT64_expr", "Interprets <INT64_expr> as the number of microseconds since 1970-01-01 00:00:00 UTC.", ""},
          {"TIMESTAMP_MILLIS", "INT64_expr", "Interprets <INT64_expr> as the number of milliseconds since 1970-01-01 00:00:00 UTC.", ""},
          {"TIMESTAMP_SECONDS", "INT64_expr", "Interprets <INT64_expr> as the number of seconds since 1970-01-01 00:00:00 UTC.", ""},
          {"TIMESTAMP_SUB", "timestamp_expr, INTERVAL int64_expr date_part", "Subtracts <int64_expr> units of <date_part> from the timestamp, independent of any time zone.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_sub"},
          {"TIMESTAMP_TRUNC", "timestamp_expr, date_part [, time_zone]", "Truncates a timestamp to the granularity of <date_part>.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_trunc"},
          {"TRANSLATE", "expression, source_characters, target_characters", "In the input <expression>, replace the characters in <source_characters> to the corresponding characters in <target_characters>. Note that each character will be translated at most once. Characters in <expression> but not in <source_characters> will be added to the result with no change.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#translate"},
          {"TRIM", "value1 [, value2]", "Removes all leading and trailing characters that match <value2>. If <value2> is not specified, all leading and trailing whitespace characters (as defined by the Unicode standard) are removed. If the first argument is of type BYTES, the second argument is required.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#trim"},
          {"TRUNC", "numeric_expr [, decimal_places]", "If only <numeric_expr> is present, TRUNC rounds <numeric_expr> to the nearest integer whose absolute value is not greater than the absolute value of <numeric_expr>. If <decimal_places> is also present, TRUNC behaves like ROUND(<numeric_expr>, <decimal_places>), but always rounds towards zero and never overflows.", ""},
          {"UNICODE", "input", "Returns the Unicode code point for the first character of the <input> string. Function returns 0 if the string is empty, or the resulted unicode code point is 0.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/string_functions#unicode"},
          {"UNIX_DATE", "date_expr", "Returns the number of days since 1970-01-01.", ""},
          {"UNIX_MICROS", "timestamp_expr", "Returns the number of microseconds since 1970-01-01 00:00:00 UTC. Truncates higher levels of precision.", ""},
          {"UNIX_MILLIS", "timestamp_expr", "Returns the number of milliseconds since 1970-01-01 00:00:00 UTC. Truncates higher levels of precision.", ""},
          {"UNIX_SECONDS", "timestamp_expr", "Returns the number of seconds since 1970-01-01 00:00:00 UTC. Truncates higher levels of precision.", ""},
          {"UNNEST", "array_expr", "The UNNEST operator takes an ARRAY and returns a table, with one row for each element in the ARRAY. ", ""},
          {"UPPER", "value", "For STRING arguments, returns the original string with all alphabetic characters in uppercase. Mapping between uppercase and lowercase is done according to the Unicode Character Database without taking into account language-specific mappings.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#upper"},
          {"AGG", "expression", "", ""},
          {"APPROX_TOP_SUM", "expression, weight, number", "", ""},
          {"ARRAY", "subquery", "", ""},
          {"ARRAY_REVERSE", "value", "", ""},
          {"BIT_COUNT", "expression", "", ""},
          {"BOOL", "json_expr", "Takes a JSON expression, extracts a JSON boolean, and returns that value as a SQL BOOL. If the expression is SQL NULL, the function returns SQL NULL. If the extracted JSON value is not a boolean, an error is produced.", ""},
          {"CLASSIFIER", "", "Returns the matched symbol of a row in a match inside MATCH_RECOGNIZE", ""},
          {"COALESCE", "expr[, ...]", "", ""},
          {"CODE_POINTS_TO_BYTES", "ascii_values", "", ""},
          {"CODE_POINTS_TO_STRING", "value", "", ""},
          {"CONTAINS_SUBSTR", "expression, search_value_literal", "", ""},
          {"CORR", "X1, X2", "", ""},
          {"COVAR_POP", "X1, X2", "", ""},
          {"COVAR_SAMP", "X1, X2", "", ""},
          {"CURRENT_DATETIME", "[timezone]", "", ""},
          {"CURRENT_TIME", "[timezone]", "", ""},
          {"DATETIME", "year, month, day, hour, minute, second", "", ""},
          {"DATETIME_ADD", "datetime_expression, INTERVAL int64_expression part", "", ""},
          {"DATETIME_BUCKET", "datetime_expression, bucket_width [, origin]", "Gets the lower bound of the datetime bucket that contains a datetime.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#datetime_bucket"},
          {"DATETIME_DIFF", "datetime_expression_a, datetime_expression_b, part", "", ""},
          {"DATETIME_SUB", "datetime_expression, INTERVAL int64_expression part", "", ""},
          {"DATETIME_TRUNC", "datetime_expression, part", "", ""},
          {"DATE_BUCKET", "date_expression, bucket_width [, origin]", "Gets the lower bound of the date bucket that contains a date.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#date_bucket"},
          {"ERROR", "error_message", "", ""},
          {"FARM_FINGERPRINT", "value", "", ""},
          {"FIRST", "expression", "Returns the first row in a match inside MATCH_RECOGNIZE", ""},
          {"FORMAT_DATETIME", "format_string, datetime_expression", "", ""},
          {"FORMAT_TIME", "format_string, time_object", "", ""},
          {"FROM_BASE32", "string_expr", "", ""},
          {"FROM_BASE64", "string_expr", "", ""},
          {"FROM_HEX", "string", "", ""},
          {"GENERATE_RANGE_ARRAY", "range_expression, INTERVAL step_expression [, bool_expression]", "Splits a range into an array of subranges.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#generate_range_array"},
          {"GENERATE_TIMESTAMP_ARRAY", "start_timestamp, end_timestamp, INTERVAL step_expression date_part", "", ""},
          {"GENERATE_UUID", "", "", ""},
          {"HLL_COUNT.EXTRACT", "sketch", "", ""},
          {"HLL_COUNT.INIT", "input [, precision]", "", ""},
          {"HLL_COUNT.MERGE", "sketch", "", ""},
          {"HLL_COUNT.MERGE_PARTIAL", "sketch", "", ""},
          {"IF", "expr, true_result, else_result", "", ""},
          {"INT64", "json_expr", "Takes a JSON expression, extracts a JSON number and returns that value as a SQL INT64. If the expression is SQL NULL, the function returns SQL NULL. If the extracted JSON number has a fractional part or is outside of the INT64 domain, an error is produced.", ""},
          {"JSON_KEYS", "json_expr [, max_depth] [, mode=> 'strict' | 'lax' | 'lax recursive']", "Extracts an array of JSON keys from a JSON value. max_depth specifies the maximum depth of nested fields to search for keys. mode specifies how keys are extracted from arrays.", ""},
          {"JSON_TYPE", "json_expr", "Takes a JSON expression and returns the type of the outermost JSON value as a SQL STRING. If the expression is SQL NULL, the function returns SQL NULL. If the extracted JSON value is not a valid JSON type, an error is produced.", ""},
          {"JUSTIFY_DAYS", "interval_expression", "", ""},
          {"JUSTIFY_HOURS", "interval_expression", "", ""},
          {"JUSTIFY_INTERVAL", "interval_expression", "", ""},
          {"LAST", "expression", "Returns the last row in a match inside MATCH_RECOGNIZE", ""},
          {"LPAD", "original_value, return_length[, pattern]", "", ""},
          {"MAKE_INTERVAL", "year, month, day, hour, minute, second", "", ""},
          {"MATCH_NUMBER", "", "Returns the 1-based index of a match inside MATCH_RECOGNIZE", ""},
          {"MATCH_ROW_NUMBER", "", "Returns the 1-based index of a row in a match inside MATCH_RECOGNIZE", ""},
          {"MD5", "input", "", ""},
          {"NET.HOST", "url", "", ""},
          {"NET.IPV4_FROM_INT64", "integer_value", "", ""},
          {"NET.IPV4_TO_INT64", "addr_bin", "", ""},
          {"NET.IP_FROM_STRING", "addr_str", "", ""},
          {"NET.IP_NET_MASK", "num_output_bytes, prefix_length", "", ""},
          {"NET.IP_TO_STRING", "addr_bin", "", ""},
          {"NET.IP_TRUNC", "addr_bin, prefix_length", "", ""},
          {"NET.PUBLIC_SUFFIX", "url", "", ""},
          {"NET.REG_DOMAIN", "url", "", ""},
          {"NET.SAFE_IP_FROM_STRING", "addr_str", "", ""},
          {"NORMALIZE", "value[, normalization_mode]", "", ""},
          {"NORMALIZE_AND_CASEFOLD", "value[, normalization_mode]", "", ""},
          {"NULLIF", "expr, expr_to_match", "", ""},
          {"PARSE_BIGNUMERIC", "string_expression", "", ""},
          {"PARSE_DATE", "format_string, date_string", "", ""},
          {"PARSE_DATETIME", "format_string, datetime_string", "", ""},
          {"PARSE_NUMERIC", "string_expression", "", ""},
          {"PARSE_TIME", "format_string, time_string", "", ""},
          {"RAND", "", "", ""},
          {"RANGE_BUCKET", "point, boundaries_array", "", ""},
          {"RANGE_END", "range_expression", "Gets the upper bound of a range.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#range_end"},
          {"RANGE_INTERSECT", "range_expression, range_expression", "Gets a segment of two ranges that intersect.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#range_intersect"},
          {"RANGE_OVERLAPS", "range_expression, range_expression", "Checks if two ranges overlap.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#range_overlaps"},
          {"RANGE_START", "range_expression", "Gets the lower bound of a range.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#range_start"},
          {"REPEAT", "original_value, repetitions", "", ""},
          {"REVERSE", "value", "", ""},
          {"RPAD", "original_value, return_length[, pattern]", "", ""},
          {"SAFE_ADD", "X, Y", "", ""},
          {"SAFE_DIVIDE", "X, Y", "", ""},
          {"SAFE_MULTIPLY", "X, Y", "", ""},
          {"SAFE_NEGATE", "X", "", ""},
          {"SAFE_OFFSET", "zero_based_offset", "", ""},
          {"SAFE_ORDINAL", "one_based_offset", "", ""},
          {"SAFE_SUBTRACT", "X, Y", "", ""},
          {"SESSION_USER", "", "", ""},
          {"SHA1", "input", "", ""},
          {"SHA256", "input", "", ""},
          {"SHA512", "input", "", ""},
          {"STDDEV", "[DISTINCT]  expression", "", ""},
          {"STDDEV_POP", "[DISTINCT]  expression", "", ""},
          {"STDDEV_SAMP", "[DISTINCT]  expression", "", ""},
          {"ST_AREA", "geography_expression[, use_spheroid]", "", ""},
          {"ST_ASBINARY", "geography_expression", "", ""},
          {"ST_ASGEOJSON", "geography_expression", "", ""},
          {"ST_ASTEXT", "geography_expression", "", ""},
          {"ST_BOUNDARY", "geography_expression", "", ""},
          {"ST_CENTROID", "geography_expression", "", ""},
          {"ST_CENTROID_AGG", "geography", "", ""},
          {"ST_CLOSESTPOINT", "geography_1, geography_2[, use_spheroid]", "", ""},
          {"ST_CLUSTERDBSCAN", "geography_column, epsilon, minimum_geographies) OVER(...", "", ""},
          {"ST_CONTAINS", "geography_1, geography_2", "", ""},
          {"ST_CONVEXHULL", "geography_expression", "", ""},
          {"ST_COVEREDBY", "geography_1, geography_2", "", ""},
          {"ST_COVERS", "geography_1, geography_2", "", ""},
          {"ST_DIFFERENCE", "geography_1, geography_2", "", ""},
          {"ST_DIMENSION", "geography_expression", "", ""},
          {"ST_DISJOINT", "geography_1, geography_2", "", ""},
          {"ST_DUMP", "geography[, dimension]", "", ""},
          {"ST_DWITHIN", "geography_1, geography_2, distance[, use_spheroid]", "", ""},
          {"ST_ENDPOINT", "linestring_geography", "", ""},
          {"ST_EQUALS", "geography_1, geography_2", "", ""},
          {"ST_EXTERIORRING", "polygon_geography", "", ""},
          {"ST_GEOGFROM", "expression", "", ""},
          {"ST_GEOGFROMGEOJSON", "geojson_string[, make_valid => constant_expression]", "", ""},
          {"ST_GEOGFROMTEXT", "wkt_string[, oriented]", "", ""},
          {"ST_GEOGFROMWKB", "wkb_bytes_expression", "", ""},
          {"ST_GEOGPOINT", "longitude, latitude", "", ""},
          {"ST_GEOGPOINTFROMGEOHASH", "geohash", "", ""},
          {"ST_GEOHASH", "geography_expression, maxchars", "", ""},
          {"ST_INTERSECTION", "geography_1, geography_2", "", ""},
          {"ST_INTERSECTS", "geography_1, geography_2", "", ""},
          {"ST_INTERSECTSBOX", "geography, lng1, lat1, lng2, lat2", "", ""},
          {"ST_ISCOLLECTION", "geography_expression", "", ""},
          {"ST_ISEMPTY", "geography_expression", "", ""},
          {"ST_LENGTH", "geography_expression[, use_spheroid]", "", ""},
          {"ST_MAKELINE", "geography_1, geography_2", "", ""},
          {"ST_MAKEPOLYGON", "geography_expression[, array_of_geography]", "", ""},
          {"ST_MAKEPOLYGONORIENTED", "array_of_geography", "", ""},
          {"ST_MAXDISTANCE", "geography_1, geography_2[, use_spheroid]", "", ""},
          {"ST_NUMGEOMETRIES", "geography_expression", "", ""},
          {"ST_NUMPOINTS", "geography_expression", "", ""},
          {"ST_PERIMETER", "geography_expression[, use_spheroid]", "", ""},
          {"ST_POINTN", "linestring_geography, index", "", ""},
          {"ST_REGIONSTATS", "geography, raster_id[, band => string_1][, include => string_2][, options => json_constant]", "", ""},
          {"ST_SIMPLIFY", "geography, tolerance_meters", "", ""},
          {"ST_SNAPTOGRID", "geography_expression, grid_size", "", ""},
          {"ST_STARTPOINT", "linestring_geography", "", ""},
          {"ST_TOUCHES", "geography_1, geography_2", "", ""},
          {"ST_UNION", "geography_1, geography_2", "", ""},
          {"ST_UNION_AGG", "geography", "", ""},
          {"ST_WITHIN", "geography_1, geography_2", "", ""},
          {"ST_X", "geography_expression", "", ""},
          {"ST_Y", "geography_expression", "", ""},
          {"TIMESTAMP_BUCKET", "timestamp_expression, bucket_width [, origin]", "Gets the lower bound of the timestamp bucket that contains a timestamp.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#timestamp_bucket"},
          {"TIME", "hour, minute, second", "", ""},
          {"TIME_ADD", "time_expression, INTERVAL int64_expression part", "", ""},
          {"TIME_DIFF", "time_expression_a, time_expression_b, part", "", ""},
          {"TIME_SUB", "time_expression, INTERVAL int64_expression part", "", ""},
          {"TIME_TRUNC", "time_expression, part", "", ""},
          {"TO_BASE32", "bytes_expr", "", ""},
          {"TO_BASE64", "bytes_expr", "", ""},
          {"TO_CODE_POINTS", "value", "", ""},
          {"TO_HEX", "bytes", "", ""},
          {"TO_JSON_STRING", "value[, pretty_print]", "Takes a SQL value and returns a JSON-formatted string representation of the value. The value must be a supported BigQuery data type.", ""},
          {"VARIANCE", "[DISTINCT]  expression", "", ""},
          {"VAR_POP", "[DISTINCT]  expression", "", ""},
          {"VAR_SAMP", "[DISTINCT]  expression", "", ""},
      };
  return *kEntries;
}

const std::vector<FunctionInfoEntry>& BuildTvfFunctionInfo() {
  static const std::vector<FunctionInfoEntry>* kEntries =
      new std::vector<FunctionInfoEntry>{
          {"ML.EVALUATE", "MODEL model, TABLE table | (subquery) [, STRUCT(numeric_expr AS threshold)]", "", ""},
          {"ML.FEATURE_INFO", "MODEL model", "", ""},
          {"ML.PREDICT", "MODEL model, TABLE table | (subquery)", "", ""},
          {"ML.ROC_CURVE", "MODEL model, TABLE table | (subquery) [, thresholds_array]", "", ""},
          {"ML.TRAINING_INFO", "MODEL model", "", ""},
          {"ML.WEIGHTS", "MODEL model", "", ""},
          {"GAP_FILL", "TABLE table | (subquery), time_series_column, bucket_width [, partitioning_columns, value_columns, origin, ignore_null_values]", "Finds and fills gaps in a time series.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/functions-and-operators#gap_fill"},
          {"RANGE_SESSIONIZE", "TABLE table | (subquery), STRING range_column, ARRAY<STRING> partitioning_columns [, sessionize_mode]", "Produces a table of sessionized ranges.", "https://cloud.google.com/bigquery/docs/reference/standard-sql/range-functions#range_sessionize"},
      };
  return *kEntries;
}

const std::vector<std::string>& BuildTypeNames() {
  static const std::vector<std::string>* kEntries =
      new std::vector<std::string>{
          "INT64",
          "FLOAT64",
          "NUMERIC",
          "DECIMAL",
          "BIGNUMERIC",
          "BIGDECIMAL",
          "BOOL",
          "STRING",
          "BYTES",
          "DATE",
          "DATETIME",
          "TIME",
          "TIMESTAMP",
          "INTERVAL",
          "GEOGRAPHY",
          "JSON",
          "ARRAY",
          "STRUCT",
          "RANGE",
      };
  return *kEntries;
}

}  // namespace

const std::vector<ClauseWordEntry>& ClauseWords() {
  return BuildClauseWords();
}

const std::vector<std::string>& ExpressionKeywords() {
  return BuildExpressionKeywords();
}

const std::vector<FunctionInfoEntry>& FunctionInfo() {
  return BuildFunctionInfo();
}

const std::vector<FunctionInfoEntry>& TvfFunctionInfo() {
  return BuildTvfFunctionInfo();
}

const std::vector<std::string>& TypeNames() {
  return BuildTypeNames();
}

}  // namespace sqltools
}  // namespace backend
}  // namespace bigquery_emulator
