#include "backend/sqltools/sql_completion_data_internal.h"

namespace bigquery_emulator {
namespace backend {
namespace sqltools {
namespace completion_data_internal {
const std::vector<ClauseWordEntry>& ClauseWordEntries() {
  static const std::vector<ClauseWordEntry>* kEntries =
      new std::vector<ClauseWordEntry>{
          {"SELECT", "select"},
          {"FROM", "from"},
          {"INNER JOIN", "join"},
          {"CROSS JOIN", "join"},
          {"FULL OUTER JOIN", "join"},
          {"FULL JOIN", "join"},
          {"LEFT OUTER JOIN", "join"},
          {"LEFT JOIN", "join"},
          {"RIGHT OUTER JOIN", "join"},
          {"RIGHT JOIN", "join"},
          {"JOIN", "join"},
          {"ON", "on"},
          {"USING", "using"},
          {"WHERE", "where"},
          {"GROUP BY", "group"},
          {"GROUPING SETS", "group"},
          {"HAVING", "having"},
          {"ORDER BY", "order"},
          {"NULLS FIRST", "order"},
          {"NULLS LAST", "order"},
          {"UNION ALL", "union"},
          {"UNION DISTINCT", "union"},
          {"INTERSECT DISTINCT", "intersect"},
          {"EXCEPT DISTINCT", "intersect"},
          {"LIMIT", "limit"},
          {"OFFSET", "offset"},
          {"WITH", "with"},
          {"WITH DATA", "with"},
          {"WITH PARTITION COLUMNS", "partition"},
          {"PARTITION BY", "partition"},
          {"WINDOW", "window"},
          {"CREATE TEMPORARY FUNCTION", "udf"},
          {"CREATE TEMP FUNCTION", "udf"},
          {"CREATE FUNCTION IF NOT EXISTS", "udf"},
          {"CREATE OR REPLACE FUNCTION", "udf"},
          {"CREATE FUNCTION", "udf"},
          {"CREATE TEMPORARY AGGREGATE FUNCTION", "udaf"},
          {"CREATE TEMP AGGREGATE FUNCTION", "udaf"},
          {"CREATE AGGREGATE FUNCTION IF NOT EXISTS", "udaf"},
          {"CREATE OR REPLACE AGGREGATE FUNCTION", "udaf"},
          {"CREATE AGGREGATE FUNCTION", "udf"},
          {"CREATE PROCEDURE", "procedure"},
          {"CREATE OR REPLACE PROCEDURE", "procedure"},
          {"CREATE PROCEDURE IF NOT EXISTS", "procedure"},
          {"DELETE", "delete"},
          {"INSERT INTO", "insert"},
          {"INSERT", "insert"},
          {"UPDATE", "update"},
          {"MERGE INTO", "merge"},
          {"MERGE", "merge"},
          {"WHEN MATCHED", "match"},
          {"WHEN NOT MATCHED BY TARGET", "match"},
          {"WHEN NOT MATCHED BY SOURCE", "match"},
          {"WHEN NOT MATCHED", "match"},
          {"SET", "set"},
          {"VALUES", "values"},
          {"CREATE TABLE IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE TABLE", "create"},
          {"CREATE TABLE", "create"},
          {"CREATE EXTERNAL TABLE IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE EXTERNAL TABLE", "create"},
          {"CREATE EXTERNAL TABLE", "create"},
          {"CREATE MATERIALIZED VIEW IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE MATERIALIZED VIEW", "create"},
          {"CREATE MATERIALIZED VIEW", "create"},
          {"CREATE VIEW IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE VIEW", "create"},
          {"CREATE VIEW", "create"},
          {"CREATE MODEL IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE MODEL", "create"},
          {"CREATE MODEL", "create"},
          {"CREATE ROW ACCESS POLICY IF NOT EXISTS", "create"},
          {"CREATE OR REPLACE ROW ACCESS POLICY", "create"},
          {"CREATE ROW ACCESS POLICY", "create"},
          {"CREATE RESERVATION", "create"},
          {"CREATE RESERVATION IF NOT EXISTS", "create"},
          {"CREATE CAPACITY", "create"},
          {"CREATE ASSIGNMENT", "create"},
          {"CREATE SCHEMA", "create"},
          {"CREATE SCHEMA IF NOT EXISTS", "create"},
          {"CREATE SNAPSHOT TABLE IF NOT EXISTS", "create"},
          {"CREATE SNAPSHOT TABLE", "create"},
          {"CREATE SEARCH INDEX", "create"},
          {"CREATE SEARCH INDEX IF NOT EXISTS", "create"},
          {"CREATE VECTOR INDEX", "create"},
          {"CREATE VECTOR INDEX IF NOT EXISTS", "create"},
          {"DROP TABLE IF EXISTS", "drop"},
          {"DROP TABLE", "drop"},
          {"DROP EXTERNAL TABLE IF EXISTS", "drop"},
          {"DROP EXTERNAL TABLE", "drop"},
          {"DROP MATERIALIZED VIEW IF EXISTS", "drop"},
          {"DROP MATERIALIZED VIEW", "drop"},
          {"DROP VIEW IF EXISTS", "drop"},
          {"DROP VIEW", "drop"},
          {"DROP FUNCTION IF EXISTS", "drop"},
          {"DROP FUNCTION", "drop"},
          {"DROP PROCEDURE", "drop"},
          {"DROP PROCEDURE IF EXISTS", "drop"},
          {"DROP ROW ACCESS POLICY", "drop"},
          {"DROP ROW ACCESS POLICY IF EXISTS", "drop"},
          {"DROP ALL ROW ACCESS POLICIES", "drop"},
          {"TRUNCATE TABLE", "drop"},
          {"DROP RESERVATION IF EXISTS", "drop"},
          {"DROP RESERVATION", "drop"},
          {"DROP CAPACITY IF EXISTS", "drop"},
          {"DROP CAPACITY", "drop"},
          {"DROP ASSIGNMENT IF EXISTS", "drop"},
          {"DROP ASSIGNMENT", "drop"},
          {"DROP SCHEMA IF EXISTS", "drop"},
          {"DROP SCHEMA", "drop"},
          {"DROP SNAPSHOT TABLE IF EXISTS", "drop"},
          {"DROP SNAPSHOT TABLE", "drop"},
          {"DROP SEARCH INDEX", "drop"},
          {"DROP SEARCH INDEX IF EXISTS", "drop"},
          {"DROP VECTOR INDEX", "drop"},
          {"DROP VECTOR INDEX IF EXISTS", "drop"},
          {"DROP", "drop"},
          {"CLUSTER BY", "cluster"},
          {"ALTER TABLE IF EXISTS", "alter"},
          {"ALTER TABLE", "alter"},
          {"ALTER MATERIALIZED VIEW IF EXISTS", "alter"},
          {"ALTER MATERIALIZED VIEW", "alter"},
          {"ALTER VIEW IF EXISTS", "alter"},
          {"ALTER VIEW", "alter"},
          {"ALTER SCHEMA IF EXISTS", "alter"},
          {"ALTER SCHEMA", "alter"},
          {"ALTER BI_CAPACITY", "alter"},
          {"ALTER CAPACITY", "alter"},
          {"ALTER ORGANIZATION", "alter"},
          {"ALTER PROJECT", "alter"},
          {"ALTER RESERVATION", "alter"},
          {"DECLARE", "declare"},
          {"SET", "set"},
          {"IF", "if"},
          {"EXECUTE IMMEDIATE", "execute immediate"},
          {"LOOP", "loop"},
          {"WHILE", "loop"},
          {"BEGIN", "begin"},
          {"BEGIN TRANSACTION", "begin"},
          {"COMMIT", "end"},
          {"COMMIT TRANSACTION", "end"},
          {"ROLLBACK", "end"},
          {"ROLLBACK TRANSACTION", "end"},
          {"END", "end"},
          {"END IF", "end"},
          {"END WHILE", "end"},
          {"END LOOP", "end"},
          {"CONTINUE", "continue"},
          {"ITERATE", "continue"},
          {"BREAK", "break"},
          {"LEAVE", "break"},
          {"CALL", "call"},
          {"ASSERT", "assert"},
          {"EXPORT DATA", "export"},
          {"EXPORT DATA WITH CONNECTION", "export"},
          {"EXPORT TABLE METADATA", "export"},
          {"LOAD DATA INTO", "load"},
          {"LOAD DATA OVERWRITE", "load"},
          {"PARTITIONS", "load"},
          {"OVERWRITE PARTITIONS", "load"},
          {"FROM FILES", "load"},
          {"ADD CONSTRAINT", "alter"},
          {"ADD FOREIGN KEY", "alter"},
          {"ADD PRIMARY KEY", "alter"},
          {"DROP CONSTRAINT", "alter"},
          {"DROP PRIMARY KEY", "alter"},
          {"AS REPLICA OF", "create"},
          {"CONSTRAINT", "create"},
          {"ENFORCED", "create"},
          {"FOREIGN KEY", "create"},
          {"NOT ENFORCED", "create"},
          {"PRIMARY KEY", "create"},
          {"REFERENCES", "create"},
          {"UNDROP SCHEMA", "undrop"},
          {"UNDROP SCHEMA IF NOT EXISTS", "undrop"},
          {"QUALIFY", "qualify"},
          {"EXTEND", "pipe"},
          {"AGGREGATE", "pipe"},
          {"TABLESAMPLE", "pipe"},
          {"PIVOT", "pipe"},
          {"UNPIVOT", "pipe"},
          {"RENAME", "pipe"},
          {"MATCH_RECOGNIZE", "match_recognize"},
          {"MEASURES", "match_recognize"},
          {"PATTERN", "match_recognize"},
          {"DEFINE", "match_recognize"},
          {"AFTER MATCH SKIP TO NEXT ROW", "match_recognize"},
          {"AFTER MATCH SKIP PAST LAST ROW", "match_recognize"},
      };
  return *kEntries;
}

}  // namespace completion_data_internal
}  // namespace sqltools
}  // namespace backend
}  // namespace bigquery_emulator
