package main

import (
	"fmt"
	"io"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type fileSummary struct {
	File            string
	Findings        []tidyFinding
	WorstComplexity int
	Checks          map[string]int
}

func failedFileForFinding(f tidyFinding, failedFiles map[string]struct{}) string {
	if _, ok := failedFiles[f.File]; ok {
		return f.File
	}
	if _, ok := failedFiles[f.BlockFile]; ok {
		return f.BlockFile
	}
	return ""
}

func summarizeByFile(findings []tidyFinding, failedFiles map[string]struct{}) []fileSummary {
	byFile := make(map[string]*fileSummary)
	for path := range failedFiles {
		byFile[path] = &fileSummary{File: path, Checks: make(map[string]int)}
	}
	for _, f := range findings {
		key := failedFileForFinding(f, failedFiles)
		if key == "" {
			continue
		}
		s := byFile[key]
		s.Findings = append(s.Findings, f)
		s.Checks[f.Check]++
		if f.ComplexityScore > s.WorstComplexity {
			s.WorstComplexity = f.ComplexityScore
		}
	}
	out := make([]fileSummary, 0, len(byFile))
	for _, s := range byFile {
		out = append(out, *s)
	}
	sort.Slice(out, func(i, j int) bool { return out[i].File < out[j].File })
	return out
}

func subsystemFor(path string) string {
	switch {
	case strings.HasPrefix(path, "backend/catalog/"):
		return "catalog"
	case strings.HasPrefix(path, "backend/engine/control/"):
		return "control"
	case strings.HasPrefix(path, "backend/engine/coordinator/"):
		return "coordinator"
	case strings.HasPrefix(path, "backend/engine/duckdb/"):
		return "duckdb"
	case strings.HasPrefix(path, "backend/engine/semantic/"):
		return "semantic"
	case strings.HasPrefix(path, "backend/storage/"):
		return "storage"
	case strings.HasPrefix(path, "backend/schema/"):
		return "schema"
	case strings.HasPrefix(path, "backend/sqltools/"):
		return "sqltools"
	case strings.HasPrefix(path, "frontend/handlers/"):
		return "frontend"
	case strings.HasPrefix(path, "binaries/"):
		return "binaries"
	case strings.HasPrefix(path, "tools/googlesql-prebuilt/smoke/"):
		return "smoke"
	default:
		return "other"
	}
}

func fileKind(path string) string {
	base := filepath.Base(path)
	switch {
	case strings.HasSuffix(base, "_test.cc"):
		return fileKindTest
	case strings.HasSuffix(base, "_test_fixture.h"), strings.HasSuffix(base, "_internal.h"):
		return fileKindFixture
	case strings.HasSuffix(base, ".h"), strings.HasSuffix(base, ".hpp"):
		return "header"
	default:
		return "production"
	}
}

func dispositionFor(s fileSummary) (disp string, wave int) {
	hasNonComplexity := false
	for check := range s.Checks {
		if check != "readability-function-cognitive-complexity" &&
			check != "readability-function-size" {
			hasNonComplexity = true
			break
		}
	}
	if hasNonComplexity {
		for check := range s.Checks {
			if strings.HasPrefix(check, "modernize-") {
				return "autofix", 0
			}
		}
		return dispFix, 3
	}

	kind := fileKind(s.File)
	score := s.WorstComplexity
	switch {
	case score > 50:
		return dispFix, 1
	case score >= 35:
		return dispFix, 2
	case score >= 26:
		if kind == fileKindTest || kind == fileKindFixture {
			return "NOLINT", 4
		}
		return dispFix, 4
	case kind == fileKindTest || kind == fileKindFixture:
		return "NOLINT", 4
	default:
		return dispFix, 4
	}
}

func writeTriageMarkdown(path string, findings []tidyFinding, failedFiles map[string]struct{}, totalBlocks int) error {
	//nolint:gosec // Output path comes from task wrapper defaults or explicit flags.
	if err := os.MkdirAll(filepath.Dir(path), 0o755); err != nil {
		return fmt.Errorf("mkdir triage doc: %w", err)
	}
	content := buildTriageMarkdown(findings, failedFiles, totalBlocks)
	//nolint:gosec // Generated triage doc is intentionally world-readable.
	return os.WriteFile(path, []byte(content), 0o644)
}

func buildTriageMarkdown(findings []tidyFinding, failedFiles map[string]struct{}, totalBlocks int) string {
	summaries := summarizeByFile(findings, failedFiles)

	checkCounts := make(map[string]int)
	complexityCount := 0
	for _, f := range findings {
		checkCounts[f.Check]++
		if f.ComplexityScore > 0 {
			complexityCount++
		}
	}

	var b strings.Builder
	writeTriageSummary(&b, summaries, findings, checkCounts, complexityCount, totalBlocks)
	writeTriageMatrix(&b, summaries)
	writeTriageWaves(&b)
	return b.String()
}

func writeTriageSummary(
	b *strings.Builder,
	summaries []fileSummary,
	findings []tidyFinding,
	checkCounts map[string]int,
	complexityCount, totalBlocks int,
) {
	b.WriteString("# clang-tidy triage (first-party C++)\n\n")
	b.WriteString("Generated by `task lint:cpp:tidy-report` from `lint-cpp-tidy.log`.\n\n")
	b.WriteString("## Summary\n\n")
	_, _ = fmt.Fprintf(b, "| Metric | Value |\n|---|---|\n")
	_, _ = fmt.Fprintf(b, "| Files scanned | %d |\n", totalBlocks)
	_, _ = fmt.Fprintf(b, "| Files failed | %d |\n", len(summaries))
	_, _ = fmt.Fprintf(b, "| Total findings | %d |\n", len(findings))
	_, _ = fmt.Fprintf(b, "| Cognitive-complexity findings | %d |\n\n", complexityCount)

	b.WriteString("**Check mix:** Failures are **not** complexity-only. ")
	b.WriteString(
		"Cognitive-complexity is the largest bucket, but analyzer and cppcoreguidelines checks also fail the lane.\n\n",
	)

	b.WriteString("### Findings by check\n\n")
	b.WriteString("| Check | Count |\n|---|---|\n")
	for _, check := range sortedKeys(checkCounts) {
		_, _ = fmt.Fprintf(b, "| `%s` | %d |\n", check, checkCounts[check])
	}
	b.WriteString("\n### Failed files by subsystem\n\n")
	b.WriteString("| Subsystem | Files |\n|---|---|\n")
	subFailed := make(map[string]int)
	for _, s := range summaries {
		subFailed[subsystemFor(s.File)]++
	}
	for _, sub := range sortedKeys(subFailed) {
		_, _ = fmt.Fprintf(b, "| %s | %d |\n", sub, subFailed[sub])
	}
}

func writeTriageMatrix(b *strings.Builder, summaries []fileSummary) {
	b.WriteString("\n## Disposition matrix\n\n")
	b.WriteString("| File | Findings | Checks | Worst complexity | Subsystem | Kind | Disposition | Wave | Notes |\n")
	b.WriteString("|---|---:|---|---:|---|---|---|---:|---|\n")
	for _, s := range summaries {
		checks := sortedCheckList(s.Checks)
		symbols := uniqueSymbols(s.Findings)
		disp, wave := dispositionFor(s)
		notes := strings.Join(symbols, ", ")
		if len(notes) > 80 {
			notes = notes[:77] + "..."
		}
		_, _ = fmt.Fprintf(b, "| `%s` | %d | %s | %d | %s | %s | %s | %d | %s |\n",
			s.File, len(s.Findings), checks, s.WorstComplexity,
			subsystemFor(s.File), fileKind(s.File), disp, wave, notes)
	}
}

func writeTriageWaves(b *strings.Builder) {
	b.WriteString("\n## Remediation waves\n\n")
	b.WriteString("1. **Wave 0** — Tooling + `clang-tidy --fix` on rows dispositioned `autofix`.\n")
	b.WriteString("2. **Wave 1** — P0 complexity (>50): dedicated PRs with tests.\n")
	b.WriteString("3. **Wave 2** — P1 complexity (35–50): one PR per subsystem.\n")
	b.WriteString("4. **Wave 3** — Non-complexity correctness (`bugprone-*`, `clang-analyzer-*`).\n")
	b.WriteString("5. **Wave 4** — P2 complexity (26–34), tests/fixtures, scoped NOLINT.\n")
}

func sortedKeys(m map[string]int) []string {
	keys := make([]string, 0, len(m))
	for k := range m {
		keys = append(keys, k)
	}
	sort.Slice(keys, func(i, j int) bool {
		if m[keys[i]] != m[keys[j]] {
			return m[keys[i]] > m[keys[j]]
		}
		return keys[i] < keys[j]
	})
	return keys
}

func sortedCheckList(m map[string]int) string {
	keys := sortedKeys(m)
	parts := make([]string, len(keys))
	for i, k := range keys {
		parts[i] = fmt.Sprintf("%s (%d)", k, m[k])
	}
	return strings.Join(parts, "; ")
}

func uniqueSymbols(findings []tidyFinding) []string {
	seen := make(map[string]struct{})
	var out []string
	for _, f := range findings {
		name := f.Symbol
		if name == "" {
			name = truncateMsg(f.Message, 40)
		}
		if _, ok := seen[name]; ok {
			continue
		}
		seen[name] = struct{}{}
		out = append(out, name)
	}
	return out
}

func truncateMsg(s string, n int) string {
	if len(s) <= n {
		return s
	}
	return s[:n-3] + "..."
}

func printTidySummary(
	w io.Writer,
	findings []tidyFinding,
	failedFiles map[string]struct{},
	totalBlocks int,
	csvPath, mdPath string,
) {
	checkCounts := make(map[string]int)
	complexityCount := 0
	for _, f := range findings {
		checkCounts[f.Check]++
		if f.ComplexityScore > 0 {
			complexityCount++
		}
	}
	_, _ = fmt.Fprintf(w, "lint:cpp:tidy-report: scanned %d file blocks, %d failed files, %d findings\n",
		totalBlocks, len(failedFiles), len(findings))
	_, _ = fmt.Fprintf(w, "  cognitive-complexity findings: %d\n", complexityCount)
	_, _ = fmt.Fprintf(w, "  checks:\n")
	for _, check := range sortedKeys(checkCounts) {
		_, _ = fmt.Fprintf(w, "    %s: %d\n", check, checkCounts[check])
	}
	_, _ = fmt.Fprintf(w, "  csv: %s\n", csvPath)
	_, _ = fmt.Fprintf(w, "  triage: %s\n", mdPath)
}
