#include "backend/engine/duckdb/transpiler/functions.h"

#include <string>

#include "absl/container/flat_hash_map.h"
#include "absl/strings/ascii.h"
#include "absl/strings/string_view.h"
#include "backend/engine/disposition.h"

namespace bigquery_emulator {
namespace backend {
namespace engine {
namespace duckdb {
namespace transpiler {

namespace {

using Table = absl::flat_hash_map<std::string, FnEntry>;

// The disposition table.
//
// `functions_table.inc` is generated by the Bazel `genrule`
// (`backend/engine/duckdb/transpiler:functions_table_inc`) from
// `functions.yaml`. It is a comma-separated list of
// `{"name", FnEntry{...}}` initializers we drop into the static map
// below. We pay the static-init cost once at process start; a
// `flat_hash_map` lookup is a hashed string compare and the table
// is < 200 entries, so the per-query cost is negligible compared to
// the analyzer pass that lands here.
const Table& GetTable() {
  static const auto* kTable = new Table{
#include "backend/engine/duckdb/transpiler/functions_table.inc"
  };
  return *kTable;
}

}  // namespace

const FnEntry* LookupFunction(absl::string_view bq_name) {
  std::string lower(bq_name);
  absl::AsciiStrToLower(&lower);
  const Table& t = GetTable();
  auto it = t.find(lower);
  return it == t.end() ? nullptr : &it->second;
}

}  // namespace transpiler
}  // namespace duckdb
}  // namespace engine
}  // namespace backend
}  // namespace bigquery_emulator
