#include "backend/engine/duckdb/transpiler/node_dispositions.h"

#include <string>
#include <vector>

#include "absl/container/flat_hash_map.h"
#include "absl/strings/string_view.h"
#include "backend/engine/disposition.h"

namespace bigquery_emulator {
namespace backend {
namespace engine {
namespace duckdb {
namespace transpiler {

namespace {

using Table = absl::flat_hash_map<std::string, NodeDispositionEntry>;

// The disposition table.
//
// `node_dispositions_table.inc` is generated by the Bazel `genrule`
// (`backend/engine/duckdb/transpiler:node_dispositions_table_inc`)
// from `node_dispositions.yaml`. It is a comma-separated list of
// `{"name", NodeDispositionEntry{...}}` initializers we drop into
// the static map below. We pay the static-init cost once at process
// start; a `flat_hash_map` lookup is a hashed string compare and
// the table is ~80 entries, so the per-call cost is negligible
// compared to the analyzer pass that lands here.
const Table& GetTable() {
  static const auto* kTable = new Table{
#include "backend/engine/duckdb/transpiler/node_dispositions_table.inc"
  };
  return *kTable;
}

}  // namespace

const NodeDispositionEntry* LookupNodeDisposition(absl::string_view node_kind) {
  const Table& t = GetTable();
  // `flat_hash_map<std::string, V>::find` accepts a
  // `string_view`-shaped key via transparent hashing in newer
  // Abseil; construct a `std::string` to stay portable to older
  // Abseil revisions that the GoogleSQL toolchain might still pin.
  auto it = t.find(std::string(node_kind));
  return it == t.end() ? nullptr : &it->second;
}

namespace internal {

const std::vector<NodeDispositionView>& AllNodeDispositions() {
  static const auto* kView = [] {
    auto* v = new std::vector<NodeDispositionView>();
    const Table& t = GetTable();
    v->reserve(t.size());
    for (const auto& kv : t) {
      v->push_back({absl::string_view(kv.first), &kv.second});
    }
    return v;
  }();
  return *kView;
}

}  // namespace internal

}  // namespace transpiler
}  // namespace duckdb
}  // namespace engine
}  // namespace backend
}  // namespace bigquery_emulator
