// emulator.proto is the internal contract between the Go REST gateway and
// the C++ engine. It is intentionally minimal: the gateway owns the
// public-facing BigQuery REST shape, and only forwards the bits that
// actually need GoogleSQL to do their job.
//
// Code generation is wired up via buf (see ../buf.gen.yaml) for the Go
// side and via CMake (see ../CMakeLists.txt) for the C++ side. The Go
// stubs land in gateway/enginepb/ and are checked in so `go build`
// works without an extra codegen step; the C++ stubs are generated
// fresh into the CMake build tree.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: emulator.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type DatasetRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DatasetRef) Reset() {
	*x = DatasetRef{}
	mi := &file_emulator_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DatasetRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DatasetRef) ProtoMessage() {}

func (x *DatasetRef) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DatasetRef.ProtoReflect.Descriptor instead.
func (*DatasetRef) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{0}
}

func (x *DatasetRef) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *DatasetRef) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

type TableRef struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ProjectId     string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	DatasetId     string                 `protobuf:"bytes,2,opt,name=dataset_id,json=datasetId,proto3" json:"dataset_id,omitempty"`
	TableId       string                 `protobuf:"bytes,3,opt,name=table_id,json=tableId,proto3" json:"table_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableRef) Reset() {
	*x = TableRef{}
	mi := &file_emulator_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableRef) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableRef) ProtoMessage() {}

func (x *TableRef) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableRef.ProtoReflect.Descriptor instead.
func (*TableRef) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{1}
}

func (x *TableRef) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *TableRef) GetDatasetId() string {
	if x != nil {
		return x.DatasetId
	}
	return ""
}

func (x *TableRef) GetTableId() string {
	if x != nil {
		return x.TableId
	}
	return ""
}

type FieldSchema struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Name  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// BigQuery type names: STRING, INT64, FLOAT64, BOOL, TIMESTAMP, DATE,
	// TIME, DATETIME, GEOGRAPHY, BYTES, NUMERIC, BIGNUMERIC, JSON, STRUCT,
	// ARRAY, ...
	Type string `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	// NULLABLE | REQUIRED | REPEATED. Empty defaults to NULLABLE.
	Mode          string         `protobuf:"bytes,3,opt,name=mode,proto3" json:"mode,omitempty"`
	Description   string         `protobuf:"bytes,4,opt,name=description,proto3" json:"description,omitempty"`
	Fields        []*FieldSchema `protobuf:"bytes,5,rep,name=fields,proto3" json:"fields,omitempty"` // for STRUCT/RECORD.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FieldSchema) Reset() {
	*x = FieldSchema{}
	mi := &file_emulator_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FieldSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FieldSchema) ProtoMessage() {}

func (x *FieldSchema) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FieldSchema.ProtoReflect.Descriptor instead.
func (*FieldSchema) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{2}
}

func (x *FieldSchema) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *FieldSchema) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *FieldSchema) GetMode() string {
	if x != nil {
		return x.Mode
	}
	return ""
}

func (x *FieldSchema) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *FieldSchema) GetFields() []*FieldSchema {
	if x != nil {
		return x.Fields
	}
	return nil
}

type TableSchema struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*FieldSchema         `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *TableSchema) Reset() {
	*x = TableSchema{}
	mi := &file_emulator_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TableSchema) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TableSchema) ProtoMessage() {}

func (x *TableSchema) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TableSchema.ProtoReflect.Descriptor instead.
func (*TableSchema) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{3}
}

func (x *TableSchema) GetFields() []*FieldSchema {
	if x != nil {
		return x.Fields
	}
	return nil
}

type RegisterDatasetRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Dataset       *DatasetRef            `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	Location      string                 `protobuf:"bytes,2,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDatasetRequest) Reset() {
	*x = RegisterDatasetRequest{}
	mi := &file_emulator_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDatasetRequest) ProtoMessage() {}

func (x *RegisterDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDatasetRequest.ProtoReflect.Descriptor instead.
func (*RegisterDatasetRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{4}
}

func (x *RegisterDatasetRequest) GetDataset() *DatasetRef {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *RegisterDatasetRequest) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

type RegisterDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterDatasetResponse) Reset() {
	*x = RegisterDatasetResponse{}
	mi := &file_emulator_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterDatasetResponse) ProtoMessage() {}

func (x *RegisterDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterDatasetResponse.ProtoReflect.Descriptor instead.
func (*RegisterDatasetResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{5}
}

type DropDatasetRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Dataset        *DatasetRef            `protobuf:"bytes,1,opt,name=dataset,proto3" json:"dataset,omitempty"`
	DeleteContents bool                   `protobuf:"varint,2,opt,name=delete_contents,json=deleteContents,proto3" json:"delete_contents,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *DropDatasetRequest) Reset() {
	*x = DropDatasetRequest{}
	mi := &file_emulator_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatasetRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatasetRequest) ProtoMessage() {}

func (x *DropDatasetRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatasetRequest.ProtoReflect.Descriptor instead.
func (*DropDatasetRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{6}
}

func (x *DropDatasetRequest) GetDataset() *DatasetRef {
	if x != nil {
		return x.Dataset
	}
	return nil
}

func (x *DropDatasetRequest) GetDeleteContents() bool {
	if x != nil {
		return x.DeleteContents
	}
	return false
}

type DropDatasetResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropDatasetResponse) Reset() {
	*x = DropDatasetResponse{}
	mi := &file_emulator_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropDatasetResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropDatasetResponse) ProtoMessage() {}

func (x *DropDatasetResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropDatasetResponse.ProtoReflect.Descriptor instead.
func (*DropDatasetResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{7}
}

type RegisterTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	Schema        *TableSchema           `protobuf:"bytes,2,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTableRequest) Reset() {
	*x = RegisterTableRequest{}
	mi := &file_emulator_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTableRequest) ProtoMessage() {}

func (x *RegisterTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTableRequest.ProtoReflect.Descriptor instead.
func (*RegisterTableRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterTableRequest) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

func (x *RegisterTableRequest) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type RegisterTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterTableResponse) Reset() {
	*x = RegisterTableResponse{}
	mi := &file_emulator_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterTableResponse) ProtoMessage() {}

func (x *RegisterTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterTableResponse.ProtoReflect.Descriptor instead.
func (*RegisterTableResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{9}
}

type DropTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTableRequest) Reset() {
	*x = DropTableRequest{}
	mi := &file_emulator_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableRequest) ProtoMessage() {}

func (x *DropTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableRequest.ProtoReflect.Descriptor instead.
func (*DropTableRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{10}
}

func (x *DropTableRequest) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

type DropTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DropTableResponse) Reset() {
	*x = DropTableResponse{}
	mi := &file_emulator_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DropTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DropTableResponse) ProtoMessage() {}

func (x *DropTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DropTableResponse.ProtoReflect.Descriptor instead.
func (*DropTableResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{11}
}

type DescribeTableRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Table         *TableRef              `protobuf:"bytes,1,opt,name=table,proto3" json:"table,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTableRequest) Reset() {
	*x = DescribeTableRequest{}
	mi := &file_emulator_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTableRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTableRequest) ProtoMessage() {}

func (x *DescribeTableRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTableRequest.ProtoReflect.Descriptor instead.
func (*DescribeTableRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{12}
}

func (x *DescribeTableRequest) GetTable() *TableRef {
	if x != nil {
		return x.Table
	}
	return nil
}

type DescribeTableResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Schema        *TableSchema           `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DescribeTableResponse) Reset() {
	*x = DescribeTableResponse{}
	mi := &file_emulator_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DescribeTableResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DescribeTableResponse) ProtoMessage() {}

func (x *DescribeTableResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DescribeTableResponse.ProtoReflect.Descriptor instead.
func (*DescribeTableResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{13}
}

func (x *DescribeTableResponse) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

type QueryRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	ProjectId string                 `protobuf:"bytes,1,opt,name=project_id,json=projectId,proto3" json:"project_id,omitempty"`
	// Default dataset for unqualified table references.
	DefaultDatasetId string `protobuf:"bytes,2,opt,name=default_dataset_id,json=defaultDatasetId,proto3" json:"default_dataset_id,omitempty"`
	Sql              string `protobuf:"bytes,3,opt,name=sql,proto3" json:"sql,omitempty"`
	// Optional: query parameters keyed by name. Positional parameters use
	// an empty key (BigQuery's @0, @1, ... convention is unrolled here).
	Parameters    map[string]*QueryParameter `protobuf:"bytes,4,rep,name=parameters,proto3" json:"parameters,omitempty" protobuf_key:"bytes,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	UseLegacySql  bool                       `protobuf:"varint,5,opt,name=use_legacy_sql,json=useLegacySql,proto3" json:"use_legacy_sql,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryRequest) Reset() {
	*x = QueryRequest{}
	mi := &file_emulator_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryRequest) ProtoMessage() {}

func (x *QueryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryRequest.ProtoReflect.Descriptor instead.
func (*QueryRequest) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{14}
}

func (x *QueryRequest) GetProjectId() string {
	if x != nil {
		return x.ProjectId
	}
	return ""
}

func (x *QueryRequest) GetDefaultDatasetId() string {
	if x != nil {
		return x.DefaultDatasetId
	}
	return ""
}

func (x *QueryRequest) GetSql() string {
	if x != nil {
		return x.Sql
	}
	return ""
}

func (x *QueryRequest) GetParameters() map[string]*QueryParameter {
	if x != nil {
		return x.Parameters
	}
	return nil
}

func (x *QueryRequest) GetUseLegacySql() bool {
	if x != nil {
		return x.UseLegacySql
	}
	return false
}

type QueryParameter struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TypeKind      string                 `protobuf:"bytes,1,opt,name=type_kind,json=typeKind,proto3" json:"type_kind,omitempty"`    // googlesql TypeKind name (e.g. INT64, STRING).
	ValueJson     string                 `protobuf:"bytes,2,opt,name=value_json,json=valueJson,proto3" json:"value_json,omitempty"` // JSON-encoded literal value.
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryParameter) Reset() {
	*x = QueryParameter{}
	mi := &file_emulator_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryParameter) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryParameter) ProtoMessage() {}

func (x *QueryParameter) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryParameter.ProtoReflect.Descriptor instead.
func (*QueryParameter) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{15}
}

func (x *QueryParameter) GetTypeKind() string {
	if x != nil {
		return x.TypeKind
	}
	return ""
}

func (x *QueryParameter) GetValueJson() string {
	if x != nil {
		return x.ValueJson
	}
	return ""
}

type DryRunResponse struct {
	state                   protoimpl.MessageState `protogen:"open.v1"`
	Schema                  *TableSchema           `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	EstimatedBytesProcessed int64                  `protobuf:"varint,2,opt,name=estimated_bytes_processed,json=estimatedBytesProcessed,proto3" json:"estimated_bytes_processed,omitempty"`
	unknownFields           protoimpl.UnknownFields
	sizeCache               protoimpl.SizeCache
}

func (x *DryRunResponse) Reset() {
	*x = DryRunResponse{}
	mi := &file_emulator_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DryRunResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DryRunResponse) ProtoMessage() {}

func (x *DryRunResponse) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DryRunResponse.ProtoReflect.Descriptor instead.
func (*DryRunResponse) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{16}
}

func (x *DryRunResponse) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *DryRunResponse) GetEstimatedBytesProcessed() int64 {
	if x != nil {
		return x.EstimatedBytesProcessed
	}
	return 0
}

type QueryResultRow struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// First message in the stream carries the schema; subsequent messages
	// carry rows. Either `schema` or `cells` is set, not both.
	Schema        *TableSchema `protobuf:"bytes,1,opt,name=schema,proto3" json:"schema,omitempty"`
	Cells         []*Cell      `protobuf:"bytes,2,rep,name=cells,proto3" json:"cells,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueryResultRow) Reset() {
	*x = QueryResultRow{}
	mi := &file_emulator_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueryResultRow) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueryResultRow) ProtoMessage() {}

func (x *QueryResultRow) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueryResultRow.ProtoReflect.Descriptor instead.
func (*QueryResultRow) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{17}
}

func (x *QueryResultRow) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *QueryResultRow) GetCells() []*Cell {
	if x != nil {
		return x.Cells
	}
	return nil
}

type Cell struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Wire shape: either `string_value`, `null_value`, `array`, or `struct`
	// is set. Mirrors googlesql::Value's flavor of variant.
	//
	// Types that are valid to be assigned to Value:
	//
	//	*Cell_StringValue
	//	*Cell_NullValue
	//	*Cell_Array
	//	*Cell_StructValue
	Value         isCell_Value `protobuf_oneof:"value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Cell) Reset() {
	*x = Cell{}
	mi := &file_emulator_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Cell) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Cell) ProtoMessage() {}

func (x *Cell) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Cell.ProtoReflect.Descriptor instead.
func (*Cell) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{18}
}

func (x *Cell) GetValue() isCell_Value {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *Cell) GetStringValue() string {
	if x != nil {
		if x, ok := x.Value.(*Cell_StringValue); ok {
			return x.StringValue
		}
	}
	return ""
}

func (x *Cell) GetNullValue() bool {
	if x != nil {
		if x, ok := x.Value.(*Cell_NullValue); ok {
			return x.NullValue
		}
	}
	return false
}

func (x *Cell) GetArray() *Array {
	if x != nil {
		if x, ok := x.Value.(*Cell_Array); ok {
			return x.Array
		}
	}
	return nil
}

func (x *Cell) GetStructValue() *Struct {
	if x != nil {
		if x, ok := x.Value.(*Cell_StructValue); ok {
			return x.StructValue
		}
	}
	return nil
}

type isCell_Value interface {
	isCell_Value()
}

type Cell_StringValue struct {
	StringValue string `protobuf:"bytes,1,opt,name=string_value,json=stringValue,proto3,oneof"`
}

type Cell_NullValue struct {
	NullValue bool `protobuf:"varint,2,opt,name=null_value,json=nullValue,proto3,oneof"`
}

type Cell_Array struct {
	Array *Array `protobuf:"bytes,3,opt,name=array,proto3,oneof"`
}

type Cell_StructValue struct {
	StructValue *Struct `protobuf:"bytes,4,opt,name=struct_value,json=structValue,proto3,oneof"`
}

func (*Cell_StringValue) isCell_Value() {}

func (*Cell_NullValue) isCell_Value() {}

func (*Cell_Array) isCell_Value() {}

func (*Cell_StructValue) isCell_Value() {}

type Array struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Elements      []*Cell                `protobuf:"bytes,1,rep,name=elements,proto3" json:"elements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Array) Reset() {
	*x = Array{}
	mi := &file_emulator_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Array) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Array) ProtoMessage() {}

func (x *Array) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Array.ProtoReflect.Descriptor instead.
func (*Array) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{19}
}

func (x *Array) GetElements() []*Cell {
	if x != nil {
		return x.Elements
	}
	return nil
}

type Struct struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Fields        []*Cell                `protobuf:"bytes,1,rep,name=fields,proto3" json:"fields,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Struct) Reset() {
	*x = Struct{}
	mi := &file_emulator_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Struct) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Struct) ProtoMessage() {}

func (x *Struct) ProtoReflect() protoreflect.Message {
	mi := &file_emulator_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Struct.ProtoReflect.Descriptor instead.
func (*Struct) Descriptor() ([]byte, []int) {
	return file_emulator_proto_rawDescGZIP(), []int{20}
}

func (x *Struct) GetFields() []*Cell {
	if x != nil {
		return x.Fields
	}
	return nil
}

var File_emulator_proto protoreflect.FileDescriptor

const file_emulator_proto_rawDesc = "" +
	"\n" +
	"\x0eemulator.proto\x12\x14bigquery_emulator.v1\"J\n" +
	"\n" +
	"DatasetRef\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\"c\n" +
	"\bTableRef\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12\x1d\n" +
	"\n" +
	"dataset_id\x18\x02 \x01(\tR\tdatasetId\x12\x19\n" +
	"\btable_id\x18\x03 \x01(\tR\atableId\"\xa6\x01\n" +
	"\vFieldSchema\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12\x12\n" +
	"\x04mode\x18\x03 \x01(\tR\x04mode\x12 \n" +
	"\vdescription\x18\x04 \x01(\tR\vdescription\x129\n" +
	"\x06fields\x18\x05 \x03(\v2!.bigquery_emulator.v1.FieldSchemaR\x06fields\"H\n" +
	"\vTableSchema\x129\n" +
	"\x06fields\x18\x01 \x03(\v2!.bigquery_emulator.v1.FieldSchemaR\x06fields\"p\n" +
	"\x16RegisterDatasetRequest\x12:\n" +
	"\adataset\x18\x01 \x01(\v2 .bigquery_emulator.v1.DatasetRefR\adataset\x12\x1a\n" +
	"\blocation\x18\x02 \x01(\tR\blocation\"\x19\n" +
	"\x17RegisterDatasetResponse\"y\n" +
	"\x12DropDatasetRequest\x12:\n" +
	"\adataset\x18\x01 \x01(\v2 .bigquery_emulator.v1.DatasetRefR\adataset\x12'\n" +
	"\x0fdelete_contents\x18\x02 \x01(\bR\x0edeleteContents\"\x15\n" +
	"\x13DropDatasetResponse\"\x87\x01\n" +
	"\x14RegisterTableRequest\x124\n" +
	"\x05table\x18\x01 \x01(\v2\x1e.bigquery_emulator.v1.TableRefR\x05table\x129\n" +
	"\x06schema\x18\x02 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\"\x17\n" +
	"\x15RegisterTableResponse\"H\n" +
	"\x10DropTableRequest\x124\n" +
	"\x05table\x18\x01 \x01(\v2\x1e.bigquery_emulator.v1.TableRefR\x05table\"\x13\n" +
	"\x11DropTableResponse\"L\n" +
	"\x14DescribeTableRequest\x124\n" +
	"\x05table\x18\x01 \x01(\v2\x1e.bigquery_emulator.v1.TableRefR\x05table\"R\n" +
	"\x15DescribeTableResponse\x129\n" +
	"\x06schema\x18\x01 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\"\xcc\x02\n" +
	"\fQueryRequest\x12\x1d\n" +
	"\n" +
	"project_id\x18\x01 \x01(\tR\tprojectId\x12,\n" +
	"\x12default_dataset_id\x18\x02 \x01(\tR\x10defaultDatasetId\x12\x10\n" +
	"\x03sql\x18\x03 \x01(\tR\x03sql\x12R\n" +
	"\n" +
	"parameters\x18\x04 \x03(\v22.bigquery_emulator.v1.QueryRequest.ParametersEntryR\n" +
	"parameters\x12$\n" +
	"\x0euse_legacy_sql\x18\x05 \x01(\bR\fuseLegacySql\x1ac\n" +
	"\x0fParametersEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12:\n" +
	"\x05value\x18\x02 \x01(\v2$.bigquery_emulator.v1.QueryParameterR\x05value:\x028\x01\"L\n" +
	"\x0eQueryParameter\x12\x1b\n" +
	"\ttype_kind\x18\x01 \x01(\tR\btypeKind\x12\x1d\n" +
	"\n" +
	"value_json\x18\x02 \x01(\tR\tvalueJson\"\x87\x01\n" +
	"\x0eDryRunResponse\x129\n" +
	"\x06schema\x18\x01 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\x12:\n" +
	"\x19estimated_bytes_processed\x18\x02 \x01(\x03R\x17estimatedBytesProcessed\"}\n" +
	"\x0eQueryResultRow\x129\n" +
	"\x06schema\x18\x01 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\x120\n" +
	"\x05cells\x18\x02 \x03(\v2\x1a.bigquery_emulator.v1.CellR\x05cells\"\xcd\x01\n" +
	"\x04Cell\x12#\n" +
	"\fstring_value\x18\x01 \x01(\tH\x00R\vstringValue\x12\x1f\n" +
	"\n" +
	"null_value\x18\x02 \x01(\bH\x00R\tnullValue\x123\n" +
	"\x05array\x18\x03 \x01(\v2\x1b.bigquery_emulator.v1.ArrayH\x00R\x05array\x12A\n" +
	"\fstruct_value\x18\x04 \x01(\v2\x1c.bigquery_emulator.v1.StructH\x00R\vstructValueB\a\n" +
	"\x05value\"?\n" +
	"\x05Array\x126\n" +
	"\belements\x18\x01 \x03(\v2\x1a.bigquery_emulator.v1.CellR\belements\"<\n" +
	"\x06Struct\x122\n" +
	"\x06fields\x18\x01 \x03(\v2\x1a.bigquery_emulator.v1.CellR\x06fields2\x8f\x04\n" +
	"\aCatalog\x12n\n" +
	"\x0fRegisterDataset\x12,.bigquery_emulator.v1.RegisterDatasetRequest\x1a-.bigquery_emulator.v1.RegisterDatasetResponse\x12b\n" +
	"\vDropDataset\x12(.bigquery_emulator.v1.DropDatasetRequest\x1a).bigquery_emulator.v1.DropDatasetResponse\x12h\n" +
	"\rRegisterTable\x12*.bigquery_emulator.v1.RegisterTableRequest\x1a+.bigquery_emulator.v1.RegisterTableResponse\x12\\\n" +
	"\tDropTable\x12&.bigquery_emulator.v1.DropTableRequest\x1a'.bigquery_emulator.v1.DropTableResponse\x12h\n" +
	"\rDescribeTable\x12*.bigquery_emulator.v1.DescribeTableRequest\x1a+.bigquery_emulator.v1.DescribeTableResponse2\xb7\x01\n" +
	"\x05Query\x12R\n" +
	"\x06DryRun\x12\".bigquery_emulator.v1.QueryRequest\x1a$.bigquery_emulator.v1.DryRunResponse\x12Z\n" +
	"\fExecuteQuery\x12\".bigquery_emulator.v1.QueryRequest\x1a$.bigquery_emulator.v1.QueryResultRow0\x01BFZAgithub.com/vantaboard/bigquery-emulator/gateway/enginepb;enginepb\xf8\x01\x01b\x06proto3"

var (
	file_emulator_proto_rawDescOnce sync.Once
	file_emulator_proto_rawDescData []byte
)

func file_emulator_proto_rawDescGZIP() []byte {
	file_emulator_proto_rawDescOnce.Do(func() {
		file_emulator_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_emulator_proto_rawDesc), len(file_emulator_proto_rawDesc)))
	})
	return file_emulator_proto_rawDescData
}

var file_emulator_proto_msgTypes = make([]protoimpl.MessageInfo, 22)
var file_emulator_proto_goTypes = []any{
	(*DatasetRef)(nil),              // 0: bigquery_emulator.v1.DatasetRef
	(*TableRef)(nil),                // 1: bigquery_emulator.v1.TableRef
	(*FieldSchema)(nil),             // 2: bigquery_emulator.v1.FieldSchema
	(*TableSchema)(nil),             // 3: bigquery_emulator.v1.TableSchema
	(*RegisterDatasetRequest)(nil),  // 4: bigquery_emulator.v1.RegisterDatasetRequest
	(*RegisterDatasetResponse)(nil), // 5: bigquery_emulator.v1.RegisterDatasetResponse
	(*DropDatasetRequest)(nil),      // 6: bigquery_emulator.v1.DropDatasetRequest
	(*DropDatasetResponse)(nil),     // 7: bigquery_emulator.v1.DropDatasetResponse
	(*RegisterTableRequest)(nil),    // 8: bigquery_emulator.v1.RegisterTableRequest
	(*RegisterTableResponse)(nil),   // 9: bigquery_emulator.v1.RegisterTableResponse
	(*DropTableRequest)(nil),        // 10: bigquery_emulator.v1.DropTableRequest
	(*DropTableResponse)(nil),       // 11: bigquery_emulator.v1.DropTableResponse
	(*DescribeTableRequest)(nil),    // 12: bigquery_emulator.v1.DescribeTableRequest
	(*DescribeTableResponse)(nil),   // 13: bigquery_emulator.v1.DescribeTableResponse
	(*QueryRequest)(nil),            // 14: bigquery_emulator.v1.QueryRequest
	(*QueryParameter)(nil),          // 15: bigquery_emulator.v1.QueryParameter
	(*DryRunResponse)(nil),          // 16: bigquery_emulator.v1.DryRunResponse
	(*QueryResultRow)(nil),          // 17: bigquery_emulator.v1.QueryResultRow
	(*Cell)(nil),                    // 18: bigquery_emulator.v1.Cell
	(*Array)(nil),                   // 19: bigquery_emulator.v1.Array
	(*Struct)(nil),                  // 20: bigquery_emulator.v1.Struct
	nil,                             // 21: bigquery_emulator.v1.QueryRequest.ParametersEntry
}
var file_emulator_proto_depIdxs = []int32{
	2,  // 0: bigquery_emulator.v1.FieldSchema.fields:type_name -> bigquery_emulator.v1.FieldSchema
	2,  // 1: bigquery_emulator.v1.TableSchema.fields:type_name -> bigquery_emulator.v1.FieldSchema
	0,  // 2: bigquery_emulator.v1.RegisterDatasetRequest.dataset:type_name -> bigquery_emulator.v1.DatasetRef
	0,  // 3: bigquery_emulator.v1.DropDatasetRequest.dataset:type_name -> bigquery_emulator.v1.DatasetRef
	1,  // 4: bigquery_emulator.v1.RegisterTableRequest.table:type_name -> bigquery_emulator.v1.TableRef
	3,  // 5: bigquery_emulator.v1.RegisterTableRequest.schema:type_name -> bigquery_emulator.v1.TableSchema
	1,  // 6: bigquery_emulator.v1.DropTableRequest.table:type_name -> bigquery_emulator.v1.TableRef
	1,  // 7: bigquery_emulator.v1.DescribeTableRequest.table:type_name -> bigquery_emulator.v1.TableRef
	3,  // 8: bigquery_emulator.v1.DescribeTableResponse.schema:type_name -> bigquery_emulator.v1.TableSchema
	21, // 9: bigquery_emulator.v1.QueryRequest.parameters:type_name -> bigquery_emulator.v1.QueryRequest.ParametersEntry
	3,  // 10: bigquery_emulator.v1.DryRunResponse.schema:type_name -> bigquery_emulator.v1.TableSchema
	3,  // 11: bigquery_emulator.v1.QueryResultRow.schema:type_name -> bigquery_emulator.v1.TableSchema
	18, // 12: bigquery_emulator.v1.QueryResultRow.cells:type_name -> bigquery_emulator.v1.Cell
	19, // 13: bigquery_emulator.v1.Cell.array:type_name -> bigquery_emulator.v1.Array
	20, // 14: bigquery_emulator.v1.Cell.struct_value:type_name -> bigquery_emulator.v1.Struct
	18, // 15: bigquery_emulator.v1.Array.elements:type_name -> bigquery_emulator.v1.Cell
	18, // 16: bigquery_emulator.v1.Struct.fields:type_name -> bigquery_emulator.v1.Cell
	15, // 17: bigquery_emulator.v1.QueryRequest.ParametersEntry.value:type_name -> bigquery_emulator.v1.QueryParameter
	4,  // 18: bigquery_emulator.v1.Catalog.RegisterDataset:input_type -> bigquery_emulator.v1.RegisterDatasetRequest
	6,  // 19: bigquery_emulator.v1.Catalog.DropDataset:input_type -> bigquery_emulator.v1.DropDatasetRequest
	8,  // 20: bigquery_emulator.v1.Catalog.RegisterTable:input_type -> bigquery_emulator.v1.RegisterTableRequest
	10, // 21: bigquery_emulator.v1.Catalog.DropTable:input_type -> bigquery_emulator.v1.DropTableRequest
	12, // 22: bigquery_emulator.v1.Catalog.DescribeTable:input_type -> bigquery_emulator.v1.DescribeTableRequest
	14, // 23: bigquery_emulator.v1.Query.DryRun:input_type -> bigquery_emulator.v1.QueryRequest
	14, // 24: bigquery_emulator.v1.Query.ExecuteQuery:input_type -> bigquery_emulator.v1.QueryRequest
	5,  // 25: bigquery_emulator.v1.Catalog.RegisterDataset:output_type -> bigquery_emulator.v1.RegisterDatasetResponse
	7,  // 26: bigquery_emulator.v1.Catalog.DropDataset:output_type -> bigquery_emulator.v1.DropDatasetResponse
	9,  // 27: bigquery_emulator.v1.Catalog.RegisterTable:output_type -> bigquery_emulator.v1.RegisterTableResponse
	11, // 28: bigquery_emulator.v1.Catalog.DropTable:output_type -> bigquery_emulator.v1.DropTableResponse
	13, // 29: bigquery_emulator.v1.Catalog.DescribeTable:output_type -> bigquery_emulator.v1.DescribeTableResponse
	16, // 30: bigquery_emulator.v1.Query.DryRun:output_type -> bigquery_emulator.v1.DryRunResponse
	17, // 31: bigquery_emulator.v1.Query.ExecuteQuery:output_type -> bigquery_emulator.v1.QueryResultRow
	25, // [25:32] is the sub-list for method output_type
	18, // [18:25] is the sub-list for method input_type
	18, // [18:18] is the sub-list for extension type_name
	18, // [18:18] is the sub-list for extension extendee
	0,  // [0:18] is the sub-list for field type_name
}

func init() { file_emulator_proto_init() }
func file_emulator_proto_init() {
	if File_emulator_proto != nil {
		return
	}
	file_emulator_proto_msgTypes[18].OneofWrappers = []any{
		(*Cell_StringValue)(nil),
		(*Cell_NullValue)(nil),
		(*Cell_Array)(nil),
		(*Cell_StructValue)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_emulator_proto_rawDesc), len(file_emulator_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   22,
			NumExtensions: 0,
			NumServices:   2,
		},
		GoTypes:           file_emulator_proto_goTypes,
		DependencyIndexes: file_emulator_proto_depIdxs,
		MessageInfos:      file_emulator_proto_msgTypes,
	}.Build()
	File_emulator_proto = out.File
	file_emulator_proto_goTypes = nil
	file_emulator_proto_depIdxs = nil
}
