// emulator.proto is the internal contract between the Go REST gateway and
// the C++ engine. It is intentionally minimal: the gateway owns the
// public-facing BigQuery REST shape, and only forwards the bits that
// actually need GoogleSQL to do their job.
//
// Code generation is wired up via buf (see ../buf.gen.yaml) for the Go
// side and via Bazel (see ./BUILD.bazel) for the C++ side. The Go
// stubs land in gateway/enginepb/ and are checked in so `go build`
// works without an extra codegen step; the C++ stubs are generated
// fresh into the Bazel output tree.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: emulator.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Catalog_RegisterDataset_FullMethodName = "/bigquery_emulator.v1.Catalog/RegisterDataset"
	Catalog_DropDataset_FullMethodName     = "/bigquery_emulator.v1.Catalog/DropDataset"
	Catalog_RegisterTable_FullMethodName   = "/bigquery_emulator.v1.Catalog/RegisterTable"
	Catalog_DropTable_FullMethodName       = "/bigquery_emulator.v1.Catalog/DropTable"
	Catalog_DescribeTable_FullMethodName   = "/bigquery_emulator.v1.Catalog/DescribeTable"
	Catalog_InsertRows_FullMethodName      = "/bigquery_emulator.v1.Catalog/InsertRows"
	Catalog_ListRows_FullMethodName        = "/bigquery_emulator.v1.Catalog/ListRows"
)

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogClient interface {
	RegisterDataset(ctx context.Context, in *RegisterDatasetRequest, opts ...grpc.CallOption) (*RegisterDatasetResponse, error)
	DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error)
	RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
	DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error)
	// Row-level access. `InsertRows` delegates to `Storage::AppendRows`
	// and is the engine side of `tabledata.insertAll`. `ListRows` is
	// the engine side of `tabledata.list` and returns a single
	// (possibly empty) page of rows plus the total row count so the
	// gateway can synthesize BigQuery's pageToken semantics.
	InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error)
	ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*ListRowsResponse, error)
}

type catalogClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogClient(cc grpc.ClientConnInterface) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) RegisterDataset(ctx context.Context, in *RegisterDatasetRequest, opts ...grpc.CallOption) (*RegisterDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDatasetResponse)
	err := c.cc.Invoke(ctx, Catalog_RegisterDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatasetResponse)
	err := c.cc.Invoke(ctx, Catalog_DropDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTableResponse)
	err := c.cc.Invoke(ctx, Catalog_RegisterTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, Catalog_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTableResponse)
	err := c.cc.Invoke(ctx, Catalog_DescribeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertRowsResponse)
	err := c.cc.Invoke(ctx, Catalog_InsertRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*ListRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRowsResponse)
	err := c.cc.Invoke(ctx, Catalog_ListRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
// All implementations should embed UnimplementedCatalogServer
// for forward compatibility.
type CatalogServer interface {
	RegisterDataset(context.Context, *RegisterDatasetRequest) (*RegisterDatasetResponse, error)
	DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error)
	RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error)
	// Row-level access. `InsertRows` delegates to `Storage::AppendRows`
	// and is the engine side of `tabledata.insertAll`. `ListRows` is
	// the engine side of `tabledata.list` and returns a single
	// (possibly empty) page of rows plus the total row count so the
	// gateway can synthesize BigQuery's pageToken semantics.
	InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error)
	ListRows(context.Context, *ListRowsRequest) (*ListRowsResponse, error)
}

// UnimplementedCatalogServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServer struct{}

func (UnimplementedCatalogServer) RegisterDataset(context.Context, *RegisterDatasetRequest) (*RegisterDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDataset not implemented")
}
func (UnimplementedCatalogServer) DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDataset not implemented")
}
func (UnimplementedCatalogServer) RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTable not implemented")
}
func (UnimplementedCatalogServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedCatalogServer) DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTable not implemented")
}
func (UnimplementedCatalogServer) InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertRows not implemented")
}
func (UnimplementedCatalogServer) ListRows(context.Context, *ListRowsRequest) (*ListRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRows not implemented")
}
func (UnimplementedCatalogServer) testEmbeddedByValue() {}

// UnsafeCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServer will
// result in compilation errors.
type UnsafeCatalogServer interface {
	mustEmbedUnimplementedCatalogServer()
}

func RegisterCatalogServer(s grpc.ServiceRegistrar, srv CatalogServer) {
	// If the following call panics, it indicates UnimplementedCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Catalog_ServiceDesc, srv)
}

func _Catalog_RegisterDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).RegisterDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_RegisterDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).RegisterDataset(ctx, req.(*RegisterDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DropDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DropDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DropDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DropDataset(ctx, req.(*DropDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_RegisterTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).RegisterTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_RegisterTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).RegisterTable(ctx, req.(*RegisterTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DescribeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DescribeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DescribeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DescribeTable(ctx, req.(*DescribeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_InsertRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).InsertRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_InsertRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).InsertRows(ctx, req.(*InsertRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListRows(ctx, req.(*ListRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalog_ServiceDesc is the grpc.ServiceDesc for Catalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDataset",
			Handler:    _Catalog_RegisterDataset_Handler,
		},
		{
			MethodName: "DropDataset",
			Handler:    _Catalog_DropDataset_Handler,
		},
		{
			MethodName: "RegisterTable",
			Handler:    _Catalog_RegisterTable_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _Catalog_DropTable_Handler,
		},
		{
			MethodName: "DescribeTable",
			Handler:    _Catalog_DescribeTable_Handler,
		},
		{
			MethodName: "InsertRows",
			Handler:    _Catalog_InsertRows_Handler,
		},
		{
			MethodName: "ListRows",
			Handler:    _Catalog_ListRows_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emulator.proto",
}

const (
	Query_DryRun_FullMethodName       = "/bigquery_emulator.v1.Query/DryRun"
	Query_ExecuteQuery_FullMethodName = "/bigquery_emulator.v1.Query/ExecuteQuery"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	DryRun(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*DryRunResponse, error)
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultRow], error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DryRun(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*DryRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunResponse)
	err := c.cc.Invoke(ctx, Query_DryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Query_ServiceDesc.Streams[0], Query_ExecuteQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResultRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Query_ExecuteQueryClient = grpc.ServerStreamingClient[QueryResultRow]

// QueryServer is the server API for Query service.
// All implementations should embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	DryRun(context.Context, *QueryRequest) (*DryRunResponse, error)
	ExecuteQuery(*QueryRequest, grpc.ServerStreamingServer[QueryResultRow]) error
}

// UnimplementedQueryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) DryRun(context.Context, *QueryRequest) (*DryRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRun not implemented")
}
func (UnimplementedQueryServer) ExecuteQuery(*QueryRequest, grpc.ServerStreamingServer[QueryResultRow]) error {
	return status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedQueryServer) testEmbeddedByValue() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_DryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DryRun(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ExecuteQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).ExecuteQuery(m, &grpc.GenericServerStream[QueryRequest, QueryResultRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Query_ExecuteQueryServer = grpc.ServerStreamingServer[QueryResultRow]

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DryRun",
			Handler:    _Query_DryRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteQuery",
			Handler:       _Query_ExecuteQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emulator.proto",
}
