// emulator.proto is the internal contract between the Go REST gateway and
// the C++ engine. It is intentionally minimal: the gateway owns the
// public-facing BigQuery REST shape, and only forwards the bits that
// actually need GoogleSQL to do their job.
//
// Code generation is wired up via buf (see ../buf.gen.yaml) for the Go
// side and via Bazel (see ./BUILD.bazel) for the C++ side. The Go
// stubs land in gateway/enginepb/ and are checked in so `go build`
// works without an extra codegen step; the C++ stubs are generated
// fresh into the Bazel output tree.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: emulator.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	Catalog_RegisterDataset_FullMethodName       = "/bigquery_emulator.v1.Catalog/RegisterDataset"
	Catalog_DropDataset_FullMethodName           = "/bigquery_emulator.v1.Catalog/DropDataset"
	Catalog_ListDatasets_FullMethodName          = "/bigquery_emulator.v1.Catalog/ListDatasets"
	Catalog_RegisterTable_FullMethodName         = "/bigquery_emulator.v1.Catalog/RegisterTable"
	Catalog_DropTable_FullMethodName             = "/bigquery_emulator.v1.Catalog/DropTable"
	Catalog_ListTables_FullMethodName            = "/bigquery_emulator.v1.Catalog/ListTables"
	Catalog_DescribeTable_FullMethodName         = "/bigquery_emulator.v1.Catalog/DescribeTable"
	Catalog_InsertRows_FullMethodName            = "/bigquery_emulator.v1.Catalog/InsertRows"
	Catalog_ListRows_FullMethodName              = "/bigquery_emulator.v1.Catalog/ListRows"
	Catalog_ListRoutines_FullMethodName          = "/bigquery_emulator.v1.Catalog/ListRoutines"
	Catalog_GetRoutine_FullMethodName            = "/bigquery_emulator.v1.Catalog/GetRoutine"
	Catalog_UpsertRoutine_FullMethodName         = "/bigquery_emulator.v1.Catalog/UpsertRoutine"
	Catalog_DeleteRoutine_FullMethodName         = "/bigquery_emulator.v1.Catalog/DeleteRoutine"
	Catalog_UpsertRowAccessPolicy_FullMethodName = "/bigquery_emulator.v1.Catalog/UpsertRowAccessPolicy"
	Catalog_DeleteRowAccessPolicy_FullMethodName = "/bigquery_emulator.v1.Catalog/DeleteRowAccessPolicy"
	Catalog_ListRowAccessPolicies_FullMethodName = "/bigquery_emulator.v1.Catalog/ListRowAccessPolicies"
	Catalog_SetColumnGovernance_FullMethodName   = "/bigquery_emulator.v1.Catalog/SetColumnGovernance"
)

// CatalogClient is the client API for Catalog service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type CatalogClient interface {
	RegisterDataset(ctx context.Context, in *RegisterDatasetRequest, opts ...grpc.CallOption) (*RegisterDatasetResponse, error)
	DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error)
	// Lists every dataset registered under `project_id`. The gateway's
	// `datasets.list` REST handler delegates here; the response is
	// shaped as a single page (no continuation cursor today, the
	// emulator never has enough datasets to need one).
	ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error)
	RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error)
	DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error)
	// Lists every table registered under `dataset`. The gateway's
	// `tables.list` REST handler delegates here; pagination contract
	// matches ListDatasets.
	ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error)
	DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error)
	// Row-level access. `InsertRows` delegates to `Storage::AppendRows`
	// and is the engine side of `tabledata.insertAll`. `ListRows` is
	// the engine side of `tabledata.list` and returns a single
	// (possibly empty) page of rows plus the total row count so the
	// gateway can synthesize BigQuery's pageToken semantics.
	InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error)
	ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*ListRowsResponse, error)
	// Routine metadata persisted in `catalog.duckdb` for REST
	// round-trip and cross-restart SQL UDF / TVF / procedure replay.
	ListRoutines(ctx context.Context, in *ListRoutinesRequest, opts ...grpc.CallOption) (*ListRoutinesResponse, error)
	GetRoutine(ctx context.Context, in *GetRoutineRequest, opts ...grpc.CallOption) (*GetRoutineResponse, error)
	UpsertRoutine(ctx context.Context, in *UpsertRoutineRequest, opts ...grpc.CallOption) (*UpsertRoutineResponse, error)
	DeleteRoutine(ctx context.Context, in *DeleteRoutineRequest, opts ...grpc.CallOption) (*DeleteRoutineResponse, error)
	// Row-access policies and column-level security metadata.
	UpsertRowAccessPolicy(ctx context.Context, in *UpsertRowAccessPolicyRequest, opts ...grpc.CallOption) (*UpsertRowAccessPolicyResponse, error)
	DeleteRowAccessPolicy(ctx context.Context, in *DeleteRowAccessPolicyRequest, opts ...grpc.CallOption) (*DeleteRowAccessPolicyResponse, error)
	ListRowAccessPolicies(ctx context.Context, in *ListRowAccessPoliciesRequest, opts ...grpc.CallOption) (*ListRowAccessPoliciesResponse, error)
	SetColumnGovernance(ctx context.Context, in *SetColumnGovernanceRequest, opts ...grpc.CallOption) (*SetColumnGovernanceResponse, error)
}

type catalogClient struct {
	cc grpc.ClientConnInterface
}

func NewCatalogClient(cc grpc.ClientConnInterface) CatalogClient {
	return &catalogClient{cc}
}

func (c *catalogClient) RegisterDataset(ctx context.Context, in *RegisterDatasetRequest, opts ...grpc.CallOption) (*RegisterDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterDatasetResponse)
	err := c.cc.Invoke(ctx, Catalog_RegisterDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DropDataset(ctx context.Context, in *DropDatasetRequest, opts ...grpc.CallOption) (*DropDatasetResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropDatasetResponse)
	err := c.cc.Invoke(ctx, Catalog_DropDataset_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListDatasets(ctx context.Context, in *ListDatasetsRequest, opts ...grpc.CallOption) (*ListDatasetsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDatasetsResponse)
	err := c.cc.Invoke(ctx, Catalog_ListDatasets_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) RegisterTable(ctx context.Context, in *RegisterTableRequest, opts ...grpc.CallOption) (*RegisterTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RegisterTableResponse)
	err := c.cc.Invoke(ctx, Catalog_RegisterTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DropTable(ctx context.Context, in *DropTableRequest, opts ...grpc.CallOption) (*DropTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DropTableResponse)
	err := c.cc.Invoke(ctx, Catalog_DropTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListTables(ctx context.Context, in *ListTablesRequest, opts ...grpc.CallOption) (*ListTablesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListTablesResponse)
	err := c.cc.Invoke(ctx, Catalog_ListTables_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DescribeTable(ctx context.Context, in *DescribeTableRequest, opts ...grpc.CallOption) (*DescribeTableResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DescribeTableResponse)
	err := c.cc.Invoke(ctx, Catalog_DescribeTable_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) InsertRows(ctx context.Context, in *InsertRowsRequest, opts ...grpc.CallOption) (*InsertRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(InsertRowsResponse)
	err := c.cc.Invoke(ctx, Catalog_InsertRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListRows(ctx context.Context, in *ListRowsRequest, opts ...grpc.CallOption) (*ListRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRowsResponse)
	err := c.cc.Invoke(ctx, Catalog_ListRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListRoutines(ctx context.Context, in *ListRoutinesRequest, opts ...grpc.CallOption) (*ListRoutinesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRoutinesResponse)
	err := c.cc.Invoke(ctx, Catalog_ListRoutines_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) GetRoutine(ctx context.Context, in *GetRoutineRequest, opts ...grpc.CallOption) (*GetRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoutineResponse)
	err := c.cc.Invoke(ctx, Catalog_GetRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpsertRoutine(ctx context.Context, in *UpsertRoutineRequest, opts ...grpc.CallOption) (*UpsertRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRoutineResponse)
	err := c.cc.Invoke(ctx, Catalog_UpsertRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DeleteRoutine(ctx context.Context, in *DeleteRoutineRequest, opts ...grpc.CallOption) (*DeleteRoutineResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRoutineResponse)
	err := c.cc.Invoke(ctx, Catalog_DeleteRoutine_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) UpsertRowAccessPolicy(ctx context.Context, in *UpsertRowAccessPolicyRequest, opts ...grpc.CallOption) (*UpsertRowAccessPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpsertRowAccessPolicyResponse)
	err := c.cc.Invoke(ctx, Catalog_UpsertRowAccessPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) DeleteRowAccessPolicy(ctx context.Context, in *DeleteRowAccessPolicyRequest, opts ...grpc.CallOption) (*DeleteRowAccessPolicyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteRowAccessPolicyResponse)
	err := c.cc.Invoke(ctx, Catalog_DeleteRowAccessPolicy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) ListRowAccessPolicies(ctx context.Context, in *ListRowAccessPoliciesRequest, opts ...grpc.CallOption) (*ListRowAccessPoliciesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListRowAccessPoliciesResponse)
	err := c.cc.Invoke(ctx, Catalog_ListRowAccessPolicies_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *catalogClient) SetColumnGovernance(ctx context.Context, in *SetColumnGovernanceRequest, opts ...grpc.CallOption) (*SetColumnGovernanceResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SetColumnGovernanceResponse)
	err := c.cc.Invoke(ctx, Catalog_SetColumnGovernance_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// CatalogServer is the server API for Catalog service.
// All implementations should embed UnimplementedCatalogServer
// for forward compatibility.
type CatalogServer interface {
	RegisterDataset(context.Context, *RegisterDatasetRequest) (*RegisterDatasetResponse, error)
	DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error)
	// Lists every dataset registered under `project_id`. The gateway's
	// `datasets.list` REST handler delegates here; the response is
	// shaped as a single page (no continuation cursor today, the
	// emulator never has enough datasets to need one).
	ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error)
	RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error)
	DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error)
	// Lists every table registered under `dataset`. The gateway's
	// `tables.list` REST handler delegates here; pagination contract
	// matches ListDatasets.
	ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error)
	DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error)
	// Row-level access. `InsertRows` delegates to `Storage::AppendRows`
	// and is the engine side of `tabledata.insertAll`. `ListRows` is
	// the engine side of `tabledata.list` and returns a single
	// (possibly empty) page of rows plus the total row count so the
	// gateway can synthesize BigQuery's pageToken semantics.
	InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error)
	ListRows(context.Context, *ListRowsRequest) (*ListRowsResponse, error)
	// Routine metadata persisted in `catalog.duckdb` for REST
	// round-trip and cross-restart SQL UDF / TVF / procedure replay.
	ListRoutines(context.Context, *ListRoutinesRequest) (*ListRoutinesResponse, error)
	GetRoutine(context.Context, *GetRoutineRequest) (*GetRoutineResponse, error)
	UpsertRoutine(context.Context, *UpsertRoutineRequest) (*UpsertRoutineResponse, error)
	DeleteRoutine(context.Context, *DeleteRoutineRequest) (*DeleteRoutineResponse, error)
	// Row-access policies and column-level security metadata.
	UpsertRowAccessPolicy(context.Context, *UpsertRowAccessPolicyRequest) (*UpsertRowAccessPolicyResponse, error)
	DeleteRowAccessPolicy(context.Context, *DeleteRowAccessPolicyRequest) (*DeleteRowAccessPolicyResponse, error)
	ListRowAccessPolicies(context.Context, *ListRowAccessPoliciesRequest) (*ListRowAccessPoliciesResponse, error)
	SetColumnGovernance(context.Context, *SetColumnGovernanceRequest) (*SetColumnGovernanceResponse, error)
}

// UnimplementedCatalogServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedCatalogServer struct{}

func (UnimplementedCatalogServer) RegisterDataset(context.Context, *RegisterDatasetRequest) (*RegisterDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterDataset not implemented")
}
func (UnimplementedCatalogServer) DropDataset(context.Context, *DropDatasetRequest) (*DropDatasetResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropDataset not implemented")
}
func (UnimplementedCatalogServer) ListDatasets(context.Context, *ListDatasetsRequest) (*ListDatasetsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListDatasets not implemented")
}
func (UnimplementedCatalogServer) RegisterTable(context.Context, *RegisterTableRequest) (*RegisterTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RegisterTable not implemented")
}
func (UnimplementedCatalogServer) DropTable(context.Context, *DropTableRequest) (*DropTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DropTable not implemented")
}
func (UnimplementedCatalogServer) ListTables(context.Context, *ListTablesRequest) (*ListTablesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListTables not implemented")
}
func (UnimplementedCatalogServer) DescribeTable(context.Context, *DescribeTableRequest) (*DescribeTableResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DescribeTable not implemented")
}
func (UnimplementedCatalogServer) InsertRows(context.Context, *InsertRowsRequest) (*InsertRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method InsertRows not implemented")
}
func (UnimplementedCatalogServer) ListRows(context.Context, *ListRowsRequest) (*ListRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRows not implemented")
}
func (UnimplementedCatalogServer) ListRoutines(context.Context, *ListRoutinesRequest) (*ListRoutinesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRoutines not implemented")
}
func (UnimplementedCatalogServer) GetRoutine(context.Context, *GetRoutineRequest) (*GetRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoutine not implemented")
}
func (UnimplementedCatalogServer) UpsertRoutine(context.Context, *UpsertRoutineRequest) (*UpsertRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRoutine not implemented")
}
func (UnimplementedCatalogServer) DeleteRoutine(context.Context, *DeleteRoutineRequest) (*DeleteRoutineResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRoutine not implemented")
}
func (UnimplementedCatalogServer) UpsertRowAccessPolicy(context.Context, *UpsertRowAccessPolicyRequest) (*UpsertRowAccessPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpsertRowAccessPolicy not implemented")
}
func (UnimplementedCatalogServer) DeleteRowAccessPolicy(context.Context, *DeleteRowAccessPolicyRequest) (*DeleteRowAccessPolicyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteRowAccessPolicy not implemented")
}
func (UnimplementedCatalogServer) ListRowAccessPolicies(context.Context, *ListRowAccessPoliciesRequest) (*ListRowAccessPoliciesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListRowAccessPolicies not implemented")
}
func (UnimplementedCatalogServer) SetColumnGovernance(context.Context, *SetColumnGovernanceRequest) (*SetColumnGovernanceResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SetColumnGovernance not implemented")
}
func (UnimplementedCatalogServer) testEmbeddedByValue() {}

// UnsafeCatalogServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to CatalogServer will
// result in compilation errors.
type UnsafeCatalogServer interface {
	mustEmbedUnimplementedCatalogServer()
}

func RegisterCatalogServer(s grpc.ServiceRegistrar, srv CatalogServer) {
	// If the following call panics, it indicates UnimplementedCatalogServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Catalog_ServiceDesc, srv)
}

func _Catalog_RegisterDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).RegisterDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_RegisterDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).RegisterDataset(ctx, req.(*RegisterDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DropDataset_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropDatasetRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DropDataset(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DropDataset_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DropDataset(ctx, req.(*DropDatasetRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListDatasets_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDatasetsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListDatasets(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListDatasets_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListDatasets(ctx, req.(*ListDatasetsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_RegisterTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).RegisterTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_RegisterTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).RegisterTable(ctx, req.(*RegisterTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DropTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DropTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DropTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DropTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DropTable(ctx, req.(*DropTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListTables_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListTablesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListTables(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListTables_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListTables(ctx, req.(*ListTablesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DescribeTable_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DescribeTableRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DescribeTable(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DescribeTable_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DescribeTable(ctx, req.(*DescribeTableRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_InsertRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(InsertRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).InsertRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_InsertRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).InsertRows(ctx, req.(*InsertRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListRows(ctx, req.(*ListRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListRoutines_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRoutinesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListRoutines(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListRoutines_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListRoutines(ctx, req.(*ListRoutinesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_GetRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).GetRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_GetRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).GetRoutine(ctx, req.(*GetRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpsertRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpsertRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_UpsertRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpsertRoutine(ctx, req.(*UpsertRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DeleteRoutine_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRoutineRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DeleteRoutine(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DeleteRoutine_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DeleteRoutine(ctx, req.(*DeleteRoutineRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_UpsertRowAccessPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpsertRowAccessPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).UpsertRowAccessPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_UpsertRowAccessPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).UpsertRowAccessPolicy(ctx, req.(*UpsertRowAccessPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_DeleteRowAccessPolicy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteRowAccessPolicyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).DeleteRowAccessPolicy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_DeleteRowAccessPolicy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).DeleteRowAccessPolicy(ctx, req.(*DeleteRowAccessPolicyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_ListRowAccessPolicies_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListRowAccessPoliciesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).ListRowAccessPolicies(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_ListRowAccessPolicies_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).ListRowAccessPolicies(ctx, req.(*ListRowAccessPoliciesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Catalog_SetColumnGovernance_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SetColumnGovernanceRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(CatalogServer).SetColumnGovernance(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Catalog_SetColumnGovernance_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(CatalogServer).SetColumnGovernance(ctx, req.(*SetColumnGovernanceRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// Catalog_ServiceDesc is the grpc.ServiceDesc for Catalog service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Catalog_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.Catalog",
	HandlerType: (*CatalogServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "RegisterDataset",
			Handler:    _Catalog_RegisterDataset_Handler,
		},
		{
			MethodName: "DropDataset",
			Handler:    _Catalog_DropDataset_Handler,
		},
		{
			MethodName: "ListDatasets",
			Handler:    _Catalog_ListDatasets_Handler,
		},
		{
			MethodName: "RegisterTable",
			Handler:    _Catalog_RegisterTable_Handler,
		},
		{
			MethodName: "DropTable",
			Handler:    _Catalog_DropTable_Handler,
		},
		{
			MethodName: "ListTables",
			Handler:    _Catalog_ListTables_Handler,
		},
		{
			MethodName: "DescribeTable",
			Handler:    _Catalog_DescribeTable_Handler,
		},
		{
			MethodName: "InsertRows",
			Handler:    _Catalog_InsertRows_Handler,
		},
		{
			MethodName: "ListRows",
			Handler:    _Catalog_ListRows_Handler,
		},
		{
			MethodName: "ListRoutines",
			Handler:    _Catalog_ListRoutines_Handler,
		},
		{
			MethodName: "GetRoutine",
			Handler:    _Catalog_GetRoutine_Handler,
		},
		{
			MethodName: "UpsertRoutine",
			Handler:    _Catalog_UpsertRoutine_Handler,
		},
		{
			MethodName: "DeleteRoutine",
			Handler:    _Catalog_DeleteRoutine_Handler,
		},
		{
			MethodName: "UpsertRowAccessPolicy",
			Handler:    _Catalog_UpsertRowAccessPolicy_Handler,
		},
		{
			MethodName: "DeleteRowAccessPolicy",
			Handler:    _Catalog_DeleteRowAccessPolicy_Handler,
		},
		{
			MethodName: "ListRowAccessPolicies",
			Handler:    _Catalog_ListRowAccessPolicies_Handler,
		},
		{
			MethodName: "SetColumnGovernance",
			Handler:    _Catalog_SetColumnGovernance_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emulator.proto",
}

const (
	Query_DryRun_FullMethodName       = "/bigquery_emulator.v1.Query/DryRun"
	Query_ExecuteQuery_FullMethodName = "/bigquery_emulator.v1.Query/ExecuteQuery"
)

// QueryClient is the client API for Query service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueryClient interface {
	DryRun(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*DryRunResponse, error)
	ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultRow], error)
}

type queryClient struct {
	cc grpc.ClientConnInterface
}

func NewQueryClient(cc grpc.ClientConnInterface) QueryClient {
	return &queryClient{cc}
}

func (c *queryClient) DryRun(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (*DryRunResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DryRunResponse)
	err := c.cc.Invoke(ctx, Query_DryRun_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queryClient) ExecuteQuery(ctx context.Context, in *QueryRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[QueryResultRow], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &Query_ServiceDesc.Streams[0], Query_ExecuteQuery_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[QueryRequest, QueryResultRow]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Query_ExecuteQueryClient = grpc.ServerStreamingClient[QueryResultRow]

// QueryServer is the server API for Query service.
// All implementations should embed UnimplementedQueryServer
// for forward compatibility.
type QueryServer interface {
	DryRun(context.Context, *QueryRequest) (*DryRunResponse, error)
	ExecuteQuery(*QueryRequest, grpc.ServerStreamingServer[QueryResultRow]) error
}

// UnimplementedQueryServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueryServer struct{}

func (UnimplementedQueryServer) DryRun(context.Context, *QueryRequest) (*DryRunResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DryRun not implemented")
}
func (UnimplementedQueryServer) ExecuteQuery(*QueryRequest, grpc.ServerStreamingServer[QueryResultRow]) error {
	return status.Error(codes.Unimplemented, "method ExecuteQuery not implemented")
}
func (UnimplementedQueryServer) testEmbeddedByValue() {}

// UnsafeQueryServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueryServer will
// result in compilation errors.
type UnsafeQueryServer interface {
	mustEmbedUnimplementedQueryServer()
}

func RegisterQueryServer(s grpc.ServiceRegistrar, srv QueryServer) {
	// If the following call panics, it indicates UnimplementedQueryServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&Query_ServiceDesc, srv)
}

func _Query_DryRun_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueryServer).DryRun(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: Query_DryRun_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueryServer).DryRun(ctx, req.(*QueryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _Query_ExecuteQuery_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(QueryRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueryServer).ExecuteQuery(m, &grpc.GenericServerStream[QueryRequest, QueryResultRow]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type Query_ExecuteQueryServer = grpc.ServerStreamingServer[QueryResultRow]

// Query_ServiceDesc is the grpc.ServiceDesc for Query service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var Query_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.Query",
	HandlerType: (*QueryServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "DryRun",
			Handler:    _Query_DryRun_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ExecuteQuery",
			Handler:       _Query_ExecuteQuery_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "emulator.proto",
}

const (
	SqlTools_Format_FullMethodName   = "/bigquery_emulator.v1.SqlTools/Format"
	SqlTools_Parse_FullMethodName    = "/bigquery_emulator.v1.SqlTools/Parse"
	SqlTools_Tokenize_FullMethodName = "/bigquery_emulator.v1.SqlTools/Tokenize"
	SqlTools_Complete_FullMethodName = "/bigquery_emulator.v1.SqlTools/Complete"
	SqlTools_Analyze_FullMethodName  = "/bigquery_emulator.v1.SqlTools/Analyze"
)

// SqlToolsClient is the client API for SqlTools service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SqlToolsClient interface {
	Format(ctx context.Context, in *FormatSqlRequest, opts ...grpc.CallOption) (*FormatSqlResponse, error)
	Parse(ctx context.Context, in *ParseSqlRequest, opts ...grpc.CallOption) (*ParseSqlResponse, error)
	Tokenize(ctx context.Context, in *TokenizeSqlRequest, opts ...grpc.CallOption) (*TokenizeSqlResponse, error)
	Complete(ctx context.Context, in *CompleteSqlRequest, opts ...grpc.CallOption) (*CompleteSqlResponse, error)
	Analyze(ctx context.Context, in *AnalyzeSqlRequest, opts ...grpc.CallOption) (*AnalyzeSqlResponse, error)
}

type sqlToolsClient struct {
	cc grpc.ClientConnInterface
}

func NewSqlToolsClient(cc grpc.ClientConnInterface) SqlToolsClient {
	return &sqlToolsClient{cc}
}

func (c *sqlToolsClient) Format(ctx context.Context, in *FormatSqlRequest, opts ...grpc.CallOption) (*FormatSqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FormatSqlResponse)
	err := c.cc.Invoke(ctx, SqlTools_Format_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlToolsClient) Parse(ctx context.Context, in *ParseSqlRequest, opts ...grpc.CallOption) (*ParseSqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ParseSqlResponse)
	err := c.cc.Invoke(ctx, SqlTools_Parse_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlToolsClient) Tokenize(ctx context.Context, in *TokenizeSqlRequest, opts ...grpc.CallOption) (*TokenizeSqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(TokenizeSqlResponse)
	err := c.cc.Invoke(ctx, SqlTools_Tokenize_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlToolsClient) Complete(ctx context.Context, in *CompleteSqlRequest, opts ...grpc.CallOption) (*CompleteSqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompleteSqlResponse)
	err := c.cc.Invoke(ctx, SqlTools_Complete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *sqlToolsClient) Analyze(ctx context.Context, in *AnalyzeSqlRequest, opts ...grpc.CallOption) (*AnalyzeSqlResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeSqlResponse)
	err := c.cc.Invoke(ctx, SqlTools_Analyze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SqlToolsServer is the server API for SqlTools service.
// All implementations should embed UnimplementedSqlToolsServer
// for forward compatibility.
type SqlToolsServer interface {
	Format(context.Context, *FormatSqlRequest) (*FormatSqlResponse, error)
	Parse(context.Context, *ParseSqlRequest) (*ParseSqlResponse, error)
	Tokenize(context.Context, *TokenizeSqlRequest) (*TokenizeSqlResponse, error)
	Complete(context.Context, *CompleteSqlRequest) (*CompleteSqlResponse, error)
	Analyze(context.Context, *AnalyzeSqlRequest) (*AnalyzeSqlResponse, error)
}

// UnimplementedSqlToolsServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSqlToolsServer struct{}

func (UnimplementedSqlToolsServer) Format(context.Context, *FormatSqlRequest) (*FormatSqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Format not implemented")
}
func (UnimplementedSqlToolsServer) Parse(context.Context, *ParseSqlRequest) (*ParseSqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Parse not implemented")
}
func (UnimplementedSqlToolsServer) Tokenize(context.Context, *TokenizeSqlRequest) (*TokenizeSqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Tokenize not implemented")
}
func (UnimplementedSqlToolsServer) Complete(context.Context, *CompleteSqlRequest) (*CompleteSqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Complete not implemented")
}
func (UnimplementedSqlToolsServer) Analyze(context.Context, *AnalyzeSqlRequest) (*AnalyzeSqlResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Analyze not implemented")
}
func (UnimplementedSqlToolsServer) testEmbeddedByValue() {}

// UnsafeSqlToolsServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SqlToolsServer will
// result in compilation errors.
type UnsafeSqlToolsServer interface {
	mustEmbedUnimplementedSqlToolsServer()
}

func RegisterSqlToolsServer(s grpc.ServiceRegistrar, srv SqlToolsServer) {
	// If the following call panics, it indicates UnimplementedSqlToolsServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SqlTools_ServiceDesc, srv)
}

func _SqlTools_Format_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FormatSqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlToolsServer).Format(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlTools_Format_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlToolsServer).Format(ctx, req.(*FormatSqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlTools_Parse_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ParseSqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlToolsServer).Parse(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlTools_Parse_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlToolsServer).Parse(ctx, req.(*ParseSqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlTools_Tokenize_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(TokenizeSqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlToolsServer).Tokenize(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlTools_Tokenize_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlToolsServer).Tokenize(ctx, req.(*TokenizeSqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlTools_Complete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompleteSqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlToolsServer).Complete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlTools_Complete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlToolsServer).Complete(ctx, req.(*CompleteSqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SqlTools_Analyze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeSqlRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SqlToolsServer).Analyze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SqlTools_Analyze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SqlToolsServer).Analyze(ctx, req.(*AnalyzeSqlRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SqlTools_ServiceDesc is the grpc.ServiceDesc for SqlTools service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SqlTools_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.SqlTools",
	HandlerType: (*SqlToolsServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Format",
			Handler:    _SqlTools_Format_Handler,
		},
		{
			MethodName: "Parse",
			Handler:    _SqlTools_Parse_Handler,
		},
		{
			MethodName: "Tokenize",
			Handler:    _SqlTools_Tokenize_Handler,
		},
		{
			MethodName: "Complete",
			Handler:    _SqlTools_Complete_Handler,
		},
		{
			MethodName: "Analyze",
			Handler:    _SqlTools_Analyze_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "emulator.proto",
}
