// storage_read.proto is the internal contract for the BigQuery Storage
// Read API surface (BQ public name: `google.cloud.bigquery.storage.v1`).
// The Go gateway translates REST `tabledata.list` reads against large
// tables into Storage Read RPCs against this service so the C++ engine
// can stream rows back without the entire result set living in the
// gateway's heap.
//
// The engine implements `CreateReadSession` and the streaming
// `ReadRows` reply, including per-column projection
// (`selected_fields`) and `row_restriction` pushdown, and the gateway
// is wired to it (with e2e coverage under `gateway/e2e/`). The shape
// here is the **simplified** Storage Read v1 contract: no Arrow/Avro
// projections (rows ride on the same `DataRow` cells that
// `Catalog.ListRows` already returns), no SplitReadStream RPC, no
// session liveness extension. Those are documented as "future" so
// the conformance harness can pin per-feature gaps.
//
// Code generation:
//   - Go:  `task proto:gen` writes
//          `gateway/enginepb/storage_read.{pb,grpc.pb}.go`. Same
//          plugin pipeline as `emulator.proto`.
//   - C++: Bazel's `cc_proto_library` + `cc_grpc_library` rules in
//          `proto/BUILD.bazel` emit
//          `storage_read.{pb,grpc.pb}.{h,cc}` into bazel-bin.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: storage_read.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateReadSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BigQuery resource path the session belongs to: `projects/{project_id}`.
	// The gateway derives this from the REST URL path so different
	// projects do not see each other's sessions.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Session shape the caller wants to read. `read_session.table` names
	// the table; `read_options.selected_fields` and
	// `read_options.row_restriction` are validated here and applied when
	// the streams are drained.
	ReadSession *ReadSession `protobuf:"bytes,2,opt,name=read_session,json=readSession,proto3" json:"read_session,omitempty"`
	// Maximum number of streams the caller is willing to drain in
	// parallel. The engine always returns exactly one stream (no
	// parallel reads), regardless of this value.
	MaxStreamCount int32 `protobuf:"varint,3,opt,name=max_stream_count,json=maxStreamCount,proto3" json:"max_stream_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *CreateReadSessionRequest) Reset() {
	*x = CreateReadSessionRequest{}
	mi := &file_storage_read_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateReadSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateReadSessionRequest) ProtoMessage() {}

func (x *CreateReadSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateReadSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateReadSessionRequest) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{0}
}

func (x *CreateReadSessionRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateReadSessionRequest) GetReadSession() *ReadSession {
	if x != nil {
		return x.ReadSession
	}
	return nil
}

func (x *CreateReadSessionRequest) GetMaxStreamCount() int32 {
	if x != nil {
		return x.MaxStreamCount
	}
	return 0
}

type ReadSession struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned session id, of the form
	// `projects/{project_id}/locations/{location}/sessions/{session_id}`.
	// The gateway returns this in the REST `name` field so a follow-up
	// `ReadRows` call can find the session again.
	Name string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	// Fully-qualified BigQuery table id the session is reading from:
	// `projects/{project_id}/datasets/{dataset_id}/tables/{table_id}`.
	// Set on the request side (caller specifies which table to read);
	// echoed back on the response side so the caller does not have to
	// re-derive it.
	Table string `protobuf:"bytes,2,opt,name=table,proto3" json:"table,omitempty"`
	// Schema of the rows the streams will emit. Populated by the engine
	// from `Storage::GetSchema` so the caller can decode the cells the
	// same way it decodes `tabledata.list` rows.
	Schema *TableSchema `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// Subset of fields to read; the engine validates the list at
	// session creation and projects rows to these columns on ReadRows.
	ReadOptions *ReadOptions `protobuf:"bytes,4,opt,name=read_options,json=readOptions,proto3" json:"read_options,omitempty"`
	// Streams the caller can drain. Each one is independent and any
	// single row in `table` appears in exactly one stream. The engine
	// always returns a single stream with the full table.
	Streams       []*ReadStream `protobuf:"bytes,5,rep,name=streams,proto3" json:"streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadSession) Reset() {
	*x = ReadSession{}
	mi := &file_storage_read_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadSession) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadSession) ProtoMessage() {}

func (x *ReadSession) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadSession.ProtoReflect.Descriptor instead.
func (*ReadSession) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{1}
}

func (x *ReadSession) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ReadSession) GetTable() string {
	if x != nil {
		return x.Table
	}
	return ""
}

func (x *ReadSession) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *ReadSession) GetReadOptions() *ReadOptions {
	if x != nil {
		return x.ReadOptions
	}
	return nil
}

func (x *ReadSession) GetStreams() []*ReadStream {
	if x != nil {
		return x.Streams
	}
	return nil
}

type ReadOptions struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Names of the columns the caller wants returned. Empty / unset
	// means "all columns". Non-empty lists are validated at session
	// creation and rows are projected to exactly these columns.
	SelectedFields []string `protobuf:"bytes,1,rep,name=selected_fields,json=selectedFields,proto3" json:"selected_fields,omitempty"`
	// SQL-shaped filter expression the engine pushes down. The
	// supported surface is a single `<column> = <literal>` equality
	// (INT64 / STRING / BOOL literals); anything else is rejected with
	// INVALID_ARGUMENT at CreateReadSession time. The predicate is
	// applied before `offset`, matching BigQuery's documented
	// semantics.
	RowRestriction string `protobuf:"bytes,2,opt,name=row_restriction,json=rowRestriction,proto3" json:"row_restriction,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReadOptions) Reset() {
	*x = ReadOptions{}
	mi := &file_storage_read_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadOptions) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadOptions) ProtoMessage() {}

func (x *ReadOptions) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadOptions.ProtoReflect.Descriptor instead.
func (*ReadOptions) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{2}
}

func (x *ReadOptions) GetSelectedFields() []string {
	if x != nil {
		return x.SelectedFields
	}
	return nil
}

func (x *ReadOptions) GetRowRestriction() string {
	if x != nil {
		return x.RowRestriction
	}
	return ""
}

type ReadStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned stream id of the form
	// `{session_name}/streams/{stream_id}`. The caller passes this
	// back to `ReadRows` to drain rows off this stream.
	Name          string `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadStream) Reset() {
	*x = ReadStream{}
	mi := &file_storage_read_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadStream) ProtoMessage() {}

func (x *ReadStream) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadStream.ProtoReflect.Descriptor instead.
func (*ReadStream) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{3}
}

func (x *ReadStream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type ReadRowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Stream id returned by `CreateReadSession`. The engine looks the
	// session up by stripping the trailing `/streams/{id}` and finding
	// the matching `ReadSession`.
	ReadStream string `protobuf:"bytes,1,opt,name=read_stream,json=readStream,proto3" json:"read_stream,omitempty"`
	// Row offset to resume from. The gateway uses this to re-attach to
	// a stream after a transient failure without re-driving rows the
	// client already received. The engine honors the offset (counted
	// over the post-filter row stream).
	Offset        int64 `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsRequest) Reset() {
	*x = ReadRowsRequest{}
	mi := &file_storage_read_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsRequest) ProtoMessage() {}

func (x *ReadRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsRequest.ProtoReflect.Descriptor instead.
func (*ReadRowsRequest) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{4}
}

func (x *ReadRowsRequest) GetReadStream() string {
	if x != nil {
		return x.ReadStream
	}
	return ""
}

func (x *ReadRowsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type ReadRowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Rows on this page of the stream. The engine streams rows in
	// fixed-size pages (see `kReadRowsBatchSize` in
	// `frontend/handlers/storage_read.cc`).
	Rows []*DataRow `protobuf:"bytes,1,rep,name=rows,proto3" json:"rows,omitempty"`
	// Number of rows in this page. Convenience field so callers do not
	// have to count `rows.size()` on every reply.
	RowCount      int64 `protobuf:"varint,2,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReadRowsResponse) Reset() {
	*x = ReadRowsResponse{}
	mi := &file_storage_read_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReadRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReadRowsResponse) ProtoMessage() {}

func (x *ReadRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_storage_read_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReadRowsResponse.ProtoReflect.Descriptor instead.
func (*ReadRowsResponse) Descriptor() ([]byte, []int) {
	return file_storage_read_proto_rawDescGZIP(), []int{5}
}

func (x *ReadRowsResponse) GetRows() []*DataRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

func (x *ReadRowsResponse) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

var File_storage_read_proto protoreflect.FileDescriptor

const file_storage_read_proto_rawDesc = "" +
	"\n" +
	"\x12storage_read.proto\x12\x14bigquery_emulator.v1\x1a\x0eemulator.proto\"\xa2\x01\n" +
	"\x18CreateReadSessionRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12D\n" +
	"\fread_session\x18\x02 \x01(\v2!.bigquery_emulator.v1.ReadSessionR\vreadSession\x12(\n" +
	"\x10max_stream_count\x18\x03 \x01(\x05R\x0emaxStreamCount\"\xf4\x01\n" +
	"\vReadSession\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x14\n" +
	"\x05table\x18\x02 \x01(\tR\x05table\x129\n" +
	"\x06schema\x18\x03 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\x12D\n" +
	"\fread_options\x18\x04 \x01(\v2!.bigquery_emulator.v1.ReadOptionsR\vreadOptions\x12:\n" +
	"\astreams\x18\x05 \x03(\v2 .bigquery_emulator.v1.ReadStreamR\astreams\"_\n" +
	"\vReadOptions\x12'\n" +
	"\x0fselected_fields\x18\x01 \x03(\tR\x0eselectedFields\x12'\n" +
	"\x0frow_restriction\x18\x02 \x01(\tR\x0erowRestriction\" \n" +
	"\n" +
	"ReadStream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"J\n" +
	"\x0fReadRowsRequest\x12\x1f\n" +
	"\vread_stream\x18\x01 \x01(\tR\n" +
	"readStream\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"b\n" +
	"\x10ReadRowsResponse\x121\n" +
	"\x04rows\x18\x01 \x03(\v2\x1d.bigquery_emulator.v1.DataRowR\x04rows\x12\x1b\n" +
	"\trow_count\x18\x02 \x01(\x03R\browCount2\xd2\x01\n" +
	"\vStorageRead\x12f\n" +
	"\x11CreateReadSession\x12..bigquery_emulator.v1.CreateReadSessionRequest\x1a!.bigquery_emulator.v1.ReadSession\x12[\n" +
	"\bReadRows\x12%.bigquery_emulator.v1.ReadRowsRequest\x1a&.bigquery_emulator.v1.ReadRowsResponse0\x01BFZAgithub.com/vantaboard/bigquery-emulator/gateway/enginepb;enginepb\xf8\x01\x01b\x06proto3"

var (
	file_storage_read_proto_rawDescOnce sync.Once
	file_storage_read_proto_rawDescData []byte
)

func file_storage_read_proto_rawDescGZIP() []byte {
	file_storage_read_proto_rawDescOnce.Do(func() {
		file_storage_read_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_storage_read_proto_rawDesc), len(file_storage_read_proto_rawDesc)))
	})
	return file_storage_read_proto_rawDescData
}

var file_storage_read_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_storage_read_proto_goTypes = []any{
	(*CreateReadSessionRequest)(nil), // 0: bigquery_emulator.v1.CreateReadSessionRequest
	(*ReadSession)(nil),              // 1: bigquery_emulator.v1.ReadSession
	(*ReadOptions)(nil),              // 2: bigquery_emulator.v1.ReadOptions
	(*ReadStream)(nil),               // 3: bigquery_emulator.v1.ReadStream
	(*ReadRowsRequest)(nil),          // 4: bigquery_emulator.v1.ReadRowsRequest
	(*ReadRowsResponse)(nil),         // 5: bigquery_emulator.v1.ReadRowsResponse
	(*TableSchema)(nil),              // 6: bigquery_emulator.v1.TableSchema
	(*DataRow)(nil),                  // 7: bigquery_emulator.v1.DataRow
}
var file_storage_read_proto_depIdxs = []int32{
	1, // 0: bigquery_emulator.v1.CreateReadSessionRequest.read_session:type_name -> bigquery_emulator.v1.ReadSession
	6, // 1: bigquery_emulator.v1.ReadSession.schema:type_name -> bigquery_emulator.v1.TableSchema
	2, // 2: bigquery_emulator.v1.ReadSession.read_options:type_name -> bigquery_emulator.v1.ReadOptions
	3, // 3: bigquery_emulator.v1.ReadSession.streams:type_name -> bigquery_emulator.v1.ReadStream
	7, // 4: bigquery_emulator.v1.ReadRowsResponse.rows:type_name -> bigquery_emulator.v1.DataRow
	0, // 5: bigquery_emulator.v1.StorageRead.CreateReadSession:input_type -> bigquery_emulator.v1.CreateReadSessionRequest
	4, // 6: bigquery_emulator.v1.StorageRead.ReadRows:input_type -> bigquery_emulator.v1.ReadRowsRequest
	1, // 7: bigquery_emulator.v1.StorageRead.CreateReadSession:output_type -> bigquery_emulator.v1.ReadSession
	5, // 8: bigquery_emulator.v1.StorageRead.ReadRows:output_type -> bigquery_emulator.v1.ReadRowsResponse
	7, // [7:9] is the sub-list for method output_type
	5, // [5:7] is the sub-list for method input_type
	5, // [5:5] is the sub-list for extension type_name
	5, // [5:5] is the sub-list for extension extendee
	0, // [0:5] is the sub-list for field type_name
}

func init() { file_storage_read_proto_init() }
func file_storage_read_proto_init() {
	if File_storage_read_proto != nil {
		return
	}
	file_emulator_proto_init()
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_storage_read_proto_rawDesc), len(file_storage_read_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_storage_read_proto_goTypes,
		DependencyIndexes: file_storage_read_proto_depIdxs,
		MessageInfos:      file_storage_read_proto_msgTypes,
	}.Build()
	File_storage_read_proto = out.File
	file_storage_read_proto_goTypes = nil
	file_storage_read_proto_depIdxs = nil
}
