// storage_write.proto is the internal contract for the BigQuery Storage
// Write API surface (BQ public name: `google.cloud.bigquery.storage.v1`).
// The Go gateway translates REST `tabledata.insertAll` calls (and the
// gRPC AppendRows path used directly by the Storage Write client
// libraries) into RPCs against this service so the C++ engine can
// commit rows through the same `DuckDBStorage::AppendRows` primitive
// the local DML executor already uses.
//
// Storage Read/Write API handlers for `_default` and `COMMITTED` stream types
// ship first; `BUFFERED`, `PENDING`, `FlushRows`, `FinalizeWriteStream`, and
// `BatchCommitWriteStreams` reserve proto slots for deferred follow-up (see
// `ROADMAP.md`). Matching handler methods return UNIMPLEMENTED today.
//
// Code generation:
//   - Go:  `task proto:gen` writes
//          `gateway/enginepb/storage_write.{pb,grpc.pb}.go`. Same
//          plugin pipeline as `emulator.proto`.
//   - C++: Bazel's `cc_proto_library` + `cc_grpc_library` rules in
//          `proto/BUILD.bazel` emit
//          `storage_write.{pb,grpc.pb}.{h,cc}` into bazel-bin.

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.0
// source: proto/storage_write.proto

package enginepb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// BigQuery's stream lifecycle vocabulary.
type WriteStream_Type int32

const (
	// Reserved zero-value for proto3. Server treats this as
	// COMMITTED (matching BigQuery's documented default).
	WriteStream_TYPE_UNSPECIFIED WriteStream_Type = 0
	// `_default` and explicit COMMITTED both commit on every
	// AppendRows batch (rows immediately visible to readers).
	// The emulator supports both.
	WriteStream_COMMITTED WriteStream_Type = 1
	// PENDING streams buffer rows server-side until
	// `BatchCommitWriteStreams` makes them visible. Reserved for
	// the deferred follow-up; CreateWriteStream returns
	// UNIMPLEMENTED today.
	WriteStream_PENDING WriteStream_Type = 2
	// BUFFERED streams buffer rows server-side until `FlushRows`
	// advances the visibility offset. Reserved for the deferred
	// follow-up; CreateWriteStream returns UNIMPLEMENTED today.
	WriteStream_BUFFERED WriteStream_Type = 3
)

// Enum value maps for WriteStream_Type.
var (
	WriteStream_Type_name = map[int32]string{
		0: "TYPE_UNSPECIFIED",
		1: "COMMITTED",
		2: "PENDING",
		3: "BUFFERED",
	}
	WriteStream_Type_value = map[string]int32{
		"TYPE_UNSPECIFIED": 0,
		"COMMITTED":        1,
		"PENDING":          2,
		"BUFFERED":         3,
	}
)

func (x WriteStream_Type) Enum() *WriteStream_Type {
	p := new(WriteStream_Type)
	*p = x
	return p
}

func (x WriteStream_Type) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (WriteStream_Type) Descriptor() protoreflect.EnumDescriptor {
	return file_proto_storage_write_proto_enumTypes[0].Descriptor()
}

func (WriteStream_Type) Type() protoreflect.EnumType {
	return &file_proto_storage_write_proto_enumTypes[0]
}

func (x WriteStream_Type) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use WriteStream_Type.Descriptor instead.
func (WriteStream_Type) EnumDescriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{0, 0}
}

// WriteStream describes a write stream by name + type + pinned schema.
// `name` is the server-assigned id of the form
// `{table}/streams/{id}` (or the canonical `_default` reserved name);
// the caller passes it back to `AppendRows`.
type WriteStream struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Server-assigned stream id. Format:
	//
	//	`projects/{p}/datasets/{d}/tables/{t}/streams/{id}`
	//
	// The `_default` stream uses the reserved id `_default`; the
	// engine also accepts that the caller did not call
	// CreateWriteStream first and routes appends to the table's
	// implicit default stream.
	Name string           `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Type WriteStream_Type `protobuf:"varint,2,opt,name=type,proto3,enum=bigquery_emulator.v1.WriteStream_Type" json:"type,omitempty"`
	// Schema the stream pins at creation time. Engine populates this
	// from the source table's `Storage::GetSchema` reply so the
	// caller can sanity-check writer alignment without a follow-up
	// DescribeTable round-trip.
	Schema *TableSchema `protobuf:"bytes,3,opt,name=schema,proto3" json:"schema,omitempty"`
	// RFC3339 timestamp the stream was minted. The handler stamps
	// this so a follow-up `GetWriteStream` can surface stream
	// age (BigQuery uses it for retention windows).
	CreateTime    string `protobuf:"bytes,4,opt,name=create_time,json=createTime,proto3" json:"create_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WriteStream) Reset() {
	*x = WriteStream{}
	mi := &file_proto_storage_write_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WriteStream) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WriteStream) ProtoMessage() {}

func (x *WriteStream) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WriteStream.ProtoReflect.Descriptor instead.
func (*WriteStream) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{0}
}

func (x *WriteStream) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WriteStream) GetType() WriteStream_Type {
	if x != nil {
		return x.Type
	}
	return WriteStream_TYPE_UNSPECIFIED
}

func (x *WriteStream) GetSchema() *TableSchema {
	if x != nil {
		return x.Schema
	}
	return nil
}

func (x *WriteStream) GetCreateTime() string {
	if x != nil {
		return x.CreateTime
	}
	return ""
}

type CreateWriteStreamRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// BigQuery resource path the stream belongs to:
	// `projects/{p}/datasets/{d}/tables/{t}`.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Stream shape the caller wants. Only `type` is read today;
	// `name` and `schema` are server-populated.
	WriteStream   *WriteStream `protobuf:"bytes,2,opt,name=write_stream,json=writeStream,proto3" json:"write_stream,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateWriteStreamRequest) Reset() {
	*x = CreateWriteStreamRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateWriteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateWriteStreamRequest) ProtoMessage() {}

func (x *CreateWriteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateWriteStreamRequest.ProtoReflect.Descriptor instead.
func (*CreateWriteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{1}
}

func (x *CreateWriteStreamRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *CreateWriteStreamRequest) GetWriteStream() *WriteStream {
	if x != nil {
		return x.WriteStream
	}
	return nil
}

type AppendRowsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The full stream name (matching `WriteStream.name`). Required on
	// the first message; subsequent messages on the same stream may
	// leave this empty (the handler keeps the first message's
	// binding) or re-assert the same value.
	WriteStream string `protobuf:"bytes,1,opt,name=write_stream,json=writeStream,proto3" json:"write_stream,omitempty"`
	// Optional offset for ordered append. The handler ignores the
	// value for `_default` / `COMMITTED` (every append is immediately
	// committed in arrival order); the field is here so the wire
	// shape is forward-compatible with BUFFERED / PENDING flows.
	Offset    int64                        `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	ProtoRows *AppendRowsRequest_ProtoData `protobuf:"bytes,4,opt,name=proto_rows,json=protoRows,proto3" json:"proto_rows,omitempty"`
	// Caller-supplied trace id, mirrored back on the response so
	// the producer can correlate appends with replies. Optional.
	TraceId       string `protobuf:"bytes,6,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRowsRequest) Reset() {
	*x = AppendRowsRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRowsRequest) ProtoMessage() {}

func (x *AppendRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRowsRequest.ProtoReflect.Descriptor instead.
func (*AppendRowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{2}
}

func (x *AppendRowsRequest) GetWriteStream() string {
	if x != nil {
		return x.WriteStream
	}
	return ""
}

func (x *AppendRowsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

func (x *AppendRowsRequest) GetProtoRows() *AppendRowsRequest_ProtoData {
	if x != nil {
		return x.ProtoRows
	}
	return nil
}

func (x *AppendRowsRequest) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

type AppendRowsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Either AppendResult or error is set, never both.
	//
	// Types that are valid to be assigned to Response:
	//
	//	*AppendRowsResponse_AppendResult_
	//	*AppendRowsResponse_ErrorMessage
	Response isAppendRowsResponse_Response `protobuf_oneof:"response"`
	// Trace id echoed from the request (when set). Empty if the
	// request did not pin one.
	TraceId string `protobuf:"bytes,3,opt,name=trace_id,json=traceId,proto3" json:"trace_id,omitempty"`
	// Number of rows the engine committed for this request. The
	// public surface does not advertise this on success; we surface
	// it explicitly so the in-process gRPC test can assert per-batch
	// commit counts without re-querying the table.
	RowCount      int64 `protobuf:"varint,4,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRowsResponse) Reset() {
	*x = AppendRowsResponse{}
	mi := &file_proto_storage_write_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRowsResponse) ProtoMessage() {}

func (x *AppendRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRowsResponse.ProtoReflect.Descriptor instead.
func (*AppendRowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{3}
}

func (x *AppendRowsResponse) GetResponse() isAppendRowsResponse_Response {
	if x != nil {
		return x.Response
	}
	return nil
}

func (x *AppendRowsResponse) GetAppendResult() *AppendRowsResponse_AppendResult {
	if x != nil {
		if x, ok := x.Response.(*AppendRowsResponse_AppendResult_); ok {
			return x.AppendResult
		}
	}
	return nil
}

func (x *AppendRowsResponse) GetErrorMessage() string {
	if x != nil {
		if x, ok := x.Response.(*AppendRowsResponse_ErrorMessage); ok {
			return x.ErrorMessage
		}
	}
	return ""
}

func (x *AppendRowsResponse) GetTraceId() string {
	if x != nil {
		return x.TraceId
	}
	return ""
}

func (x *AppendRowsResponse) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type isAppendRowsResponse_Response interface {
	isAppendRowsResponse_Response()
}

type AppendRowsResponse_AppendResult_ struct {
	AppendResult *AppendRowsResponse_AppendResult `protobuf:"bytes,1,opt,name=append_result,json=appendResult,proto3,oneof"`
}

type AppendRowsResponse_ErrorMessage struct {
	// Error message from the storage layer (`DuckDBStorage::AppendRows`
	// failures, schema mismatches, ...). The handler maps absl
	// statuses onto a free-form message here; the public BigQuery
	// surface uses `google.rpc.Status` but we keep the simpler
	// shape so we don't pull `google.rpc.status` in.
	ErrorMessage string `protobuf:"bytes,2,opt,name=error_message,json=errorMessage,proto3,oneof"`
}

func (*AppendRowsResponse_AppendResult_) isAppendRowsResponse_Response() {}

func (*AppendRowsResponse_ErrorMessage) isAppendRowsResponse_Response() {}

type GetWriteStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetWriteStreamRequest) Reset() {
	*x = GetWriteStreamRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetWriteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetWriteStreamRequest) ProtoMessage() {}

func (x *GetWriteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetWriteStreamRequest.ProtoReflect.Descriptor instead.
func (*GetWriteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{4}
}

func (x *GetWriteStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FinalizeWriteStreamRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeWriteStreamRequest) Reset() {
	*x = FinalizeWriteStreamRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeWriteStreamRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWriteStreamRequest) ProtoMessage() {}

func (x *FinalizeWriteStreamRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWriteStreamRequest.ProtoReflect.Descriptor instead.
func (*FinalizeWriteStreamRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{5}
}

func (x *FinalizeWriteStreamRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type FinalizeWriteStreamResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Total rows committed on the stream. Reserved for the deferred
	// follow-up; the emulator returns UNIMPLEMENTED.
	RowCount      int64 `protobuf:"varint,1,opt,name=row_count,json=rowCount,proto3" json:"row_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FinalizeWriteStreamResponse) Reset() {
	*x = FinalizeWriteStreamResponse{}
	mi := &file_proto_storage_write_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FinalizeWriteStreamResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FinalizeWriteStreamResponse) ProtoMessage() {}

func (x *FinalizeWriteStreamResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FinalizeWriteStreamResponse.ProtoReflect.Descriptor instead.
func (*FinalizeWriteStreamResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{6}
}

func (x *FinalizeWriteStreamResponse) GetRowCount() int64 {
	if x != nil {
		return x.RowCount
	}
	return 0
}

type BatchCommitWriteStreamsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Parent table that owns the streams.
	Parent string `protobuf:"bytes,1,opt,name=parent,proto3" json:"parent,omitempty"`
	// Stream names to commit atomically. Reserved for the deferred
	// follow-up; the emulator returns UNIMPLEMENTED.
	WriteStreams  []string `protobuf:"bytes,2,rep,name=write_streams,json=writeStreams,proto3" json:"write_streams,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCommitWriteStreamsRequest) Reset() {
	*x = BatchCommitWriteStreamsRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCommitWriteStreamsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCommitWriteStreamsRequest) ProtoMessage() {}

func (x *BatchCommitWriteStreamsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCommitWriteStreamsRequest.ProtoReflect.Descriptor instead.
func (*BatchCommitWriteStreamsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{7}
}

func (x *BatchCommitWriteStreamsRequest) GetParent() string {
	if x != nil {
		return x.Parent
	}
	return ""
}

func (x *BatchCommitWriteStreamsRequest) GetWriteStreams() []string {
	if x != nil {
		return x.WriteStreams
	}
	return nil
}

type BatchCommitWriteStreamsResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// RFC3339 timestamp the commit landed. Reserved for the deferred
	// follow-up.
	CommitTime    string `protobuf:"bytes,1,opt,name=commit_time,json=commitTime,proto3" json:"commit_time,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchCommitWriteStreamsResponse) Reset() {
	*x = BatchCommitWriteStreamsResponse{}
	mi := &file_proto_storage_write_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchCommitWriteStreamsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchCommitWriteStreamsResponse) ProtoMessage() {}

func (x *BatchCommitWriteStreamsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchCommitWriteStreamsResponse.ProtoReflect.Descriptor instead.
func (*BatchCommitWriteStreamsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{8}
}

func (x *BatchCommitWriteStreamsResponse) GetCommitTime() string {
	if x != nil {
		return x.CommitTime
	}
	return ""
}

type FlushRowsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WriteStream   string                 `protobuf:"bytes,1,opt,name=write_stream,json=writeStream,proto3" json:"write_stream,omitempty"`
	Offset        int64                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRowsRequest) Reset() {
	*x = FlushRowsRequest{}
	mi := &file_proto_storage_write_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRowsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRowsRequest) ProtoMessage() {}

func (x *FlushRowsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRowsRequest.ProtoReflect.Descriptor instead.
func (*FlushRowsRequest) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{9}
}

func (x *FlushRowsRequest) GetWriteStream() string {
	if x != nil {
		return x.WriteStream
	}
	return ""
}

func (x *FlushRowsRequest) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type FlushRowsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FlushRowsResponse) Reset() {
	*x = FlushRowsResponse{}
	mi := &file_proto_storage_write_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FlushRowsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FlushRowsResponse) ProtoMessage() {}

func (x *FlushRowsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FlushRowsResponse.ProtoReflect.Descriptor instead.
func (*FlushRowsResponse) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{10}
}

func (x *FlushRowsResponse) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

// ProtoData carries the rows + the writer's schema. The writer
// schema is informational today (we trust the table's schema for
// shape validation); the rows ride on `DataRow` cells, the same
// shape `Catalog.InsertRows` uses.
type AppendRowsRequest_ProtoData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	WriterSchema  *TableSchema           `protobuf:"bytes,1,opt,name=writer_schema,json=writerSchema,proto3" json:"writer_schema,omitempty"`
	Rows          []*DataRow             `protobuf:"bytes,2,rep,name=rows,proto3" json:"rows,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRowsRequest_ProtoData) Reset() {
	*x = AppendRowsRequest_ProtoData{}
	mi := &file_proto_storage_write_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRowsRequest_ProtoData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRowsRequest_ProtoData) ProtoMessage() {}

func (x *AppendRowsRequest_ProtoData) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRowsRequest_ProtoData.ProtoReflect.Descriptor instead.
func (*AppendRowsRequest_ProtoData) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{2, 0}
}

func (x *AppendRowsRequest_ProtoData) GetWriterSchema() *TableSchema {
	if x != nil {
		return x.WriterSchema
	}
	return nil
}

func (x *AppendRowsRequest_ProtoData) GetRows() []*DataRow {
	if x != nil {
		return x.Rows
	}
	return nil
}

// AppendResult is the success envelope; carries the offset of
// the first row in the batch on a `_default` / `COMMITTED`
// stream that's just `prior_offset + 0` (every append commits
// in arrival order).
type AppendRowsResponse_AppendResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Offset        int64                  `protobuf:"varint,1,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AppendRowsResponse_AppendResult) Reset() {
	*x = AppendRowsResponse_AppendResult{}
	mi := &file_proto_storage_write_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AppendRowsResponse_AppendResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AppendRowsResponse_AppendResult) ProtoMessage() {}

func (x *AppendRowsResponse_AppendResult) ProtoReflect() protoreflect.Message {
	mi := &file_proto_storage_write_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AppendRowsResponse_AppendResult.ProtoReflect.Descriptor instead.
func (*AppendRowsResponse_AppendResult) Descriptor() ([]byte, []int) {
	return file_proto_storage_write_proto_rawDescGZIP(), []int{3, 0}
}

func (x *AppendRowsResponse_AppendResult) GetOffset() int64 {
	if x != nil {
		return x.Offset
	}
	return 0
}

var File_proto_storage_write_proto protoreflect.FileDescriptor

const file_proto_storage_write_proto_rawDesc = "" +
	"\n" +
	"\x19proto/storage_write.proto\x12\x14bigquery_emulator.v1\x1a\x14proto/emulator.proto\"\x81\x02\n" +
	"\vWriteStream\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12:\n" +
	"\x04type\x18\x02 \x01(\x0e2&.bigquery_emulator.v1.WriteStream.TypeR\x04type\x129\n" +
	"\x06schema\x18\x03 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\x06schema\x12\x1f\n" +
	"\vcreate_time\x18\x04 \x01(\tR\n" +
	"createTime\"F\n" +
	"\x04Type\x12\x14\n" +
	"\x10TYPE_UNSPECIFIED\x10\x00\x12\r\n" +
	"\tCOMMITTED\x10\x01\x12\v\n" +
	"\aPENDING\x10\x02\x12\f\n" +
	"\bBUFFERED\x10\x03\"x\n" +
	"\x18CreateWriteStreamRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12D\n" +
	"\fwrite_stream\x18\x02 \x01(\v2!.bigquery_emulator.v1.WriteStreamR\vwriteStream\"\xc4\x02\n" +
	"\x11AppendRowsRequest\x12!\n" +
	"\fwrite_stream\x18\x01 \x01(\tR\vwriteStream\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\x12P\n" +
	"\n" +
	"proto_rows\x18\x04 \x01(\v21.bigquery_emulator.v1.AppendRowsRequest.ProtoDataR\tprotoRows\x12\x19\n" +
	"\btrace_id\x18\x06 \x01(\tR\atraceId\x1a\x86\x01\n" +
	"\tProtoData\x12F\n" +
	"\rwriter_schema\x18\x01 \x01(\v2!.bigquery_emulator.v1.TableSchemaR\fwriterSchema\x121\n" +
	"\x04rows\x18\x02 \x03(\v2\x1d.bigquery_emulator.v1.DataRowR\x04rows\"\x85\x02\n" +
	"\x12AppendRowsResponse\x12\\\n" +
	"\rappend_result\x18\x01 \x01(\v25.bigquery_emulator.v1.AppendRowsResponse.AppendResultH\x00R\fappendResult\x12%\n" +
	"\rerror_message\x18\x02 \x01(\tH\x00R\ferrorMessage\x12\x19\n" +
	"\btrace_id\x18\x03 \x01(\tR\atraceId\x12\x1b\n" +
	"\trow_count\x18\x04 \x01(\x03R\browCount\x1a&\n" +
	"\fAppendResult\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offsetB\n" +
	"\n" +
	"\bresponse\"+\n" +
	"\x15GetWriteStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"0\n" +
	"\x1aFinalizeWriteStreamRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\":\n" +
	"\x1bFinalizeWriteStreamResponse\x12\x1b\n" +
	"\trow_count\x18\x01 \x01(\x03R\browCount\"]\n" +
	"\x1eBatchCommitWriteStreamsRequest\x12\x16\n" +
	"\x06parent\x18\x01 \x01(\tR\x06parent\x12#\n" +
	"\rwrite_streams\x18\x02 \x03(\tR\fwriteStreams\"B\n" +
	"\x1fBatchCommitWriteStreamsResponse\x12\x1f\n" +
	"\vcommit_time\x18\x01 \x01(\tR\n" +
	"commitTime\"M\n" +
	"\x10FlushRowsRequest\x12!\n" +
	"\fwrite_stream\x18\x01 \x01(\tR\vwriteStream\x12\x16\n" +
	"\x06offset\x18\x02 \x01(\x03R\x06offset\"+\n" +
	"\x11FlushRowsResponse\x12\x16\n" +
	"\x06offset\x18\x01 \x01(\x03R\x06offset2\xa0\x05\n" +
	"\fStorageWrite\x12f\n" +
	"\x11CreateWriteStream\x12..bigquery_emulator.v1.CreateWriteStreamRequest\x1a!.bigquery_emulator.v1.WriteStream\x12c\n" +
	"\n" +
	"AppendRows\x12'.bigquery_emulator.v1.AppendRowsRequest\x1a(.bigquery_emulator.v1.AppendRowsResponse(\x010\x01\x12`\n" +
	"\x0eGetWriteStream\x12+.bigquery_emulator.v1.GetWriteStreamRequest\x1a!.bigquery_emulator.v1.WriteStream\x12z\n" +
	"\x13FinalizeWriteStream\x120.bigquery_emulator.v1.FinalizeWriteStreamRequest\x1a1.bigquery_emulator.v1.FinalizeWriteStreamResponse\x12\x86\x01\n" +
	"\x17BatchCommitWriteStreams\x124.bigquery_emulator.v1.BatchCommitWriteStreamsRequest\x1a5.bigquery_emulator.v1.BatchCommitWriteStreamsResponse\x12\\\n" +
	"\tFlushRows\x12&.bigquery_emulator.v1.FlushRowsRequest\x1a'.bigquery_emulator.v1.FlushRowsResponseBFZAgithub.com/vantaboard/bigquery-emulator/gateway/enginepb;enginepb\xf8\x01\x01b\x06proto3"

var (
	file_proto_storage_write_proto_rawDescOnce sync.Once
	file_proto_storage_write_proto_rawDescData []byte
)

func file_proto_storage_write_proto_rawDescGZIP() []byte {
	file_proto_storage_write_proto_rawDescOnce.Do(func() {
		file_proto_storage_write_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_storage_write_proto_rawDesc), len(file_proto_storage_write_proto_rawDesc)))
	})
	return file_proto_storage_write_proto_rawDescData
}

var file_proto_storage_write_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_proto_storage_write_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_proto_storage_write_proto_goTypes = []any{
	(WriteStream_Type)(0),                   // 0: bigquery_emulator.v1.WriteStream.Type
	(*WriteStream)(nil),                     // 1: bigquery_emulator.v1.WriteStream
	(*CreateWriteStreamRequest)(nil),        // 2: bigquery_emulator.v1.CreateWriteStreamRequest
	(*AppendRowsRequest)(nil),               // 3: bigquery_emulator.v1.AppendRowsRequest
	(*AppendRowsResponse)(nil),              // 4: bigquery_emulator.v1.AppendRowsResponse
	(*GetWriteStreamRequest)(nil),           // 5: bigquery_emulator.v1.GetWriteStreamRequest
	(*FinalizeWriteStreamRequest)(nil),      // 6: bigquery_emulator.v1.FinalizeWriteStreamRequest
	(*FinalizeWriteStreamResponse)(nil),     // 7: bigquery_emulator.v1.FinalizeWriteStreamResponse
	(*BatchCommitWriteStreamsRequest)(nil),  // 8: bigquery_emulator.v1.BatchCommitWriteStreamsRequest
	(*BatchCommitWriteStreamsResponse)(nil), // 9: bigquery_emulator.v1.BatchCommitWriteStreamsResponse
	(*FlushRowsRequest)(nil),                // 10: bigquery_emulator.v1.FlushRowsRequest
	(*FlushRowsResponse)(nil),               // 11: bigquery_emulator.v1.FlushRowsResponse
	(*AppendRowsRequest_ProtoData)(nil),     // 12: bigquery_emulator.v1.AppendRowsRequest.ProtoData
	(*AppendRowsResponse_AppendResult)(nil), // 13: bigquery_emulator.v1.AppendRowsResponse.AppendResult
	(*TableSchema)(nil),                     // 14: bigquery_emulator.v1.TableSchema
	(*DataRow)(nil),                         // 15: bigquery_emulator.v1.DataRow
}
var file_proto_storage_write_proto_depIdxs = []int32{
	0,  // 0: bigquery_emulator.v1.WriteStream.type:type_name -> bigquery_emulator.v1.WriteStream.Type
	14, // 1: bigquery_emulator.v1.WriteStream.schema:type_name -> bigquery_emulator.v1.TableSchema
	1,  // 2: bigquery_emulator.v1.CreateWriteStreamRequest.write_stream:type_name -> bigquery_emulator.v1.WriteStream
	12, // 3: bigquery_emulator.v1.AppendRowsRequest.proto_rows:type_name -> bigquery_emulator.v1.AppendRowsRequest.ProtoData
	13, // 4: bigquery_emulator.v1.AppendRowsResponse.append_result:type_name -> bigquery_emulator.v1.AppendRowsResponse.AppendResult
	14, // 5: bigquery_emulator.v1.AppendRowsRequest.ProtoData.writer_schema:type_name -> bigquery_emulator.v1.TableSchema
	15, // 6: bigquery_emulator.v1.AppendRowsRequest.ProtoData.rows:type_name -> bigquery_emulator.v1.DataRow
	2,  // 7: bigquery_emulator.v1.StorageWrite.CreateWriteStream:input_type -> bigquery_emulator.v1.CreateWriteStreamRequest
	3,  // 8: bigquery_emulator.v1.StorageWrite.AppendRows:input_type -> bigquery_emulator.v1.AppendRowsRequest
	5,  // 9: bigquery_emulator.v1.StorageWrite.GetWriteStream:input_type -> bigquery_emulator.v1.GetWriteStreamRequest
	6,  // 10: bigquery_emulator.v1.StorageWrite.FinalizeWriteStream:input_type -> bigquery_emulator.v1.FinalizeWriteStreamRequest
	8,  // 11: bigquery_emulator.v1.StorageWrite.BatchCommitWriteStreams:input_type -> bigquery_emulator.v1.BatchCommitWriteStreamsRequest
	10, // 12: bigquery_emulator.v1.StorageWrite.FlushRows:input_type -> bigquery_emulator.v1.FlushRowsRequest
	1,  // 13: bigquery_emulator.v1.StorageWrite.CreateWriteStream:output_type -> bigquery_emulator.v1.WriteStream
	4,  // 14: bigquery_emulator.v1.StorageWrite.AppendRows:output_type -> bigquery_emulator.v1.AppendRowsResponse
	1,  // 15: bigquery_emulator.v1.StorageWrite.GetWriteStream:output_type -> bigquery_emulator.v1.WriteStream
	7,  // 16: bigquery_emulator.v1.StorageWrite.FinalizeWriteStream:output_type -> bigquery_emulator.v1.FinalizeWriteStreamResponse
	9,  // 17: bigquery_emulator.v1.StorageWrite.BatchCommitWriteStreams:output_type -> bigquery_emulator.v1.BatchCommitWriteStreamsResponse
	11, // 18: bigquery_emulator.v1.StorageWrite.FlushRows:output_type -> bigquery_emulator.v1.FlushRowsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_storage_write_proto_init() }
func file_proto_storage_write_proto_init() {
	if File_proto_storage_write_proto != nil {
		return
	}
	file_emulator_proto_init()
	file_proto_storage_write_proto_msgTypes[3].OneofWrappers = []any{
		(*AppendRowsResponse_AppendResult_)(nil),
		(*AppendRowsResponse_ErrorMessage)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_storage_write_proto_rawDesc), len(file_proto_storage_write_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_storage_write_proto_goTypes,
		DependencyIndexes: file_proto_storage_write_proto_depIdxs,
		EnumInfos:         file_proto_storage_write_proto_enumTypes,
		MessageInfos:      file_proto_storage_write_proto_msgTypes,
	}.Build()
	File_proto_storage_write_proto = out.File
	file_proto_storage_write_proto_goTypes = nil
	file_proto_storage_write_proto_depIdxs = nil
}
