// storage_read.proto is the internal contract for the BigQuery Storage
// Read API surface (BQ public name: `google.cloud.bigquery.storage.v1`).
// The Go gateway translates REST `tabledata.list` reads against large
// tables into Storage Read RPCs against this service so the C++ engine
// can stream rows back without the entire result set living in the
// gateway's heap.
//
// The engine implements `CreateReadSession` and the streaming
// `ReadRows` reply, including per-column projection
// (`selected_fields`) and `row_restriction` pushdown, and the gateway
// is wired to it (with e2e coverage under `gateway/e2e/`). The shape
// here is the **simplified** Storage Read v1 contract: no Arrow/Avro
// projections (rows ride on the same `DataRow` cells that
// `Catalog.ListRows` already returns), no SplitReadStream RPC, no
// session liveness extension. Those are documented as "future" so
// the conformance harness can pin per-feature gaps.
//
// Code generation:
//   - Go:  `task proto:gen` writes
//          `gateway/enginepb/storage_read.{pb,grpc.pb}.go`. Same
//          plugin pipeline as `emulator.proto`.
//   - C++: Bazel's `cc_proto_library` + `cc_grpc_library` rules in
//          `proto/BUILD.bazel` emit
//          `storage_read.{pb,grpc.pb}.{h,cc}` into bazel-bin.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/storage_read.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageRead_CreateReadSession_FullMethodName = "/bigquery_emulator.v1.StorageRead/CreateReadSession"
	StorageRead_ReadRows_FullMethodName          = "/bigquery_emulator.v1.StorageRead/ReadRows"
	StorageRead_SplitReadStream_FullMethodName   = "/bigquery_emulator.v1.StorageRead/SplitReadStream"
)

// StorageReadClient is the client API for StorageRead service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageReadClient interface {
	// CreateReadSession validates the request, materializes a session
	// pinning the table + schema, and returns the session handle the
	// caller will pass back to `ReadRows`. The reply carries the table
	// schema verbatim so the caller does not need a follow-up
	// `Catalog.DescribeTable` round-trip before starting to read.
	CreateReadSession(ctx context.Context, in *CreateReadSessionRequest, opts ...grpc.CallOption) (*ReadSession, error)
	// ReadRows streams rows off the named stream. The stream id must be
	// one of the `ReadSession.streams[*].name` values returned by the
	// matching `CreateReadSession` call (or a child stream minted by
	// `SplitReadStream`).
	ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error)
	// SplitReadStream subdivides an existing stream's remaining row
	// range into a primary stream (head) and a residual stream (tail).
	SplitReadStream(ctx context.Context, in *SplitReadStreamRequest, opts ...grpc.CallOption) (*SplitReadStreamResponse, error)
}

type storageReadClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageReadClient(cc grpc.ClientConnInterface) StorageReadClient {
	return &storageReadClient{cc}
}

func (c *storageReadClient) CreateReadSession(ctx context.Context, in *CreateReadSessionRequest, opts ...grpc.CallOption) (*ReadSession, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReadSession)
	err := c.cc.Invoke(ctx, StorageRead_CreateReadSession_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageReadClient) ReadRows(ctx context.Context, in *ReadRowsRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[ReadRowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageRead_ServiceDesc.Streams[0], StorageRead_ReadRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[ReadRowsRequest, ReadRowsResponse]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageRead_ReadRowsClient = grpc.ServerStreamingClient[ReadRowsResponse]

func (c *storageReadClient) SplitReadStream(ctx context.Context, in *SplitReadStreamRequest, opts ...grpc.CallOption) (*SplitReadStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SplitReadStreamResponse)
	err := c.cc.Invoke(ctx, StorageRead_SplitReadStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageReadServer is the server API for StorageRead service.
// All implementations should embed UnimplementedStorageReadServer
// for forward compatibility.
type StorageReadServer interface {
	// CreateReadSession validates the request, materializes a session
	// pinning the table + schema, and returns the session handle the
	// caller will pass back to `ReadRows`. The reply carries the table
	// schema verbatim so the caller does not need a follow-up
	// `Catalog.DescribeTable` round-trip before starting to read.
	CreateReadSession(context.Context, *CreateReadSessionRequest) (*ReadSession, error)
	// ReadRows streams rows off the named stream. The stream id must be
	// one of the `ReadSession.streams[*].name` values returned by the
	// matching `CreateReadSession` call (or a child stream minted by
	// `SplitReadStream`).
	ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error
	// SplitReadStream subdivides an existing stream's remaining row
	// range into a primary stream (head) and a residual stream (tail).
	SplitReadStream(context.Context, *SplitReadStreamRequest) (*SplitReadStreamResponse, error)
}

// UnimplementedStorageReadServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageReadServer struct{}

func (UnimplementedStorageReadServer) CreateReadSession(context.Context, *CreateReadSessionRequest) (*ReadSession, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateReadSession not implemented")
}
func (UnimplementedStorageReadServer) ReadRows(*ReadRowsRequest, grpc.ServerStreamingServer[ReadRowsResponse]) error {
	return status.Error(codes.Unimplemented, "method ReadRows not implemented")
}
func (UnimplementedStorageReadServer) SplitReadStream(context.Context, *SplitReadStreamRequest) (*SplitReadStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SplitReadStream not implemented")
}
func (UnimplementedStorageReadServer) testEmbeddedByValue() {}

// UnsafeStorageReadServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageReadServer will
// result in compilation errors.
type UnsafeStorageReadServer interface {
	mustEmbedUnimplementedStorageReadServer()
}

func RegisterStorageReadServer(s grpc.ServiceRegistrar, srv StorageReadServer) {
	// If the following call panics, it indicates UnimplementedStorageReadServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageRead_ServiceDesc, srv)
}

func _StorageRead_CreateReadSession_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateReadSessionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReadServer).CreateReadSession(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageRead_CreateReadSession_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReadServer).CreateReadSession(ctx, req.(*CreateReadSessionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageRead_ReadRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(ReadRowsRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(StorageReadServer).ReadRows(m, &grpc.GenericServerStream[ReadRowsRequest, ReadRowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageRead_ReadRowsServer = grpc.ServerStreamingServer[ReadRowsResponse]

func _StorageRead_SplitReadStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SplitReadStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageReadServer).SplitReadStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageRead_SplitReadStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageReadServer).SplitReadStream(ctx, req.(*SplitReadStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageRead_ServiceDesc is the grpc.ServiceDesc for StorageRead service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageRead_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.StorageRead",
	HandlerType: (*StorageReadServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateReadSession",
			Handler:    _StorageRead_CreateReadSession_Handler,
		},
		{
			MethodName: "SplitReadStream",
			Handler:    _StorageRead_SplitReadStream_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "ReadRows",
			Handler:       _StorageRead_ReadRows_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "proto/storage_read.proto",
}
