// storage_write.proto is the internal contract for the BigQuery Storage
// Write API surface (BQ public name: `google.cloud.bigquery.storage.v1`).
// The Go gateway translates REST `tabledata.insertAll` calls (and the
// gRPC AppendRows path used directly by the Storage Write client
// libraries) into RPCs against this service so the C++ engine can
// commit rows through the same `DuckDBStorage::AppendRows` primitive
// the local DML executor already uses.
//
// Storage Read/Write API handlers for `_default`, `COMMITTED`, `BUFFERED`,
// and `PENDING` stream types ship end-to-end; see `ROADMAP.md` for the
// posture matrix.
//
// Code generation:
//   - Go:  `task proto:gen` writes
//          `gateway/enginepb/storage_write.{pb,grpc.pb}.go`. Same
//          plugin pipeline as `emulator.proto`.
//   - C++: Bazel's `cc_proto_library` + `cc_grpc_library` rules in
//          `proto/BUILD.bazel` emit
//          `storage_write.{pb,grpc.pb}.{h,cc}` into bazel-bin.

// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v3.21.12
// source: proto/storage_write.proto

package enginepb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	StorageWrite_CreateWriteStream_FullMethodName       = "/bigquery_emulator.v1.StorageWrite/CreateWriteStream"
	StorageWrite_AppendRows_FullMethodName              = "/bigquery_emulator.v1.StorageWrite/AppendRows"
	StorageWrite_GetWriteStream_FullMethodName          = "/bigquery_emulator.v1.StorageWrite/GetWriteStream"
	StorageWrite_FinalizeWriteStream_FullMethodName     = "/bigquery_emulator.v1.StorageWrite/FinalizeWriteStream"
	StorageWrite_BatchCommitWriteStreams_FullMethodName = "/bigquery_emulator.v1.StorageWrite/BatchCommitWriteStreams"
	StorageWrite_FlushRows_FullMethodName               = "/bigquery_emulator.v1.StorageWrite/FlushRows"
)

// StorageWriteClient is the client API for StorageWrite service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type StorageWriteClient interface {
	// CreateWriteStream returns a stream handle the caller binds to
	// `AppendRows`. The emulator supports `_default` and `COMMITTED`
	// streams (every flushed batch becomes immediately visible to
	// readers); `BUFFERED` / `PENDING` requests fail with UNIMPLEMENTED
	// until the deferred follow-up lands.
	CreateWriteStream(ctx context.Context, in *CreateWriteStreamRequest, opts ...grpc.CallOption) (*WriteStream, error)
	// AppendRows is bidirectional-streaming. The first message on a
	// stream MUST set `write_stream`; subsequent messages may leave it
	// empty (the handler keeps the binding from the first message) or
	// re-assert the same name. The handler commits each `proto_rows`
	// batch through `Storage::AppendRows` synchronously and replies with
	// one `AppendRowsResponse` per request before reading the next.
	AppendRows(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendRowsRequest, AppendRowsResponse], error)
	// GetWriteStream returns the stream metadata the engine recorded at
	// CreateWriteStream time. Used by clients to verify the stream
	// type / schema before opening an AppendRows session.
	GetWriteStream(ctx context.Context, in *GetWriteStreamRequest, opts ...grpc.CallOption) (*WriteStream, error)
	// FinalizeWriteStream marks a stream as closed. The emulator
	// returns UNIMPLEMENTED today; the surface is reserved for the
	// deferred BUFFERED / PENDING follow-up where finalize is the
	// producer's signal to the BatchCommitWriteStreams pass.
	FinalizeWriteStream(ctx context.Context, in *FinalizeWriteStreamRequest, opts ...grpc.CallOption) (*FinalizeWriteStreamResponse, error)
	// BatchCommitWriteStreams atomically commits a set of `PENDING`
	// streams. The emulator returns UNIMPLEMENTED today; reserved for
	// the deferred follow-up.
	BatchCommitWriteStreams(ctx context.Context, in *BatchCommitWriteStreamsRequest, opts ...grpc.CallOption) (*BatchCommitWriteStreamsResponse, error)
	// FlushRows advances the visibility offset on a `BUFFERED` stream.
	// The emulator returns UNIMPLEMENTED today; reserved for the
	// deferred follow-up.
	FlushRows(ctx context.Context, in *FlushRowsRequest, opts ...grpc.CallOption) (*FlushRowsResponse, error)
}

type storageWriteClient struct {
	cc grpc.ClientConnInterface
}

func NewStorageWriteClient(cc grpc.ClientConnInterface) StorageWriteClient {
	return &storageWriteClient{cc}
}

func (c *storageWriteClient) CreateWriteStream(ctx context.Context, in *CreateWriteStreamRequest, opts ...grpc.CallOption) (*WriteStream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteStream)
	err := c.cc.Invoke(ctx, StorageWrite_CreateWriteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriteClient) AppendRows(ctx context.Context, opts ...grpc.CallOption) (grpc.BidiStreamingClient[AppendRowsRequest, AppendRowsResponse], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &StorageWrite_ServiceDesc.Streams[0], StorageWrite_AppendRows_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[AppendRowsRequest, AppendRowsResponse]{ClientStream: stream}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageWrite_AppendRowsClient = grpc.BidiStreamingClient[AppendRowsRequest, AppendRowsResponse]

func (c *storageWriteClient) GetWriteStream(ctx context.Context, in *GetWriteStreamRequest, opts ...grpc.CallOption) (*WriteStream, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(WriteStream)
	err := c.cc.Invoke(ctx, StorageWrite_GetWriteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriteClient) FinalizeWriteStream(ctx context.Context, in *FinalizeWriteStreamRequest, opts ...grpc.CallOption) (*FinalizeWriteStreamResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FinalizeWriteStreamResponse)
	err := c.cc.Invoke(ctx, StorageWrite_FinalizeWriteStream_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriteClient) BatchCommitWriteStreams(ctx context.Context, in *BatchCommitWriteStreamsRequest, opts ...grpc.CallOption) (*BatchCommitWriteStreamsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchCommitWriteStreamsResponse)
	err := c.cc.Invoke(ctx, StorageWrite_BatchCommitWriteStreams_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *storageWriteClient) FlushRows(ctx context.Context, in *FlushRowsRequest, opts ...grpc.CallOption) (*FlushRowsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(FlushRowsResponse)
	err := c.cc.Invoke(ctx, StorageWrite_FlushRows_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// StorageWriteServer is the server API for StorageWrite service.
// All implementations should embed UnimplementedStorageWriteServer
// for forward compatibility.
type StorageWriteServer interface {
	// CreateWriteStream returns a stream handle the caller binds to
	// `AppendRows`. The emulator supports `_default` and `COMMITTED`
	// streams (every flushed batch becomes immediately visible to
	// readers); `BUFFERED` / `PENDING` requests fail with UNIMPLEMENTED
	// until the deferred follow-up lands.
	CreateWriteStream(context.Context, *CreateWriteStreamRequest) (*WriteStream, error)
	// AppendRows is bidirectional-streaming. The first message on a
	// stream MUST set `write_stream`; subsequent messages may leave it
	// empty (the handler keeps the binding from the first message) or
	// re-assert the same name. The handler commits each `proto_rows`
	// batch through `Storage::AppendRows` synchronously and replies with
	// one `AppendRowsResponse` per request before reading the next.
	AppendRows(grpc.BidiStreamingServer[AppendRowsRequest, AppendRowsResponse]) error
	// GetWriteStream returns the stream metadata the engine recorded at
	// CreateWriteStream time. Used by clients to verify the stream
	// type / schema before opening an AppendRows session.
	GetWriteStream(context.Context, *GetWriteStreamRequest) (*WriteStream, error)
	// FinalizeWriteStream marks a stream as closed. The emulator
	// returns UNIMPLEMENTED today; the surface is reserved for the
	// deferred BUFFERED / PENDING follow-up where finalize is the
	// producer's signal to the BatchCommitWriteStreams pass.
	FinalizeWriteStream(context.Context, *FinalizeWriteStreamRequest) (*FinalizeWriteStreamResponse, error)
	// BatchCommitWriteStreams atomically commits a set of `PENDING`
	// streams. The emulator returns UNIMPLEMENTED today; reserved for
	// the deferred follow-up.
	BatchCommitWriteStreams(context.Context, *BatchCommitWriteStreamsRequest) (*BatchCommitWriteStreamsResponse, error)
	// FlushRows advances the visibility offset on a `BUFFERED` stream.
	// The emulator returns UNIMPLEMENTED today; reserved for the
	// deferred follow-up.
	FlushRows(context.Context, *FlushRowsRequest) (*FlushRowsResponse, error)
}

// UnimplementedStorageWriteServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedStorageWriteServer struct{}

func (UnimplementedStorageWriteServer) CreateWriteStream(context.Context, *CreateWriteStreamRequest) (*WriteStream, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateWriteStream not implemented")
}
func (UnimplementedStorageWriteServer) AppendRows(grpc.BidiStreamingServer[AppendRowsRequest, AppendRowsResponse]) error {
	return status.Error(codes.Unimplemented, "method AppendRows not implemented")
}
func (UnimplementedStorageWriteServer) GetWriteStream(context.Context, *GetWriteStreamRequest) (*WriteStream, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWriteStream not implemented")
}
func (UnimplementedStorageWriteServer) FinalizeWriteStream(context.Context, *FinalizeWriteStreamRequest) (*FinalizeWriteStreamResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FinalizeWriteStream not implemented")
}
func (UnimplementedStorageWriteServer) BatchCommitWriteStreams(context.Context, *BatchCommitWriteStreamsRequest) (*BatchCommitWriteStreamsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchCommitWriteStreams not implemented")
}
func (UnimplementedStorageWriteServer) FlushRows(context.Context, *FlushRowsRequest) (*FlushRowsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method FlushRows not implemented")
}
func (UnimplementedStorageWriteServer) testEmbeddedByValue() {}

// UnsafeStorageWriteServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to StorageWriteServer will
// result in compilation errors.
type UnsafeStorageWriteServer interface {
	mustEmbedUnimplementedStorageWriteServer()
}

func RegisterStorageWriteServer(s grpc.ServiceRegistrar, srv StorageWriteServer) {
	// If the following call panics, it indicates UnimplementedStorageWriteServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&StorageWrite_ServiceDesc, srv)
}

func _StorageWrite_CreateWriteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateWriteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriteServer).CreateWriteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageWrite_CreateWriteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriteServer).CreateWriteStream(ctx, req.(*CreateWriteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWrite_AppendRows_Handler(srv interface{}, stream grpc.ServerStream) error {
	return srv.(StorageWriteServer).AppendRows(&grpc.GenericServerStream[AppendRowsRequest, AppendRowsResponse]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type StorageWrite_AppendRowsServer = grpc.BidiStreamingServer[AppendRowsRequest, AppendRowsResponse]

func _StorageWrite_GetWriteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWriteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriteServer).GetWriteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageWrite_GetWriteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriteServer).GetWriteStream(ctx, req.(*GetWriteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWrite_FinalizeWriteStream_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FinalizeWriteStreamRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriteServer).FinalizeWriteStream(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageWrite_FinalizeWriteStream_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriteServer).FinalizeWriteStream(ctx, req.(*FinalizeWriteStreamRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWrite_BatchCommitWriteStreams_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchCommitWriteStreamsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriteServer).BatchCommitWriteStreams(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageWrite_BatchCommitWriteStreams_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriteServer).BatchCommitWriteStreams(ctx, req.(*BatchCommitWriteStreamsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _StorageWrite_FlushRows_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FlushRowsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(StorageWriteServer).FlushRows(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: StorageWrite_FlushRows_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(StorageWriteServer).FlushRows(ctx, req.(*FlushRowsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// StorageWrite_ServiceDesc is the grpc.ServiceDesc for StorageWrite service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var StorageWrite_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "bigquery_emulator.v1.StorageWrite",
	HandlerType: (*StorageWriteServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateWriteStream",
			Handler:    _StorageWrite_CreateWriteStream_Handler,
		},
		{
			MethodName: "GetWriteStream",
			Handler:    _StorageWrite_GetWriteStream_Handler,
		},
		{
			MethodName: "FinalizeWriteStream",
			Handler:    _StorageWrite_FinalizeWriteStream_Handler,
		},
		{
			MethodName: "BatchCommitWriteStreams",
			Handler:    _StorageWrite_BatchCommitWriteStreams_Handler,
		},
		{
			MethodName: "FlushRows",
			Handler:    _StorageWrite_FlushRows_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "AppendRows",
			Handler:       _StorageWrite_AppendRows_Handler,
			ServerStreams: true,
			ClientStreams: true,
		},
	},
	Metadata: "proto/storage_write.proto",
}
